### ISSUE TITLE
Virtual monitor translation error (Wayland). Error: Unknown Monitor connector type [Meta]: Please report this to the GitHub issue tracker

### ISSUE THREAD

**Issue by Fr1stIT** [LizardByte/Sunshine#3349] opened 2024-10-31 19:57 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Is your issue described in the documentation?

- [ ] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

When trying to broadcast monitor 1 (created virtually, when running `gnome-shell --virtual-monitor <resolution>`), an error occurs. But when I select monitor 0 (built into my laptop), everything is fine. I am attaching two logs. One with monitor 0, the other with monitor 1. 
OS: Fedora 40 (Gnome + Wayland)
[log_display_0.txt](https://github.com/user-attachments/files/17592615/log_display_0.txt)
[log_display_1.txt](https://github.com/user-attachments/files/17592616/log_display_1.txt)

### Host Operating System

Linux

### Operating System Version

Fedora 40

### Architecture

amd64/x86_64

### Sunshine commit or version

2024.911.215654.copr

### Package

Linux - Fedora Copr

### GPU Type

Nvidia

### GPU Model

RTX 3060 Mobile

### GPU Driver/Mesa Version

nvidia-non-free-550

### Capture Method

None

### Config

```Shell
output_name = 1
controller = disabled
keyboard = disabled
mouse = disabled
locale = ru
```

### Relevant log output

```shell
[2024-10-31 14:23:26.616]: Info: Sunshine version: 2024.911.215654.copr
[2024-10-31 14:23:26.616]: Info: Package Publisher: Third Party Publisher
[2024-10-31 14:23:26.616]: Info: Publisher Website: 
[2024-10-31 14:23:26.616]: Info: Get support: https://app.lizardbyte.dev/support
[2024-10-31 14:23:26.648]: Error: Failed to create session: 
[2024-10-31 14:23:26.648]: Info: Found display [wayland-0]
[2024-10-31 14:23:26.652]: Info: Found interface: wl_output(4) version 4
[2024-10-31 14:23:26.653]: Info: Found interface: wl_output(5) version 4
[2024-10-31 14:23:26.653]: Info: Found interface: zxdg_output_manager_v1(6) version 3
[2024-10-31 14:23:26.653]: Warning: Missing Wayland wire for wlr-export-dmabuf
[2024-10-31 14:23:26.654]: Info: /dev/dri/card1 -> i915
[2024-10-31 14:23:26.655]: Info: /dev/dri/card0 -> nvidia-drm
[2024-10-31 14:23:26.657]: Info: Found display [wayland-0]
[2024-10-31 14:23:26.657]: Info: Found display [wayland-0]
[2024-10-31 14:23:26.657]: Info: Found interface: wl_output(4) version 4
[2024-10-31 14:23:26.657]: Info: Found interface: wl_output(5) version 4
[2024-10-31 14:23:26.657]: Info: Found interface: zxdg_output_manager_v1(6) version 3
[2024-10-31 14:23:26.663]: Info: Resolution: 1920x1080
[2024-10-31 14:23:26.663]: Info: Resolution: 2532x1170
[2024-10-31 14:23:26.663]: Info: Offset: 2532x90
[2024-10-31 14:23:26.663]: Info: Logical size: 1920x1080
[2024-10-31 14:23:26.663]: Info: Name: eDP-1
[2024-10-31 14:23:26.663]: Info: Found monitor: Встроенный дисплей
[2024-10-31 14:23:26.663]: Info: Offset: 0x0
[2024-10-31 14:23:26.663]: Info: Logical size: 2532x1170
[2024-10-31 14:23:26.663]: Info: Name: Meta-0
[2024-10-31 14:23:26.663]: Info: Found monitor: MetaVendor
[2024-10-31 14:23:26.663]: Info: -------- Start of KMS monitor list --------
[2024-10-31 14:23:26.663]: Info: Monitor 0 is eDP-1: Встроенный дисплей
[2024-10-31 14:23:26.663]: Error: Unknown Monitor connector type [Meta]: Please report this to the GitHub issue tracker
[2024-10-31 14:23:26.663]: Info: --------- End of KMS monitor list ---------
[2024-10-31 14:23:26.663]: Info: System tray created
[2024-10-31 14:23:26.744]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2024-10-31 14:23:26.744]: Info: Trying encoder [nvenc]
[2024-10-31 14:23:26.744]: Info: Screencasting with KMS
[2024-10-31 14:23:26.744]: Info: /dev/dri/card1 -> i915
[2024-10-31 14:23:26.744]: Info: /dev/dri/card0 -> nvidia-drm
[2024-10-31 14:23:26.744]: Error: Couldn't find monitor [1]
[2024-10-31 14:23:26.744]: Info: /dev/dri/card1 -> i915
[2024-10-31 14:23:26.744]: Info: /dev/dri/card0 -> nvidia-drm
[2024-10-31 14:23:26.744]: Error: Couldn't find monitor [1]
[2024-10-31 14:23:26.944]: Info: Screencasting with KMS
[2024-10-31 14:23:26.945]: Info: /dev/dri/card1 -> i915
[2024-10-31 14:23:26.945]: Info: /dev/dri/card0 -> nvidia-drm
[2024-10-31 14:23:26.945]: Error: Couldn't find monitor [1]
[2024-10-31 14:23:26.945]: Info: /dev/dri/card1 -> i915
[2024-10-31 14:23:26.945]: Info: /dev/dri/card0 -> nvidia-drm
[2024-10-31 14:23:26.945]: Error: Couldn't find monitor [1]
[2024-10-31 14:23:27.146]: Info: Encoder [nvenc] failed
[2024-10-31 14:23:27.146]: Info: Trying encoder [vaapi]
[2024-10-31 14:23:27.146]: Info: Screencasting with KMS
[2024-10-31 14:23:27.146]: Info: /dev/dri/card1 -> i915
[2024-10-31 14:23:27.146]: Info: /dev/dri/card0 -> nvidia-drm
[2024-10-31 14:23:27.146]: Error: Couldn't find monitor [1]
[2024-10-31 14:23:27.146]: Info: /dev/dri/card1 -> i915
[2024-10-31 14:23:27.146]: Info: /dev/dri/card0 -> nvidia-drm
[2024-10-31 14:23:27.146]: Error: Couldn't find monitor [1]
[2024-10-31 14:23:27.346]: Info: Screencasting with KMS
[2024-10-31 14:23:27.346]: Info: /dev/dri/card1 -> i915
[2024-10-31 14:23:27.346]: Info: /dev/dri/card0 -> nvidia-drm
[2024-10-31 14:23:27.347]: Error: Couldn't find monitor [1]
[2024-10-31 14:23:27.347]: Info: /dev/dri/card1 -> i915
[2024-10-31 14:23:27.347]: Info: /dev/dri/card0 -> nvidia-drm
[2024-10-31 14:23:27.347]: Error: Couldn't find monitor [1]
[2024-10-31 14:23:27.547]: Info: Encoder [vaapi] failed
[2024-10-31 14:23:27.547]: Info: Trying encoder [software]
[2024-10-31 14:23:27.547]: Info: Screencasting with KMS
[2024-10-31 14:23:27.547]: Info: /dev/dri/card1 -> i915
[2024-10-31 14:23:27.547]: Info: /dev/dri/card0 -> nvidia-drm
[2024-10-31 14:23:27.547]: Error: Couldn't find monitor [1]
[2024-10-31 14:23:27.748]: Info: Screencasting with KMS
[2024-10-31 14:23:27.748]: Info: /dev/dri/card1 -> i915
[2024-10-31 14:23:27.748]: Info: /dev/dri/card0 -> nvidia-drm
[2024-10-31 14:23:27.748]: Error: Couldn't find monitor [1]
[2024-10-31 14:23:27.948]: Info: Encoder [software] failed
[2024-10-31 14:23:27.948]: Fatal: Unable to find display or encoder during startup.
[2024-10-31 14:23:27.948]: Fatal: Please ensure your manually chosen GPU and monitor are connected and powered on.
[2024-10-31 14:23:27.948]: Error: Video failed to find working encoder
[2024-10-31 14:23:27.950]: Info: Adding avahi service MiWiFi-R4A-srv
[2024-10-31 14:23:27.950]: Info: Configuration UI available at [https://localhost:47990]
[2024-10-31 14:23:28.832]: Info: Avahi service MiWiFi-R4A-srv successfully established.
```

**Comment by ReenigneArcher** [comment] 2024-10-31 21:16
Duplicate of #2250

**Closed by ReenigneArcher** 2024-10-31 21:16 UTC
