### ISSUE TITLE
Sunshine don't detect IGD device.

### ISSUE THREAD

**Issue by MaroedesJunior** [LizardByte/Sunshine#429] opened 2022-10-24 00:39 UTC
### Describe the Bug

Not working, i did all it say in docs and in web localhost.

Patched the driver too and patched NvFBC.

It stop on "Error: No IGD device found", i cannot connect with client and i can access the web localhost.

### Host Operating System

Linux

### Operating System Version

6.0.2-artix1-1.1 + KDE Plasma

### Architecture

64 bit

### Sunshine Version

latest

### GPU Type

Nvidia

### GPU Model

GTX 1060 3GB

### GPU Driver/Mesa Version

520.56.06

### Capture Method (Linux Only)

X11 and with VGA to HDMI cable

### Relevant log output

```Shell
[file_apps] -- [apps.json]
[pkey] -- [~/.config/sunshine/credentials/cakey.pem]
[cert] -- [~/.config/sunshine/credentials/cacert.pem]
[audio_sink] -- [alsa_output.pci-0000_00_1b.0.analog-stereo]
[amd_quality] -- [default]
[origin_web_ui_allowed] -- [lan]
[vt_software] -- [auto]
[amd_coder] -- [auto]
[upnp] -- [enabled]
[nv_preset] -- [hp]
[sunshine_name] -- [MaroedesJrArtix]
[fps] -- [[10,30,60]]
[file_state] -- [sunshine_state.json]
[vt_coder] -- [auto]
[amd_rc] -- [auto]
[output_name] -- [0: +*HDMI-0 1600/443x900/249+0+0  HDMI-0]
[min_log_level] -- [2]
[vt_realtime] -- [enabled]
[key_rightalt_to_key_win] -- [disabled]
[origin_pin_allowed] -- [pc]
[resolutions] -- [[
    352x240,
    480x360,
    858x480,
    1280x720,
    1600x900    
]]
[nv_coder] -- [auto]
[gamepad] -- [x360]
[dwmflush] -- [enabled]
[hevc_mode] -- [0]
[nv_rc] -- [auto]
[2022:10:23:21:20:19]: Info: Found [1] outputs
[2022:10:23:21:20:19]: Info: Virtual Desktop: 1600x900
[2022:10:23:21:20:19]: Info: XrandR: available
[2022:10:23:21:20:19]: Info: -- Output --
[2022:10:23:21:20:19]: Info:   Resolution: 1600x900
[2022:10:23:21:20:19]: Info:   Offset: 0x0
[2022:10:23:21:20:19]: Error: Couldn't destroy session handle: Unable to cleanup NvFBC
[2022:10:23:21:20:19]: Error: Couldn't expose some/all drm planes for card: /dev/dri/card0
[2022:10:23:21:20:19]: Info: Detecting connected monitors
[2022:10:23:21:20:19]: Info: //////////////////////////////////////////////////////////////////
[2022:10:23:21:20:19]: Info: //                                                              //
[2022:10:23:21:20:19]: Info: //   Testing for available encoders, this may generate errors.  //
[2022:10:23:21:20:19]: Info: //   You can safely ignore those errors.                        //
[2022:10:23:21:20:19]: Info: //                                                              //
[2022:10:23:21:20:19]: Info: //////////////////////////////////////////////////////////////////
[2022:10:23:21:20:19]: Info: Trying encoder [nvenc]
[2022:10:23:21:20:19]: Info: Screencasting with NvFBC
[2022:10:23:21:20:19]: Warning: Can't stream monitor [8976218314314101038], it needs to be between [0] and [0], defaulting to virtual desktop
[2022:10:23:21:20:19]: Info: Color coding [Rec. 601]
[2022:10:23:21:20:19]: Info: Color range: [JPEG]
[2022:10:23:21:20:19]: Error: Could not open codec [h264_nvenc]: Function not implemented
[2022:10:23:21:20:19]: Error: Couldn't destroy session handle: The context is not bound
[2022:10:23:21:20:19]: Info: Screencasting with NvFBC
[2022:10:23:21:20:19]: Warning: Can't stream monitor [8976218314314101038], it needs to be between [0] and [0], defaulting to virtual desktop
[2022:10:23:21:20:19]: Info: Color coding [Rec. 601]
[2022:10:23:21:20:19]: Info: Color range: [JPEG]
[2022:10:23:21:20:19]: Error: Couldn't destroy session handle: The context is not bound
[2022:10:23:21:20:19]: Info: Screencasting with NvFBC
[2022:10:23:21:20:19]: Warning: Can't stream monitor [8976218314314101038], it needs to be between [0] and [0], defaulting to virtual desktop
[2022:10:23:21:20:19]: Info: Color coding [Rec. 601]
[2022:10:23:21:20:19]: Info: Color range: [JPEG]
[2022:10:23:21:20:19]: Error: Couldn't destroy session handle: The context is not bound
[2022:10:23:21:20:19]: Info: Screencasting with NvFBC
[2022:10:23:21:20:19]: Warning: Can't stream monitor [8976218314314101038], it needs to be between [0] and [0], defaulting to virtual desktop
[2022:10:23:21:20:19]: Info: Color coding [Rec. 601]
[2022:10:23:21:20:19]: Info: Color range: [JPEG]
[2022:10:23:21:20:19]: Error: Could not open codec [hevc_nvenc]: Function not implemented
[2022:10:23:21:20:19]: Error: Couldn't destroy session handle: The context is not bound
[2022:10:23:21:20:19]: Info: Screencasting with NvFBC
[2022:10:23:21:20:19]: Warning: Can't stream monitor [8976218314314101038], it needs to be between [0] and [0], defaulting to virtual desktop
[2022:10:23:21:20:19]: Info: Color coding [Rec. 601]
[2022:10:23:21:20:19]: Info: Color range: [JPEG]
[2022:10:23:21:20:19]: Error: Couldn't destroy session handle: The context is not bound
[2022:10:23:21:20:19]: Info: Screencasting with NvFBC
[2022:10:23:21:20:19]: Warning: Can't stream monitor [8976218314314101038], it needs to be between [0] and [0], defaulting to virtual desktop
[2022:10:23:21:20:19]: Info: Color coding [Rec. 709]
[2022:10:23:21:20:19]: Info: Color range: [JPEG]
[2022:10:23:21:20:19]: Error: Could not open codec [h264_nvenc]: Function not implemented
[2022:10:23:21:20:19]: Error: Couldn't destroy session handle: The context is not bound
[2022:10:23:21:20:19]: Info: Screencasting with NvFBC
[2022:10:23:21:20:19]: Warning: Can't stream monitor [8976218314314101038], it needs to be between [0] and [0], defaulting to virtual desktop
[2022:10:23:21:20:19]: Info: Color coding [Rec. 709]
[2022:10:23:21:20:19]: Info: Color range: [JPEG]
[2022:10:23:21:20:19]: Error: cuda::cuda_t doesn't support any format other than AV_PIX_FMT_NV12
[2022:10:23:21:20:20]: Error: Couldn't destroy session handle: The context is not bound
[2022:10:23:21:20:20]: Info: Screencasting with NvFBC
[2022:10:23:21:20:20]: Warning: Can't stream monitor [8976218314314101038], it needs to be between [0] and [0], defaulting to virtual desktop
[2022:10:23:21:20:20]: Info: Color coding [Rec. 601]
[2022:10:23:21:20:20]: Info: Color range: [JPEG]
[2022:10:23:21:20:20]: Error: Couldn't destroy session handle: The context is not bound
[2022:10:23:21:20:20]: Info: Screencasting with NvFBC
[2022:10:23:21:20:20]: Warning: Can't stream monitor [8976218314314101038], it needs to be between [0] and [0], defaulting to virtual desktop
[2022:10:23:21:20:20]: Info: Color coding [Rec. 601]
[2022:10:23:21:20:20]: Info: Color range: [JPEG]
[2022:10:23:21:20:20]: Warning: nvenc: hevc: replacing nalu prefix data
[2022:10:23:21:20:20]: Error: Couldn't destroy session handle: The context is not bound
[2022:10:23:21:20:20]: Info: 
[2022:10:23:21:20:20]: Info: //////////////////////////////////////////////////////////////
[2022:10:23:21:20:20]: Info: //                                                          //
[2022:10:23:21:20:20]: Info: // Ignore any errors mentioned above, they are not relevant //
[2022:10:23:21:20:20]: Info: //                                                          //
[2022:10:23:21:20:20]: Info: //////////////////////////////////////////////////////////////
[2022:10:23:21:20:20]: Info: 
[2022:10:23:21:20:20]: Info: Found encoder nvenc: [h264_nvenc, hevc_nvenc]
[2022:10:23:21:20:20]: Info: Configuration UI available at [https://localhost:47990]
[2022:10:23:21:20:20]: Info: Adding avahi service Sunshine
[2022:10:23:21:20:21]: Info: Avahi service Sunshine successfully established.
connect: Connection refused
[2022:10:23:21:20:22]: Error: No IGD device found
```

**Comment by ReenigneArcher** [comment] 2022-10-24 00:54
Disable UPNP in sunshine config

**Comment by MaroedesJunior** [comment] 2022-10-24 00:58
> Disable UPNP in sunshine config

same problem after i disable this!

**Comment by ReenigneArcher** [comment] 2022-10-24 01:10
IGD is internet gateway device. I'd check your firewall rules. Anyway, this is not a bug report so closing this.

**Closed** 2022-10-24 01:11 UTC
Labels: invalid:support
