### ISSUE TITLE
intel HD4600  Quicksync Encoder not found

### ISSUE THREAD

**Issue by lzkk4** [LizardByte/Sunshine#917] opened 2023-02-12 09:14 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I try sunshine on my i7-4790k pc with igpu hd4600,it seem that it's in Minimum Requirements list with Intel-VAAPI-compatible,however ,the hardware encoding seem to not work at all.

so anyone using 4th or older intel igpu can make hardware encoding effective? this gpu  can use hardware coding in parsec but not in steamlink,but the sunshine is my favor ,hope to make it effective.thanks very much

### Host Operating System

Windows

### Operating System Version

win11 pro 1000.22000.556.0

### Architecture

64 bit

### Sunshine commit or version

v0.18.1

### Package

Windows - installer

### GPU Type

Intel

### GPU Model

hd4600

### GPU Driver/Mesa Version

15.40.5171，newest

### Relevant log output

```Shell
[2023:02:12:16:13:02]: Info: Compiling shaders...
[2023:02:12:16:13:02]: Info: Compiled shaders
[2023:02:12:16:13:02]: Warning: Couldn't setup connection to ViGEm for gamepad support [E0000001]
[2023:02:12:16:13:02]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:02:12:16:13:02]: Info: Trying encoder [nvenc]
[2023:02:12:16:13:03]: Info: ddprobe.exe [1] [] returned: 0x00000000
[2023:02:12:16:13:03]: Info: Set GPU preference: 1
[2023:02:12:16:13:03]: Info: 
Device Description : Intel(R) HD Graphics 4600
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00000412
Device Video Mem   : 112 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 2048 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1440
Offset             : 0x0
Virtual Desktop    : 2560x1440
[2023:02:12:16:13:03]: Info: Desktop resolution [2560x1440]
[2023:02:12:16:13:03]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:16:13:03]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.65625,0.328125]
Green Primary      : [0.264648,0.588867]
Blue Primary       : [0.132812,0.103516]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:16:13:03]: Info: SDR color coding [Rec. 601]
[2023:02:12:16:13:03]: Info: Color range: [JPEG]
[2023:02:12:16:13:03]: Error: Could not open codec [h264_nvenc]: No such file or directory
[2023:02:12:16:13:03]: Info: 
Device Description : Intel(R) HD Graphics 4600
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00000412
Device Video Mem   : 112 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 2048 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1440
Offset             : 0x0
Virtual Desktop    : 2560x1440
[2023:02:12:16:13:03]: Info: Desktop resolution [2560x1440]
[2023:02:12:16:13:03]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:16:13:03]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.65625,0.328125]
Green Primary      : [0.264648,0.588867]
Blue Primary       : [0.132812,0.103516]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:16:13:03]: Info: SDR color coding [Rec. 601]
[2023:02:12:16:13:03]: Info: Color range: [JPEG]
[2023:02:12:16:13:03]: Error: Could not open codec [h264_nvenc]: No such file or directory
[2023:02:12:16:13:03]: Info: 
Device Description : Intel(R) HD Graphics 4600
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00000412
Device Video Mem   : 112 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 2048 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1440
Offset             : 0x0
Virtual Desktop    : 2560x1440
[2023:02:12:16:13:03]: Info: Desktop resolution [2560x1440]
[2023:02:12:16:13:03]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:16:13:03]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.65625,0.328125]
Green Primary      : [0.264648,0.588867]
Blue Primary       : [0.132812,0.103516]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:16:13:03]: Info: SDR color coding [Rec. 601]
[2023:02:12:16:13:03]: Info: Color range: [JPEG]
[2023:02:12:16:13:03]: Error: Could not open codec [h264_nvenc]: No such file or directory
[2023:02:12:16:13:03]: Info: 
Device Description : Intel(R) HD Graphics 4600
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00000412
Device Video Mem   : 112 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 2048 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1440
Offset             : 0x0
Virtual Desktop    : 2560x1440
[2023:02:12:16:13:03]: Info: Desktop resolution [2560x1440]
[2023:02:12:16:13:03]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:16:13:03]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.65625,0.328125]
Green Primary      : [0.264648,0.588867]
Blue Primary       : [0.132812,0.103516]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:16:13:03]: Info: SDR color coding [Rec. 601]
[2023:02:12:16:13:03]: Info: Color range: [JPEG]
[2023:02:12:16:13:03]: Error: Could not open codec [h264_nvenc]: No such file or directory
[2023:02:12:16:13:03]: Info: Encoder [nvenc] failed
[2023:02:12:16:13:03]: Info: Trying encoder [quicksync]
[2023:02:12:16:13:03]: Info: 
Device Description : Intel(R) HD Graphics 4600
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00000412
Device Video Mem   : 112 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 2048 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1440
Offset             : 0x0
Virtual Desktop    : 2560x1440
[2023:02:12:16:13:03]: Info: Desktop resolution [2560x1440]
[2023:02:12:16:13:03]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:16:13:03]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.65625,0.328125]
Green Primary      : [0.264648,0.588867]
Blue Primary       : [0.132812,0.103516]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:16:13:03]: Info: SDR color coding [Rec. 601]
[2023:02:12:16:13:03]: Info: Color range: [JPEG]
[2023:02:12:16:13:03]: Error: Could not open codec [h264_qsv]: Function not implemented
[2023:02:12:16:13:03]: Info: 
Device Description : Intel(R) HD Graphics 4600
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00000412
Device Video Mem   : 112 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 2048 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1440
Offset             : 0x0
Virtual Desktop    : 2560x1440
[2023:02:12:16:13:03]: Info: Desktop resolution [2560x1440]
[2023:02:12:16:13:03]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:16:13:03]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.65625,0.328125]
Green Primary      : [0.264648,0.588867]
Blue Primary       : [0.132812,0.103516]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:16:13:03]: Info: SDR color coding [Rec. 601]
[2023:02:12:16:13:03]: Info: Color range: [JPEG]
[2023:02:12:16:13:03]: Error: Could not open codec [h264_qsv]: Function not implemented
[2023:02:12:16:13:03]: Info: 
Device Description : Intel(R) HD Graphics 4600
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00000412
Device Video Mem   : 112 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 2048 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1440
Offset             : 0x0
Virtual Desktop    : 2560x1440
[2023:02:12:16:13:03]: Info: Desktop resolution [2560x1440]
[2023:02:12:16:13:03]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:16:13:03]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.65625,0.328125]
Green Primary      : [0.264648,0.588867]
Blue Primary       : [0.132812,0.103516]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:16:13:03]: Info: SDR color coding [Rec. 601]
[2023:02:12:16:13:03]: Info: Color range: [JPEG]
[2023:02:12:16:13:03]: Error: Could not open codec [h264_qsv]: Function not implemented
[2023:02:12:16:13:03]: Info: 
Device Description : Intel(R) HD Graphics 4600
Device Vendor ID   : 0x00008086
Device Device ID   : 0x00000412
Device Video Mem   : 112 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 2048 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1440
Offset             : 0x0
Virtual Desktop    : 2560x1440
[2023:02:12:16:13:03]: Info: Desktop resolution [2560x1440]
[2023:02:12:16:13:03]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:02:12:16:13:03]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.65625,0.328125]
Green Primary      : [0.264648,0.588867]
Blue Primary       : [0.132812,0.103516]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:02:12:16:13:03]: Info: SDR color coding [Rec. 601]
[2023:02:12:16:13:03]: Info: Color range: [JPEG]
[2023:02:12:16:13:03]: Error: Could not open codec [h264_qsv]: Function not implemented
[2023:02:12:16:13:03]: Info: Encoder [quicksync] failed
```

**Comment by ReenigneArcher** [comment] 2023-02-12 15:25
Duplicate of #904

**Closed** 2023-02-12 15:26 UTC
Labels: invalid:duplicate
