### ISSUE TITLE
Can't run Sunshine on macOS: No launchable application in Launchpad, and cannot be run in Terminal

### ISSUE THREAD

**Issue by JosephM101** [LizardByte/Sunshine#606] opened 2022-12-22 13:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I'll preface this by saying I'm running macOS Monterey (12.6.1).

So I've downloaded the `sunshine.dmg` file from the latest release, and I installed the `pkg` file. The installation succeeded, but I didn't find an application entry in either the `Applications` folder, or the Launchpad.
I tried launching it using Terminal, but there doesn't seem to be a `sunshine` command.

I've gone through all of the documentation, but there doesn't seem to be an obvious way to run the server on macOS. Maybe I'm missing something?

### Expected Behavior

I would expect Sunshine to appear as an app in the Launchpad, and when running, I would expect to see an icon in the app bar that indicated such.

### Host Operating System

macOS

### Operating System Version

12.6.1

### Architecture

64 bit

### Sunshine commit or version

0.16.0

### Package

macOS - dmg

### GPU Type

Nvidia

### GPU Model

NVIDIA GeForce GT 640M 512 MB

### GPU Driver/Mesa Version

Unknown

**Comment by brad-richardson** [comment] 2022-12-22 13:33
Sunshine has no GUI (other than a light web app) and we don't start it in the background for macOS. The install package you used is experimental, I would try using the macports install instead - https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/installation.html#portfile

**Comment by ReenigneArcher** [comment] 2022-12-22 13:42
Duplicate of #186

**Closed by ReenigneArcher** 2022-12-22 13:42 UTC
Labels: invalid:duplicate
