### ISSUE TITLE
Applications not started as normal user

### ISSUE THREAD

**Issue by BumblingCoder** [LizardByte/Sunshine#546] opened 2022-12-12 22:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Describe the Bug

Applications seem to be started as a different (possibly admin) user rather than as the normal user account. The easiest way to notice this is to launch Playnite, which complains that it is being launched with elevated privileges every time it is launched.

### Expected Behavior

The applications are launched as the normal user with no additional privileges.

### Additional Context

I was able to work around this by changing the service to run as my normal user. It looks like the service is launching sub processes as the system user rather than correctly dropping the permissions to whatever the actual user is.

### Host Operating System

Windows

### Operating System Version

10

### Architecture

64 bit

### Sunshine commit or version

0.15.0

### Package

Windows - installer

### GPU Type

AMD

### GPU Model

Any

### GPU Driver/Mesa Version

Any

**Comment by ReenigneArcher** [comment] 2022-12-14 17:27
On Windows, running sunshine as the service will run sunshine under `SYSTEM` account. As you have found, this causes issues with many other applications which are launched under the same user as sunshine.

There are some ideas for potential fixes; however the code will need to be split into Windows compatible and POSIX compatible as there are different APIs required to achieve this result.

**Comment by jmyoung** [comment] 2022-12-17 04:52
+1

This is exactly the issue I had when trying Sunshine.  I use Playnite as my game launcher, and applications launched via Sunshine run as the SYSTEM user and also elevated.  This isn't ideal and breaks Playnite and other apps which expect to be running in the context of the currently logged in user.  This would appear to be because sunshinesvc runs as SYSTEM and likely doesn't do any impersonation.

As a result I can't use Sunshine.

**Comment by brad-richardson** [comment] 2022-12-17 05:45
@jmyoung Could you try changing the service to run as your user? Services -> sunshinesvc -> right click -> properties -> log on

We need to look for a better solution but I’m wondering if that could be a workaround for now?

**Comment by BumblingCoder** [comment] 2022-12-17 12:46
It looks like not running the installer and instead running the portable version is also an easy workaround, as it doesn't seem to register the service in this mode.

**Comment by ReenigneArcher** [comment] 2022-12-17 12:53
You register the service, or not, during installation. Best to read through the installation steps, instead of just advancing automatically.

You can also enable/disable the service manually, but it's not really documented right now.

Anyway this is the normal behavior. Applications will run as the same user that is running sunshine. If running as a service, that will be SYSTEM by default. This is what enabled you to see UAC prompts as well as the lock screen.

While we need a way to run applications as another user, I will close this as it's not a bug. I will accept a PR that adds this ability though, assuming the code is multiplatform.

**Closed** 2022-12-17 12:53 UTC

**Comment by BumblingCoder** [comment] 2022-12-17 18:11
Both during install and in the documentation it isn't made particularly clear that the service is optional or how it works. At least having some documentation about using the service vs just running the executable would go a long way to clearing this up. Related: is it necessary to run the executable if the service is running? The documentation makes no mention of the service, so exactly what it does and doesn't do is really unclear.

**Comment by ReenigneArcher** [comment] 2022-12-17 18:16
In computer terminology, a "service" is typically something that runs in the background (i.e. automatically).

So if you're running the service, it would not be wise to also execute sunshine yourself.

**Comment by Justify87** [comment] 2022-12-18 08:38
Not running under user context also breaks a lot of games trying to launch. Graphics settings get scrambled. Some games don't even launch, like God of War. Afaik the required behaviour (running under user context in the background) can't be achieved in windows when registering as a service. Interacting with the user session is forbidden by design, or at least it's very restricted. So there will be no workaround. I'd advice to remove this feature for windows completely until somone fixes it. For now this will do the trick:

Start-Process -WindowStyle hidden -FilePath .\sunhine.exe

Start a powershell prompt from inside the installation folder of sunshine. For this to work. If you want it to start automatically on startup, you'd have to put it in autostart/startup folder as a powershell script. Be aware, that some apps wont close themsleves as easily as before. Playnite wouldn't close when ending the session in moonlight. Had to close the program the usual way to have it end the streaming session. Afaik nvidia geforce experience sometimes also had this problem.

**Comment by Justify87** [comment] 2022-12-18 09:47
Got it to Work. Scheduled Task and Powershell Script. For Anyone interested. You will see a cmd window 30seconds after startup in the taskbar for half a second. Other than that it works as expected.
[Sunshine_Service.zip](https://github.com/LizardByte/Sunshine/files/10253543/Sunshine_Service.zip)

**Comment by cgutman** [comment] 2023-01-01 19:11
This was fixed by #600
