### ISSUE TITLE
Struggling to get Docker start up

### ISSUE THREAD

**Issue by HarryAnkers** [LizardByte/Sunshine#2050] opened 2024-01-20 17:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I'm guessing I am doing something incorrectly with the users of setting this up with docker. But when running docker compose I'm getting the follow error logs below.

I am trying do this with this docker compose:

```
version: '3'
name: "sunshine"
services:
  sunshine:
    image: lizardbyte/sunshine:nightly-ubuntu-22.04
    container_name: sunshine
    restart: unless-stopped
    volumes:
      - /home/harryankers/Services/Sunshine/config:/config
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    ports:
      - "47984-47990:47984-47990/tcp"
      - "48010:48010"
      - "47998-48000:47998-48000/udp"
```

I am running this with docker desktop so I wasn't sure if the puid and pgid mapping of that was messing this up.

### Expected Behavior

Expect the image to run

### Additional Context

No, got it to work with the AppImage but cant with docker.

### Host Operating System

Docker

### Operating System Version

Pop!_OS 22.04 LTS

### Architecture

64 bit

### Sunshine commit or version

e7e584d23041

### Package

Linux - Docker

### GPU Type

Nvidia

### GPU Model

3060 ti founders

### GPU Driver/Mesa Version

545.29.06

### Config

```Shell
av1_mode = 1
key_rightalt_to_key_win = enabled
```

### Relevant log output

```shell
sunshine exited with code 0
sunshine  | 2024-01-20T17:49:48.526192621Z [2024-01-20 17:49:48.526071] [0x00007f135db45000] [info]    Failed to apply config: filesystem error: cannot copy file: Permission denied [/usr/share/sunshine/apps.json] [/home/lizard/.config/sunshine/apps.json]
2024-01-20 17:49:48 sunshine  | [2024-01-20 17:49:48.849862] [0x00007efc784e3000] [info]    Failed to apply config: filesystem error: cannot copy file: Permission denied [/usr/share/sunshine/apps.json] [/home/lizard/.config/sunshine/apps.json]
```

**Comment by jonfairbanks** [comment] 2024-01-26 07:55
Same issue when using PUID/PGID of `1000` which matches the output of `id` on my local system.

**Comment by ReenigneArcher** [comment] 2024-01-26 18:11
You're missing an important part of using Sunshine in Docker. https://docs.lizardbyte.dev/projects/sunshine/en/latest/about/docker.html#build-your-own-containers

If you're expecting to just use the Sunshine images, as is, it's not going to work. There's no display, there's no DE, no input, etc.

PRs welcome to improve Docker documentation and/or usability, but otherwise I will be closing this issue as it's not a bug.

**Closed by ReenigneArcher** 2024-01-26 18:11 UTC

**Comment by RandomLegend** [comment] 2024-01-28 13:33
@ReenigneArcher 

i just stumbled into this thread because i have the same issue.

As far as i can see we also cannot simply copy & paste the dockerfile from the repo to build our images. We have to configure the dockerfile aswell.

Are there any plans to provide some form of pre-configured easy entry? Like a pre configured dockerfile with installation steps for steam in them already?

As of right now i don't see how i could get this to run via docker since i have no idea on how to properly configure and write dockerfiles. My only experience is writing docker-compose and this doesn't work if i understand you correct.

**Comment by ReenigneArcher** [comment] 2024-01-28 14:08
> Are there any plans to provide some form of pre-configured easy entry? Like a pre configured dockerfile with installation steps for steam in them already?

See Games on Whales.
