### ISSUE TITLE
Rejected Connect, it's not properly set up - FAILURE TO CONNECT OVER THE INTERNET BUT WORKS OVER LAN

### ISSUE THREAD

**Issue by Lenovive** [LizardByte/Sunshine#1862] opened 2023-11-23 02:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Over LAN, moonlight & sunshine work great. I switch to cellular, and one day it just stopped working. It can detect the stream over cellular from my phone, but when I attempt to join, I get a Rejected connection error. 

### Expected Behavior

IT should connect.

### Additional Context

Disabling firewall, full windows reset, reseting router.... No fixes yet. 

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

.21

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 4090

### GPU Driver/Mesa Version

545.92

### Config

```Shell
-
```

### Apps

```json
-
```

### Relevant log output

```shell
[2023:11:22:19:47:32]: Info: nvprefs: No need to modify application profile settings
[2023:11:22:19:47:32]: Info: nvprefs: Changed OGL_CPL_PREFER_DXPRESENT to OGL_CPL_PREFER_DXPRESENT_PREFER_ENABLED for base profile
[2023:11:22:19:47:32]: Info: Sunshine version: 0.21.0
[2023:11:22:19:47:32]: Info: Compiling shaders...
[2023:11:22:19:47:32]: Info: System tray created
[2023:11:22:19:47:32]: Info: Compiled shaders
[2023:11:22:19:47:32]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:11:22:19:47:32]: Info: Trying encoder [nvenc]
[2023:11:22:19:47:32]: Info: ddprobe.exe [1] [] returned: 0x00000000
[2023:11:22:19:47:32]: Info: Set GPU preference: 1
[2023:11:22:19:47:33]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24156 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 15947 MiB
Feature Level      : 0x0000B100
Capture size       : 2796x1290
Offset             : 0x0
Virtual Desktop    : 2796x1290
[2023:11:22:19:47:33]: Info: Active GPU has HAGS enabled
[2023:11:22:19:47:33]: Info: Using realtime GPU priority
[2023:11:22:19:47:33]: Info: Desktop resolution [2796x1290]
[2023:11:22:19:47:33]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:11:22:19:47:33]: Info: Display refresh rate [120Hz]
[2023:11:22:19:47:33]: Info: Requested frame rate [60fps]
[2023:11:22:19:47:33]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 12
Red Primary        : [0.690427,0.304689]
Green Primary      : [0.240233,0.715818]
Blue Primary       : [0.146488,0.0566368]
White Point        : [0.3125,0.329098]
Min Luminance      : 0.01 nits
Max Luminance      : 1000 nits
Max Full Luminance : 1000 nits
[2023:11:22:19:47:34]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24156 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 15947 MiB
Feature Level      : 0x0000B100
Capture size       : 2796x1290
Offset             : 0x0
Virtual Desktop    : 2796x1290
[2023:11:22:19:47:34]: Info: Active GPU has HAGS enabled
[2023:11:22:19:47:34]: Info: Using realtime GPU priority
[2023:11:22:19:47:34]: Info: Desktop resolution [2796x1290]
[2023:11:22:19:47:34]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:11:22:19:47:34]: Info: Display refresh rate [120Hz]
[2023:11:22:19:47:34]: Info: Requested frame rate [60fps]
[2023:11:22:19:47:34]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 12
Red Primary        : [0.690427,0.304689]
Green Primary      : [0.240233,0.715818]
Blue Primary       : [0.146488,0.0566368]
White Point        : [0.3125,0.329098]
Min Luminance      : 0.01 nits
Max Luminance      : 1000 nits
Max Full Luminance : 1000 nits
[2023:11:22:19:47:34]: Info: SDR color coding [Rec. 601]
[2023:11:22:19:47:34]: Info: Color depth: 8-bit
[2023:11:22:19:47:34]: Info: Color range: [JPEG]
[2023:11:22:19:47:34]: Info: NvEnc: created encoder P1 two-pass rfi
[2023:11:22:19:47:35]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24156 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 15947 MiB
Feature Level      : 0x0000B100
Capture size       : 2796x1290
Offset             : 0x0
Virtual Desktop    : 2796x1290
[2023:11:22:19:47:35]: Info: Active GPU has HAGS enabled
[2023:11:22:19:47:35]: Info: Using realtime GPU priority
[2023:11:22:19:47:35]: Info: Desktop resolution [2796x1290]
[2023:11:22:19:47:35]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:11:22:19:47:35]: Info: Display refresh rate [120Hz]
[2023:11:22:19:47:35]: Info: Requested frame rate [60fps]
[2023:11:22:19:47:35]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 12
Red Primary        : [0.690427,0.304689]
Green Primary      : [0.240233,0.715818]
Blue Primary       : [0.146488,0.0566368]
White Point        : [0.3125,0.329098]
Min Luminance      : 0.01 nits
Max Luminance      : 1000 nits
Max Full Luminance : 1000 nits
[2023:11:22:19:47:35]: Info: SDR color coding [Rec. 601]
[2023:11:22:19:47:35]: Info: Color depth: 8-bit
[2023:11:22:19:47:35]: Info: Color range: [JPEG]
[2023:11:22:19:47:35]: Info: NvEnc: created encoder P1 two-pass rfi
[2023:11:22:19:47:36]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24156 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 15947 MiB
Feature Level      : 0x0000B100
Capture size       : 2796x1290
Offset             : 0x0
Virtual Desktop    : 2796x1290
[2023:11:22:19:47:36]: Info: Active GPU has HAGS enabled
[2023:11:22:19:47:36]: Info: Using realtime GPU priority
[2023:11:22:19:47:36]: Info: Desktop resolution [2796x1290]
[2023:11:22:19:47:36]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:11:22:19:47:36]: Info: Display refresh rate [120Hz]
[2023:11:22:19:47:36]: Info: Requested frame rate [60fps]
[2023:11:22:19:47:36]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 12
Red Primary        : [0.690427,0.304689]
Green Primary      : [0.240233,0.715818]
Blue Primary       : [0.146488,0.0566368]
White Point        : [0.3125,0.329098]
Min Luminance      : 0.01 nits
Max Luminance      : 1000 nits
Max Full Luminance : 1000 nits
[2023:11:22:19:47:36]: Info: SDR color coding [Rec. 601]
[2023:11:22:19:47:36]: Info: Color depth: 8-bit
[2023:11:22:19:47:36]: Info: Color range: [JPEG]
[2023:11:22:19:47:36]: Info: NvEnc: created encoder P1 two-pass rfi
[2023:11:22:19:47:37]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24156 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 15947 MiB
Feature Level      : 0x0000B100
Capture size       : 2796x1290
Offset             : 0x0
Virtual Desktop    : 2796x1290
[2023:11:22:19:47:37]: Info: Active GPU has HAGS enabled
[2023:11:22:19:47:37]: Info: Using realtime GPU priority
[2023:11:22:19:47:37]: Info: Desktop resolution [2796x1290]
[2023:11:22:19:47:37]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:11:22:19:47:37]: Info: Display refresh rate [120Hz]
[2023:11:22:19:47:37]: Info: Requested frame rate [60fps]
[2023:11:22:19:47:37]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 12
Red Primary        : [0.690427,0.304689]
Green Primary      : [0.240233,0.715818]
Blue Primary       : [0.146488,0.0566368]
White Point        : [0.3125,0.329098]
Min Luminance      : 0.01 nits
Max Luminance      : 1000 nits
Max Full Luminance : 1000 nits
[2023:11:22:19:47:37]: Info: HDR color coding [Rec. 2020 + SMPTE 2084 PQ]
[2023:11:22:19:47:37]: Info: Color depth: 10-bit
[2023:11:22:19:47:37]: Info: Color range: [JPEG]
[2023:11:22:19:47:37]: Info: NvEnc: created encoder P1 10-bit two-pass rfi
[2023:11:22:19:47:37]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24156 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 15947 MiB
Feature Level      : 0x0000B100
Capture size       : 2796x1290
Offset             : 0x0
Virtual Desktop    : 2796x1290
[2023:11:22:19:47:37]: Info: Active GPU has HAGS enabled
[2023:11:22:19:47:37]: Info: Using realtime GPU priority
[2023:11:22:19:47:37]: Info: Desktop resolution [2796x1290]
[2023:11:22:19:47:37]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:11:22:19:47:37]: Info: Display refresh rate [120Hz]
[2023:11:22:19:47:37]: Info: Requested frame rate [60fps]
[2023:11:22:19:47:37]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 12
Red Primary        : [0.690427,0.304689]
Green Primary      : [0.240233,0.715818]
Blue Primary       : [0.146488,0.0566368]
White Point        : [0.3125,0.329098]
Min Luminance      : 0.01 nits
Max Luminance      : 1000 nits
Max Full Luminance : 1000 nits
[2023:11:22:19:47:37]: Info: HDR color coding [Rec. 2020 + SMPTE 2084 PQ]
[2023:11:22:19:47:37]: Info: Color depth: 10-bit
[2023:11:22:19:47:37]: Info: Color range: [JPEG]
[2023:11:22:19:47:37]: Info: NvEnc: created encoder P1 10-bit two-pass rfi
[2023:11:22:19:47:37]: Info: 
[2023:11:22:19:47:37]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2023:11:22:19:47:37]: Info: 
[2023:11:22:19:47:37]: Info: Found H.264 encoder: h264_nvenc [nvenc]
[2023:11:22:19:47:37]: Info: Found HEVC encoder: hevc_nvenc [nvenc]
[2023:11:22:19:47:37]: Info: Found AV1 encoder: av1_nvenc [nvenc]
[2023:11:22:19:47:37]: Info: Configuration UI available at [https://localhost:47990]
[2023:11:22:19:47:38]: Info: Registered Sunshine mDNS service
[2023:11:22:19:47:41]: Info: Completed UPnP port mappings to 192.168.0.246 via http://192.168.0.1:1900/kjlfs/rootDesc.xml
[2023:11:22:19:48:13]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:11:22:19:48:13]: Info: Trying encoder [nvenc]
[2023:11:22:19:48:13]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24156 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 15947 MiB
Feature Level      : 0x0000B100
Capture size       : 2796x1290
Offset             : 0x0
Virtual Desktop    : 2796x1290
[2023:11:22:19:48:13]: Info: Active GPU has HAGS enabled
[2023:11:22:19:48:13]: Info: Using realtime GPU priority
[2023:11:22:19:48:13]: Info: Desktop resolution [2796x1290]
[2023:11:22:19:48:13]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:11:22:19:48:13]: Info: Display refresh rate [120Hz]
[2023:11:22:19:48:13]: Info: Requested frame rate [60fps]
[2023:11:22:19:48:13]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 12
Red Primary        : [0.690427,0.304689]
Green Primary      : [0.240233,0.715818]
Blue Primary       : [0.146488,0.0566368]
White Point        : [0.3125,0.329098]
Min Luminance      : 0.01 nits
Max Luminance      : 1000 nits
Max Full Luminance : 1000 nits
[2023:11:22:19:48:15]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24156 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 15947 MiB
Feature Level      : 0x0000B100
Capture size       : 2796x1290
Offset             : 0x0
Virtual Desktop    : 2796x1290
[2023:11:22:19:48:15]: Info: Active GPU has HAGS enabled
[2023:11:22:19:48:15]: Info: Using realtime GPU priority
[2023:11:22:19:48:15]: Info: Desktop resolution [2796x1290]
[2023:11:22:19:48:15]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:11:22:19:48:15]: Info: Display refresh rate [120Hz]
[2023:11:22:19:48:15]: Info: Requested frame rate [60fps]
[2023:11:22:19:48:15]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 12
Red Primary        : [0.690427,0.304689]
Green Primary      : [0.240233,0.715818]
Blue Primary       : [0.146488,0.0566368]
White Point        : [0.3125,0.329098]
Min Luminance      : 0.01 nits
Max Luminance      : 1000 nits
Max Full Luminance : 1000 nits
[2023:11:22:19:48:15]: Info: SDR color coding [Rec. 601]
[2023:11:22:19:48:15]: Info: Color depth: 8-bit
[2023:11:22:19:48:15]: Info: Color range: [JPEG]
[2023:11:22:19:48:15]: Info: NvEnc: created encoder P1 two-pass rfi
[2023:11:22:19:48:15]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24156 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 15947 MiB
Feature Level      : 0x0000B100
Capture size       : 2796x1290
Offset             : 0x0
Virtual Desktop    : 2796x1290
[2023:11:22:19:48:15]: Info: Active GPU has HAGS enabled
[2023:11:22:19:48:15]: Info: Using realtime GPU priority
[2023:11:22:19:48:15]: Info: Desktop resolution [2796x1290]
[2023:11:22:19:48:15]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:11:22:19:48:15]: Info: Display refresh rate [120Hz]
[2023:11:22:19:48:15]: Info: Requested frame rate [60fps]
[2023:11:22:19:48:15]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 12
Red Primary        : [0.690427,0.304689]
Green Primary      : [0.240233,0.715818]
Blue Primary       : [0.146488,0.0566368]
White Point        : [0.3125,0.329098]
Min Luminance      : 0.01 nits
Max Luminance      : 1000 nits
Max Full Luminance : 1000 nits
[2023:11:22:19:48:15]: Info: SDR color coding [Rec. 601]
[2023:11:22:19:48:15]: Info: Color depth: 8-bit
[2023:11:22:19:48:15]: Info: Color range: [JPEG]
[2023:11:22:19:48:15]: Info: NvEnc: created encoder P1 two-pass rfi
[2023:11:22:19:48:16]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24156 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 15947 MiB
Feature Level      : 0x0000B100
Capture size       : 2796x1290
Offset             : 0x0
Virtual Desktop    : 2796x1290
[2023:11:22:19:48:16]: Info: Active GPU has HAGS enabled
[2023:11:22:19:48:16]: Info: Using realtime GPU priority
[2023:11:22:19:48:16]: Info: Desktop resolution [2796x1290]
[2023:11:22:19:48:16]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:11:22:19:48:16]: Info: Display refresh rate [120Hz]
[2023:11:22:19:48:16]: Info: Requested frame rate [60fps]
[2023:11:22:19:48:16]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 12
Red Primary        : [0.690427,0.304689]
Green Primary      : [0.240233,0.715818]
Blue Primary       : [0.146488,0.0566368]
White Point        : [0.3125,0.329098]
Min Luminance      : 0.01 nits
Max Luminance      : 1000 nits
Max Full Luminance : 1000 nits
[2023:11:22:19:48:16]: Info: SDR color coding [Rec. 601]
[2023:11:22:19:48:16]: Info: Color depth: 8-bit
[2023:11:22:19:48:16]: Info: Color range: [JPEG]
[2023:11:22:19:48:16]: Info: NvEnc: created encoder P1 two-pass rfi
[2023:11:22:19:48:17]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24156 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 15947 MiB
Feature Level      : 0x0000B100
Capture size       : 2796x1290
Offset             : 0x0
Virtual Desktop    : 2796x1290
[2023:11:22:19:48:17]: Info: Active GPU has HAGS enabled
[2023:11:22:19:48:17]: Info: Using realtime GPU priority
[2023:11:22:19:48:17]: Info: Desktop resolution [2796x1290]
[2023:11:22:19:48:17]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:11:22:19:48:17]: Info: Display refresh rate [120Hz]
[2023:11:22:19:48:17]: Info: Requested frame rate [60fps]
[2023:11:22:19:48:17]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 12
Red Primary        : [0.690427,0.304689]
Green Primary      : [0.240233,0.715818]
Blue Primary       : [0.146488,0.0566368]
White Point        : [0.3125,0.329098]
Min Luminance      : 0.01 nits
Max Luminance      : 1000 nits
Max Full Luminance : 1000 nits
[2023:11:22:19:48:17]: Info: HDR color coding [Rec. 2020 + SMPTE 2084 PQ]
[2023:11:22:19:48:17]: Info: Color depth: 10-bit
[2023:11:22:19:48:17]: Info: Color range: [JPEG]
[2023:11:22:19:48:17]: Info: NvEnc: created encoder P1 10-bit two-pass rfi
[2023:11:22:19:48:18]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24156 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 15947 MiB
Feature Level      : 0x0000B100
Capture size       : 2796x1290
Offset             : 0x0
Virtual Desktop    : 2796x1290
[2023:11:22:19:48:18]: Info: Active GPU has HAGS enabled
[2023:11:22:19:48:18]: Info: Using realtime GPU priority
[2023:11:22:19:48:18]: Info: Desktop resolution [2796x1290]
[2023:11:22:19:48:18]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:11:22:19:48:18]: Info: Display refresh rate [120Hz]
[2023:11:22:19:48:18]: Info: Requested frame rate [60fps]
[2023:11:22:19:48:18]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 12
Red Primary        : [0.690427,0.304689]
Green Primary      : [0.240233,0.715818]
Blue Primary       : [0.146488,0.0566368]
White Point        : [0.3125,0.329098]
Min Luminance      : 0.01 nits
Max Luminance      : 1000 nits
Max Full Luminance : 1000 nits
[2023:11:22:19:48:18]: Info: HDR color coding [Rec. 2020 + SMPTE 2084 PQ]
[2023:11:22:19:48:18]: Info: Color depth: 10-bit
[2023:11:22:19:48:18]: Info: Color range: [JPEG]
[2023:11:22:19:48:18]: Info: NvEnc: created encoder P1 10-bit two-pass rfi
[2023:11:22:19:48:18]: Info: 
[2023:11:22:19:48:18]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2023:11:22:19:48:18]: Info: 
[2023:11:22:19:48:18]: Info: Found H.264 encoder: h264_nvenc [nvenc]
[2023:11:22:19:48:18]: Info: Found HEVC encoder: hevc_nvenc [nvenc]
[2023:11:22:19:48:18]: Info: Found AV1 encoder: av1_nvenc [nvenc]
[2023:11:22:19:48:18]: Info: Executing [Desktop]
[2023:11:22:19:48:21]: Info: nvprefs: No need to modify application profile settings
[2023:11:22:19:48:21]: Info: nvprefs: No need to modify global profile settings
[2023:11:22:19:48:21]: Warning: Rejected connection from [172.56.83.58]: it's not properly set up
```

**Comment by ReenigneArcher** [comment] 2023-11-23 03:00
Duplicate of #1804

**Closed by ReenigneArcher** 2023-11-23 03:00 UTC
