### ISSUE TITLE
mouse can't move in VALORANT

### ISSUE THREAD

**Issue by admin1155** [LizardByte/Sunshine#2929] opened 2024-07-29 00:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

mouse can't move in VALORANT
this bug video (https://yxrsss-my.sharepoint.com/:v:/g/personal/xmccln_yxrsss_onmicrosoft_com/EeJJNj6qgeNDhCySDAtwZqsBd_NkuDZUxaXWWq960gnr6w?e=sGXsbr)

### Host Operating System

Windows

### Operating System Version

10

### Architecture

64 bit

### Sunshine commit or version

v0.23.1

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

GT 730

### GPU Driver/Mesa Version

30.0.14.7514

### Capture Method

None

### Config

```Shell
address_family = both
nvenc_twopass = disabled
upnp = enable
locale = zh
```

### Relevant log output

```shell
[2024:07:29:08:00:38]: Info: Sunshine version: v0.23.1
[2024:07:29:08:00:38]: Info: nvprefs: Opened undo file from previous improper termination
[2024:07:29:08:00:38]: Info: nvprefs: Restored OGL_CPL_PREFER_DXPRESENT for base profile
[2024:07:29:08:00:38]: Info: nvprefs: Restored global profile settings from undo file - deleting the file
[2024:07:29:08:00:38]: Info: nvprefs: No need to modify application profile settings
[2024:07:29:08:00:38]: Info: nvprefs: Changed OGL_CPL_PREFER_DXPRESENT to OGL_CPL_PREFER_DXPRESENT_PREFER_ENABLED for base profile
[2024:07:29:08:00:38]: Info: Compiling shaders...
[2024:07:29:08:00:38]: Info: Compiled shaders
[2024:07:29:08:00:39]: Info: Trying encoder [nvenc]
[2024:07:29:08:00:39]: Info: ddprobe.exe [1] [] returned: 0x00000000
[2024:07:29:08:00:39]: Info: Set GPU preference: 1
[2024:07:29:08:00:39]: Info: 
Device Description : NVIDIA GeForce GT 730
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00001287
Device Video Mem   : 2007 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 4074 MiB
Feature Level      : 0x0000B000
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2024:07:29:08:00:39]: Info: Active GPU has HAGS disabled
[2024:07:29:08:00:39]: Info: Using realtime GPU priority
[2024:07:29:08:00:39]: Info: Desktop resolution [1920x1080]
[2024:07:29:08:00:39]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:07:29:08:00:39]: Info: Display refresh rate [24Hz]
[2024:07:29:08:00:39]: Info: Requested frame rate [60fps]
[2024:07:29:08:00:39]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.339844]
Green Primary      : [0.299805,0.69043]
Blue Primary       : [0.137695,0.0380859]
White Point        : [0.282227,0.296875]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:07:29:08:00:39]: Info: SDR color coding [Rec. 601]
[2024:07:29:08:00:39]: Info: Color depth: 8-bit
[2024:07:29:08:00:39]: Info: Color range: [JPEG]
[2024:07:29:08:00:39]: Info: NvEnc: created encoder P1
[2024:07:29:08:00:39]: Info: SDR color coding [Rec. 601]
[2024:07:29:08:00:39]: Info: Color depth: 8-bit
[2024:07:29:08:00:39]: Info: Color range: [JPEG]
[2024:07:29:08:00:39]: Error: NvEnc: encoding format is not supported by the gpu
[2024:07:29:08:00:39]: Info: SDR color coding [Rec. 601]
[2024:07:29:08:00:39]: Info: Color depth: 8-bit
[2024:07:29:08:00:39]: Info: Color range: [JPEG]
[2024:07:29:08:00:39]: Error: NvEncOpenEncodeSessionEx failed: NV_ENC_ERR_INVALID_VERSION
[2024:07:29:08:00:39]: Info: 
Device Description : NVIDIA GeForce GT 730
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00001287
Device Video Mem   : 2007 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 4074 MiB
Feature Level      : 0x0000B000
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2024:07:29:08:00:39]: Info: Active GPU has HAGS disabled
[2024:07:29:08:00:39]: Info: Using realtime GPU priority
[2024:07:29:08:00:39]: Info: Desktop resolution [1920x1080]
[2024:07:29:08:00:39]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:07:29:08:00:39]: Info: Display refresh rate [24Hz]
[2024:07:29:08:00:39]: Info: Requested frame rate [60fps]
[2024:07:29:08:00:39]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.339844]
Green Primary      : [0.299805,0.69043]
Blue Primary       : [0.137695,0.0380859]
White Point        : [0.282227,0.296875]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2024:07:29:08:00:39]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2024:07:29:08:00:39]: Info: 
[2024:07:29:08:00:39]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2024:07:29:08:00:39]: Info: 
[2024:07:29:08:00:39]: Info: Found H.264 encoder: h264_nvenc [nvenc]
[2024:07:29:08:00:40]: Info: Configuration UI available at [https://localhost:47990]
[2024:07:29:08:00:40]: Info: Registered Sunshine mDNS service
[2024:07:29:08:00:43]: Info: Completed UPnP port mappings to 192.168.1.8 via http://192.168.1.1:49652/49652gatedesc.xml
[2024:07:29:08:01:09]: Info: Encoder reenumeration is required
[2024:07:29:08:01:09]: Info: Trying encoder [nvenc]
[2024:07:29:08:01:10]: Info: 
Device Description : NVIDIA GeForce GT 730
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00001287
Device Video Mem   : 2007 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 4074 MiB
Feature Level      : 0x0000B000
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2024:07:29:08:01:10]: Info: Active GPU has HAGS disabled
[2024:07:29:08:01:10]: Info: Using realtime GPU priority
[2024:07:29:08:01:10]: Info: Desktop resolution [1920x1080]
[2024:07:29:08:01:10]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
```

**Comment by ReenigneArcher** [comment] 2024-07-29 02:44
Duplicate of #1416 and #2689 

Basically, the anti-cheat software blocks virtual input. Sorry, there isn't anything we can do about it.

**Closed by ReenigneArcher** 2024-07-29 02:44 UTC
Labels: input:mouse
