### ISSUE TITLE
Run DO - UNDO command when Client gets connected disconnected, not just Starting and Quitting Session

### ISSUE THREAD

**Issue by RebelliousX** [LizardByte/Sunshine#3481] opened 2024-12-23 13:54 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [x] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

Related to #3430 but different issue.

I downloaded `SetVol` app from [here](https://github.com/roblatour/setvol/releases) on github and added command for `DO` and `Undo` like

For Do:
```
C:\temp\SetVol mute
```

For Undo:
```
 C:\temp\SetVol unmute
```

Which works great. The issue is, the UNDO command doesn't run when the `client gets disconnected`, but only when `session quits`. That is, if I minimize Moonlight, the client disconnects, streaming stops, but Volume still muted. If I open Moonlight and force session to quit, the `Undo` command runs. 

I also have similar issue when running VDD trying to run UNDO command when client disconnect, for example Moonlight on Shield TV (session is on, just Moonlight minimized). The Undo command to switch back to main display doesn't run until I force quit the session from Moonlight. The host's main displplay remains black until I force quit the session even if Moonlight is disconnected.

**Comment by ReenigneArcher** [comment] 2024-12-23 21:46
Duplicate of https://github.com/orgs/LizardByte/discussions/408

**Closed by ReenigneArcher** 2024-12-23 21:46 UTC

**Comment by RebelliousX** [comment] 2024-12-24 01:58
@ReenigneArcher excuse me, sorry if I sound like a jerk, but a duplicate of an unanswered not in `issues` but a discussion post from 10 months ago? Probably it is better imo to leave this issue opened.

**Comment by ReenigneArcher** [comment] 2024-12-24 02:45
This is a feature request, and we keep those in discussions.

"Issues" are for bug reports.

There's a few reasons we track feature requests outside of issues.

1. Issues are automatically closed after 100 days with no activity, and feature requests are very likely to hit this. In "discussions" they remain open until added or rejected.
2. Other user's can upvote the requests.
3. I don't want the ~110 open feature requests added to the issue list.

**Comment by RebelliousX** [comment] 2024-12-24 06:02
Makes sense, thanks.

**Comment by RebelliousX** [comment] 2024-12-24 20:03
With the help of ChatGPT, it wrote a PowerShell script within a minute that works beautifully

This is for Undo command when Client gets Disconnected:

```powershell
$logFilePath = "C:\Program Files\Sunshine\config\sunshine.log"
$batchFilePath = "C:\Temp\UnmuteVolume.bat"
$matchPattern = "CLIENT DISCONNECTED"

# Monitor the log file for new content
Get-Content $logFilePath -Wait | ForEach-Object {
    if ($_ -match $matchPattern) {
        # When the pattern is matched, execute the batch file
        Start-Process -WindowStyle hidden -FilePath $batchFilePath
    }
}
```

> UnmuteVolume.bat
```batch
@echo off
C:\Temp\SetVol.exe unmute
```

This is for Undo command when Client gets Connected:

```powershell
$logFilePath = "C:\Program Files\Sunshine\config\sunshine.log"
$batchFilePath = "C:\Temp\MuteVolume.bat"
$matchPattern = "CLIENT CONNECTED"

# Monitor the log file for new content
Get-Content $logFilePath -Wait | ForEach-Object {
    if ($_ -match $matchPattern) {
        # When the pattern is matched, execute the batch file
        Start-Process -WindowStyle hidden -FilePath $batchFilePath
    }
}
```

> MuteVolume.bat
```batch
@echo off
C:\Temp\SetVol.exe mute
```

As executing the two PowerShell scripts, probably Task Scheduler with "Run whether user logged in or not" will prevent terminal from showing up when executing the script at startup.
