### ISSUE TITLE
Sunshine randomly crashes

### ISSUE THREAD

**Issue by emkay1981** [LizardByte/Sunshine#1967] opened 2024-01-01 10:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Sunshine randomly crashes. Moonlight disconnects. 
[sunshine-crash-event.txt](https://github.com/LizardByte/Sunshine/files/13804225/sunshine-crash-event.txt)
[sunshine-crash-event-detail.txt](https://github.com/LizardByte/Sunshine/files/13804226/sunshine-crash-event-detail.txt)

### Host Operating System

Windows

### Operating System Version

23H2

### Architecture

64 bit

### Sunshine commit or version

v0.21.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

Geforce 3070

### GPU Driver/Mesa Version

546.29

### Config

```Shell
encoder = nvenc
fps = [10,30,60]
resolutions = [
    1280x720,
    1920x1080
]
```

### Relevant log output

```shell
Logging inside files
```

**Comment by ReenigneArcher** [comment] 2024-01-01 13:02
Closing per https://docs.lizardbyte.dev/en/latest/about/support.html

If you discover the cause, feel free to let us know.

**Closed** 2024-01-01 13:02 UTC
