### ISSUE TITLE
Streamed Audio distorted with Pipewire 0.3.52

### ISSUE THREAD

**Issue by falk4243** [LizardByte/Sunshine#188] opened 2022-06-14 10:26 UTC
### Describe the Bug

When udating to the latest Pulseaudio version (0.3.52) available via apt, audio streamed via Sunshine is badly distorted.(tested on Moonlight Android and iOS).

### Expected Behavior

Audio should stream normally, without any distortions as it has with Pipewire until v0.3.51.

### Additional Context

Downgrading Pipewire to v0.3.51 (using Debian snapshot) immediately fixed the problem and so I took a closer look at the [change log](https://gitlab.freedesktop.org/pipewire/pipewire/-/releases). Maybe somebody else can dig deeper, but what stood out to me was the following point:

_- Add 44.1KHz to allowed samplerates. The server can now switch by default between 48KHz and 44.1KHz._

This is also the only part that has changed in "pipewire.conf", but changing it back (i.e. delete the 44100 Hz from "default.clock.allowed-rates") didn't fix the distortions unfortunately.

I'm posting this as also as a Sunshine bug for now as local sound devices continue to play just fine and just sound streamed via Sunshine seems to be affected.

### Sunshine Host Operating System and Version

Debian 12 (testing)

### Architecture

64-bit

### Sunshine Version

13.0

### GPU Type

AMD

### GPU Model

5750G (Vega 8)

### GPU Driver/Mesa Version

Mesa 21.3.8

**Comment by ReenigneArcher** [comment] 2022-06-14 10:55
Duplicate of #168

**Closed** 2022-06-14 10:56 UTC
Labels: invalid:duplicate, os:Linux:Debian
