### ISSUE TITLE
Failed to Install Sunshine Using Homebrew on macOS

### ISSUE THREAD

**Issue by Qifull** [LizardByte/Sunshine#3297] opened 2024-10-12 16:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

I’m experiencing a repeated installation failure when attempting to install Sunshine via Homebrew on macOS.

Steps to Reproduce:

	1.	Run brew install sunshine
	2.	The process halts at 54% during the build target for web-ui.
	3.	The error message returned is make: *** [all] Error 2.

Terminal Output: 
```> brew install sunshine
==> Fetching lizardbyte/homebrew/sunshine
==> Cloning https://github.com/LizardByte/Sunshine.git
Updating /Users/qifull/Library/Caches/Homebrew/sunshine--git
==> Checking out tag v0.23.1
HEAD is now at 8b21db64 Merge pull request #2388 from LizardByte/nightly
HEAD is now at 8b21db64 Merge pull request #2388 from LizardByte/nightly
Entering 'packaging/linux/flatpak/deps/org.flatpak.Builder.BaseApp'
Entering 'packaging/linux/flatpak/deps/shared-modules'
Entering 'third-party/Simple-Web-Server'
Entering 'third-party/TPCircularBuffer'
Entering 'third-party/ViGEmClient'
Entering 'third-party/build-deps'
Entering 'third-party/googletest'
Entering 'third-party/moonlight-common-c'
Synchronizing submodule url for 'enet'
Entering 'third-party/moonlight-common-c/enet'
Entering 'third-party/nanors'
Entering 'third-party/nv-codec-headers'
Entering 'third-party/nvapi-open-source-sdk'
Entering 'third-party/tray'
Entering 'third-party/wayland-protocols'
Entering 'third-party/wlr-protocols'
/Users/qifull/Library/Caches/Homebrew/sunshine--git/packaging/linux/flatpak/deps/org.flatpak.Builder.BaseApp
/Users/qifull/Library/Caches/Homebrew/sunshine--git/packaging/linux/flatpak/deps/shared-modules
/Users/qifull/Library/Caches/Homebrew/sunshine--git/third-party/Simple-Web-Server
/Users/qifull/Library/Caches/Homebrew/sunshine--git/third-party/TPCircularBuffer
/Users/qifull/Library/Caches/Homebrew/sunshine--git/third-party/ViGEmClient
/Users/qifull/Library/Caches/Homebrew/sunshine--git/third-party/build-deps
/Users/qifull/Library/Caches/Homebrew/sunshine--git/third-party/googletest
/Users/qifull/Library/Caches/Homebrew/sunshine--git/third-party/moonlight-common-c
/Users/qifull/Library/Caches/Homebrew/sunshine--git/third-party/moonlight-common-c/enet
/Users/qifull/Library/Caches/Homebrew/sunshine--git/third-party/nanors
/Users/qifull/Library/Caches/Homebrew/sunshine--git/third-party/nv-codec-headers
/Users/qifull/Library/Caches/Homebrew/sunshine--git/third-party/nvapi-open-source-sdk
/Users/qifull/Library/Caches/Homebrew/sunshine--git/third-party/tray
/Users/qifull/Library/Caches/Homebrew/sunshine--git/third-party/wayland-protocols
/Users/qifull/Library/Caches/Homebrew/sunshine--git/third-party/wlr-protocols
==> Installing sunshine from lizardbyte/homebrew
==> cmake -S . -B build -DBUILD_WERROR=ON -DOPENSSL_ROOT_DIR=/opt/homebrew/opt/o
==> make -j
Last 15 lines from /Users/qifull/Library/Logs/Homebrew/sunshine/02.make:
../../../../build/assets/web/assets/Navbar-48ec9d0d.css                       0.07 kB │ gzip:   0.09 kB
../../../../build/assets/web/assets/_plugin-vue_export-helper-cff45802.css  327.59 kB │ gzip:  54.06 kB
../../../../build/assets/web/assets/password-41ebda5b.js                      0.63 kB │ gzip:   0.41 kB
../../../../build/assets/web/assets/welcome-6454da3a.js                       0.66 kB │ gzip:   0.42 kB
../../../../build/assets/web/assets/pin-677ef343.js                           0.81 kB │ gzip:   0.43 kB
../../../../build/assets/web/assets/troubleshooting-76080e6f.js               1.36 kB │ gzip:   0.59 kB
../../../../build/assets/web/assets/ResourceCard-ea4a7cba.js                  1.67 kB │ gzip:   0.64 kB
../../../../build/assets/web/assets/index-1d511c0f.js                         2.06 kB │ gzip:   0.90 kB
../../../../build/assets/web/assets/Navbar-dbaf0800.js                        2.16 kB │ gzip:   0.94 kB
../../../../build/assets/web/assets/config-f4fb6dcb.js                        4.97 kB │ gzip:   2.10 kB
../../../../build/assets/web/assets/apps-966a1e70.js                         85.57 kB │ gzip:  25.93 kB
../../../../build/assets/web/assets/_plugin-vue_export-helper-fe085d29.js   327.84 kB │ gzip: 111.98 kB
✓ built in 969ms
[ 54%] Built target web-ui
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/lizardbyte/homebrew-homebrew/issues


 ~ 
``` 
**Additional Details:**
-  The Log 01.cmake
```
2024-10-12 16:17:08 +0000

cmake
-S
.
-B
build
-DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/sunshine/0.23.1
-DCMAKE_INSTALL_LIBDIR=lib
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_FIND_FRAMEWORK=LAST
-DCMAKE_VERBOSE_MAKEFILE=ON
-DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=/opt/homebrew/Library/Homebrew/cmake/trap_fetchcontent_provider.cmake
-Wno-dev
-DBUILD_TESTING=OFF
-DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk
-DBUILD_WERROR=ON
-DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/sunshine/0.23.1
-DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl@3
-DSUNSHINE_ASSETS_DIR=sunshine/assets
-DSUNSHINE_BUILD_HOMEBREW=ON
-DTESTS_ENABLE_PYTHON_TESTS=OFF

-- The C compiler identification is AppleClang 16.0.0.16000026
-- The CXX compiler identification is AppleClang 16.0.0.16000026
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/homebrew/Library/Homebrew/shims/mac/super/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Got from CI master branch and version v0.23.1
-- Looking for fcntl
-- Looking for fcntl - found
-- Looking for ioctl
-- Looking for ioctl - found
-- Looking for poll
-- Looking for poll - found
-- Looking for getaddrinfo
-- Looking for getaddrinfo - found
-- Looking for getnameinfo
-- Looking for getnameinfo - found
-- Looking for gethostbyname_r
-- Looking for gethostbyname_r - not found
-- Looking for gethostbyaddr_r
-- Looking for gethostbyaddr_r - not found
-- Looking for inet_pton
-- Looking for inet_pton - found
-- Looking for inet_ntop
-- Looking for inet_ntop - found
-- Performing Test HAS_MSGHDR_FLAGS
-- Performing Test HAS_MSGHDR_FLAGS - Success
-- Check size of socklen_t
-- Check size of socklen_t - done
-- Check size of QOS_FLOWID
-- Check size of QOS_FLOWID - failed
-- Check size of PQOS_FLOWID
-- Check size of PQOS_FLOWID - failed
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found Boost: /opt/homebrew/lib/cmake/Boost-1.86.0/BoostConfig.cmake (found suitable version "1.86.0", minimum required is "1.53.0") found components: system
-- Found OpenSSL: /opt/homebrew/opt/openssl/lib/libcrypto.dylib (found version "3.3.2")
-- Found PkgConfig: /opt/homebrew/bin/pkg-config (found version "0.29.2")
-- Checking for module 'libcurl'
--   Found libcurl, version 8.10.1
-- Checking for module 'miniupnpc'
--   Found miniupnpc, version 2.2.8
-- Found Boost: /opt/homebrew/lib/cmake/Boost-1.86.0/BoostConfig.cmake (found version "1.86.0") found components: locale log filesystem program_options
-- Found Python3: /opt/homebrew/bin/python3.12 (found version "3.12.7") found components: Interpreter
-- Python tests are disabled by 'TESTS_ENABLE_PYTHON_TESTS' option
-- Configuring done (3.2s)
-- Generating done (0.1s)
-- Build files have been written to: /tmp/sunshine-20241013-58059-u9wn1r/build
```

### Host Operating System

macOS

### Operating System Version

macOS Version 15.0.1 (24A348)

### Architecture

arm64/aarch64

### Sunshine commit or version

There is no version displayed after installation, indicating a failure in the installation process.

### Package

macOS - Homebrew

### GPU Type

Apple Silicon

### GPU Model

Apple M2 

### GPU Driver/Mesa Version

macOS Version 15.0.1 (24A348)

### Capture Method

None

### Relevant log output

```shell
2024-10-12 16:17:08 +0000

cmake
-S
.
-B
build
-DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/sunshine/0.23.1
-DCMAKE_INSTALL_LIBDIR=lib
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_FIND_FRAMEWORK=LAST
-DCMAKE_VERBOSE_MAKEFILE=ON
-DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=/opt/homebrew/Library/Homebrew/cmake/trap_fetchcontent_provider.cmake
-Wno-dev
-DBUILD_TESTING=OFF
-DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk
-DBUILD_WERROR=ON
-DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/sunshine/0.23.1
-DOPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl@3
-DSUNSHINE_ASSETS_DIR=sunshine/assets
-DSUNSHINE_BUILD_HOMEBREW=ON
-DTESTS_ENABLE_PYTHON_TESTS=OFF

-- The C compiler identification is AppleClang 16.0.0.16000026
-- The CXX compiler identification is AppleClang 16.0.0.16000026
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/homebrew/Library/Homebrew/shims/mac/super/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Got from CI master branch and version v0.23.1
-- Looking for fcntl
-- Looking for fcntl - found
-- Looking for ioctl
-- Looking for ioctl - found
-- Looking for poll
-- Looking for poll - found
-- Looking for getaddrinfo
-- Looking for getaddrinfo - found
-- Looking for getnameinfo
-- Looking for getnameinfo - found
-- Looking for gethostbyname_r
-- Looking for gethostbyname_r - not found
-- Looking for gethostbyaddr_r
-- Looking for gethostbyaddr_r - not found
-- Looking for inet_pton
-- Looking for inet_pton - found
-- Looking for inet_ntop
-- Looking for inet_ntop - found
-- Performing Test HAS_MSGHDR_FLAGS
-- Performing Test HAS_MSGHDR_FLAGS - Success
-- Check size of socklen_t
-- Check size of socklen_t - done
-- Check size of QOS_FLOWID
-- Check size of QOS_FLOWID - failed
-- Check size of PQOS_FLOWID
-- Check size of PQOS_FLOWID - failed
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found Boost: /opt/homebrew/lib/cmake/Boost-1.86.0/BoostConfig.cmake (found suitable version "1.86.0", minimum required is "1.53.0") found components: system
-- Found OpenSSL: /opt/homebrew/opt/openssl/lib/libcrypto.dylib (found version "3.3.2")
-- Found PkgConfig: /opt/homebrew/bin/pkg-config (found version "0.29.2")
-- Checking for module 'libcurl'
--   Found libcurl, version 8.10.1
-- Checking for module 'miniupnpc'
--   Found miniupnpc, version 2.2.8
-- Found Boost: /opt/homebrew/lib/cmake/Boost-1.86.0/BoostConfig.cmake (found version "1.86.0") found components: locale log filesystem program_options
-- Found Python3: /opt/homebrew/bin/python3.12 (found version "3.12.7") found components: Interpreter
-- Python tests are disabled by 'TESTS_ENABLE_PYTHON_TESTS' option
-- Configuring done (3.2s)
-- Generating done (0.1s)
-- Build files have been written to: /tmp/sunshine-20241013-58059-u9wn1r/build
```

**Comment by ReenigneArcher** [comment] 2024-10-12 16:54
Duplicate of #3180

**Closed by ReenigneArcher** 2024-10-12 16:54 UTC
