### ISSUE TITLE
Stuttering and Ghosting with ‘vsync:fast’ Configuration in the NVIDIA Control Panel.

### ISSUE THREAD

**Issue by Kane-Kuroneko** [LizardByte/Sunshine#2530] opened 2024-05-13 17:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Sunshine is not working normally with ‘vsync:fast’ configured in the NVIDIA Control Panel. 
I’ve tried everything, and I’ve determined that the final reason is due to this configuration difference. 
These two videos have shown that one was working well, while the other was stuttering and ghosting.
There is no difference between the two video demos, except for ‘vsync:fast’ and ‘vsync:enabled’ settings.

https://github.com/LizardByte/Sunshine/assets/40685018/7a6b0530-869e-4419-957e-3d03d06c9b35

https://github.com/LizardByte/Sunshine/assets/40685018/4db97e59-f11c-4334-bb8f-65d31585d1d9

### Expected Behavior

Expect Sunshine work fine with 'vsync:fast' configuration.

### Additional Context
You can replicate the issue by setting vsync to ‘fast’ in the NVIDIA Control Panel and locking the maximum frame rate to 60fps.
_No response_

### Host Operating System

Windows

### Operating System Version

Windows 11 Workstation 23H2 

### Architecture

64 bit

### Sunshine commit or version

v0.23.1

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 4090

### GPU Driver/Mesa Version

552.22

### Config

```Shell
encoder = nvenc
qp = 20
fec_percentage = 30
locale = zh
gamepad = x360
key_repeat_delay = 100
fps = [60,90,120]
min_threads = 12
nvenc_preset = 4
nvenc_vbv_increase = 10
```

### Relevant log output

```shell
[2024:05:13:21:13:52]: Info: Sunshine version: v0.23.1
[2024:05:13:21:13:52]: Info: nvprefs: No need to modify application profile settings
[2024:05:13:21:13:52]: Info: nvprefs: Changed OGL_CPL_PREFER_DXPRESENT to OGL_CPL_PREFER_DXPRESENT_PREFER_ENABLED for base profile
[2024:05:13:21:13:52]: Info: Compiling shaders...
[2024:05:13:21:13:52]: Info: System tray created
[2024:05:13:21:13:52]: Info: Compiled shaders
[2024:05:13:21:13:53]: Info: Trying encoder [nvenc]
[2024:05:13:21:13:53]: Info: ddprobe.exe [1] [] returned: 0x00000000
[2024:05:13:21:13:53]: Info: Set GPU preference: 1
[2024:05:13:21:13:53]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24142 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16335 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2024:05:13:21:13:53]: Info: Active GPU has HAGS disabled
[2024:05:13:21:13:53]: Info: Using realtime GPU priority
[2024:05:13:21:13:53]: Info: Desktop resolution [3840x2160]
[2024:05:13:21:13:53]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:05:13:21:13:53]: Info: Display refresh rate [59.997Hz]
[2024:05:13:21:13:53]: Info: Requested frame rate [60fps]
[2024:05:13:21:13:53]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.686523,0.307617]
Green Primary      : [0.224609,0.720703]
Blue Primary       : [0.150391,0.0664062]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.0825 nits
Max Luminance      : 1015.27 nits
Max Full Luminance : 603.698 nits
[2024:05:13:21:13:53]: Info: SDR color coding [Rec. 601]
[2024:05:13:21:13:53]: Info: Color depth: 8-bit
[2024:05:13:21:13:53]: Info: Color range: [JPEG]
[2024:05:13:21:13:53]: Info: NvEnc: created encoder P4 two-pass vbv+10 rfi
[2024:05:13:21:13:53]: Info: SDR color coding [Rec. 601]
[2024:05:13:21:13:53]: Info: Color depth: 8-bit
[2024:05:13:21:13:53]: Info: Color range: [JPEG]
[2024:05:13:21:13:53]: Info: NvEnc: created encoder P4 two-pass vbv+10 rfi
[2024:05:13:21:13:53]: Info: SDR color coding [Rec. 601]
[2024:05:13:21:13:53]: Info: Color depth: 8-bit
[2024:05:13:21:13:53]: Info: Color range: [JPEG]
[2024:05:13:21:13:53]: Info: NvEnc: created encoder P4 two-pass vbv+10 rfi
[2024:05:13:21:13:54]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24142 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16335 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2024:05:13:21:13:54]: Info: Active GPU has HAGS disabled
[2024:05:13:21:13:54]: Info: Using realtime GPU priority
[2024:05:13:21:13:54]: Info: Desktop resolution [3840x2160]
[2024:05:13:21:13:54]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:05:13:21:13:54]: Info: Display refresh rate [59.997Hz]
[2024:05:13:21:13:54]: Info: Requested frame rate [60fps]
[2024:05:13:21:13:54]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.686523,0.307617]
Green Primary      : [0.224609,0.720703]
Blue Primary       : [0.150391,0.0664062]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.0825 nits
Max Luminance      : 1015.27 nits
Max Full Luminance : 603.698 nits
[2024:05:13:21:13:54]: Info: SDR color coding [Rec. 709]
[2024:05:13:21:13:54]: Info: Color depth: 10-bit
[2024:05:13:21:13:54]: Info: Color range: [JPEG]
[2024:05:13:21:13:54]: Info: NvEnc: created encoder P4 10-bit two-pass vbv+10 rfi
[2024:05:13:21:13:54]: Info: SDR color coding [Rec. 709]
[2024:05:13:21:13:54]: Info: Color depth: 10-bit
[2024:05:13:21:13:54]: Info: Color range: [JPEG]
[2024:05:13:21:13:54]: Info: NvEnc: created encoder P4 10-bit two-pass vbv+10 rfi
[2024:05:13:21:13:54]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2024:05:13:21:13:54]: Info: 
[2024:05:13:21:13:54]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2024:05:13:21:13:54]: Info: 
[2024:05:13:21:13:54]: Info: Found H.264 encoder: h264_nvenc [nvenc]
[2024:05:13:21:13:54]: Info: Found HEVC encoder: hevc_nvenc [nvenc]
[2024:05:13:21:13:54]: Info: Found AV1 encoder: av1_nvenc [nvenc]
[2024:05:13:21:13:54]: Info: Configuration UI available at [https://localhost:47990]
[2024:05:13:21:13:55]: Info: Registered Sunshine mDNS service
[2024:05:13:21:15:46]: Info: Opening UI from system tray
[2024:05:13:21:15:46]: Info: Resolved user-provided command 'https://localhost:47990' to '"C:\Program Files\Google\Chrome\Application\chrome.exe" --single-argument https://localhost:47990'
[2024:05:13:21:15:46]: Info: https://localhost:47990 running with PID 11656
[2024:05:13:21:15:46]: Info: Opened url [https://localhost:47990]
[2024:05:13:21:15:47]: Info: Web UI: [127.0.0.1] -- not authorized
[2024:05:13:21:15:47]: Info: Web UI: [127.0.0.1] -- not authorized
[2024:05:13:21:15:50]: Info: Web UI: [127.0.0.1] -- not authorized
[2024:05:13:21:16:33]: Info: Encoder reenumeration is required
[2024:05:13:21:16:33]: Info: Trying encoder [nvenc]
[2024:05:13:21:16:33]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24142 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16335 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2024:05:13:21:16:33]: Info: Active GPU has HAGS disabled
[2024:05:13:21:16:33]: Info: Using realtime GPU priority
[2024:05:13:21:16:33]: Info: Desktop resolution [3840x2160]
[2024:05:13:21:16:33]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:05:13:21:16:33]: Info: Display refresh rate [59.997Hz]
[2024:05:13:21:16:33]: Info: Requested frame rate [60fps]
[2024:05:13:21:16:33]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.686523,0.307617]
Green Primary      : [0.224609,0.720703]
Blue Primary       : [0.150391,0.0664062]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.0825 nits
Max Luminance      : 1015.27 nits
Max Full Luminance : 603.698 nits
[2024:05:13:21:16:33]: Info: SDR color coding [Rec. 601]
[2024:05:13:21:16:33]: Info: Color depth: 8-bit
[2024:05:13:21:16:33]: Info: Color range: [JPEG]
[2024:05:13:21:16:33]: Info: NvEnc: created encoder P4 two-pass vbv+10 rfi
[2024:05:13:21:16:33]: Info: SDR color coding [Rec. 601]
[2024:05:13:21:16:33]: Info: Color depth: 8-bit
[2024:05:13:21:16:33]: Info: Color range: [JPEG]
[2024:05:13:21:16:33]: Info: NvEnc: created encoder P4 two-pass vbv+10 rfi
[2024:05:13:21:16:33]: Info: SDR color coding [Rec. 601]
[2024:05:13:21:16:33]: Info: Color depth: 8-bit
[2024:05:13:21:16:33]: Info: Color range: [JPEG]
[2024:05:13:21:16:33]: Info: NvEnc: created encoder P4 two-pass vbv+10 rfi
[2024:05:13:21:16:33]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24142 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16335 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2024:05:13:21:16:33]: Info: Active GPU has HAGS disabled
[2024:05:13:21:16:33]: Info: Using realtime GPU priority
[2024:05:13:21:16:33]: Info: Desktop resolution [3840x2160]
[2024:05:13:21:16:33]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:05:13:21:16:33]: Info: Display refresh rate [59.997Hz]
[2024:05:13:21:16:33]: Info: Requested frame rate [60fps]
[2024:05:13:21:16:33]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.686523,0.307617]
Green Primary      : [0.224609,0.720703]
Blue Primary       : [0.150391,0.0664062]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.0825 nits
Max Luminance      : 1015.27 nits
Max Full Luminance : 603.698 nits
[2024:05:13:21:16:33]: Info: SDR color coding [Rec. 709]
[2024:05:13:21:16:33]: Info: Color depth: 10-bit
[2024:05:13:21:16:33]: Info: Color range: [JPEG]
[2024:05:13:21:16:33]: Info: NvEnc: created encoder P4 10-bit two-pass vbv+10 rfi
[2024:05:13:21:16:33]: Info: SDR color coding [Rec. 709]
[2024:05:13:21:16:33]: Info: Color depth: 10-bit
[2024:05:13:21:16:33]: Info: Color range: [JPEG]
[2024:05:13:21:16:33]: Info: NvEnc: created encoder P4 10-bit two-pass vbv+10 rfi
[2024:05:13:21:16:33]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2024:05:13:21:16:33]: Info: 
[2024:05:13:21:16:33]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2024:05:13:21:16:33]: Info: 
[2024:05:13:21:16:33]: Info: Found H.264 encoder: h264_nvenc [nvenc]
[2024:05:13:21:16:33]: Info: Found HEVC encoder: hevc_nvenc [nvenc]
[2024:05:13:21:16:33]: Info: Found AV1 encoder: av1_nvenc [nvenc]
[2024:05:13:21:16:33]: Info: Executing: [W:\Gaming\Lifeslide\Lifeslide.exe] in ["W:\Gaming\Lifeslide"]
[2024:05:13:21:16:33]: Info: W:\Gaming\Lifeslide\Lifeslide.exe running with PID 8940
[2024:05:13:21:16:34]: Info: nvprefs: No need to modify application profile settings
[2024:05:13:21:16:34]: Info: nvprefs: No need to modify global profile settings
[2024:05:13:21:16:34]: Info: CLIENT CONNECTED
[2024:05:13:21:16:34]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24142 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16335 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2024:05:13:21:16:34]: Info: Active GPU has HAGS disabled
[2024:05:13:21:16:34]: Info: Using realtime GPU priority
[2024:05:13:21:16:34]: Info: Desktop resolution [3840x2160]
[2024:05:13:21:16:34]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:05:13:21:16:34]: Info: Display refresh rate [59.997Hz]
[2024:05:13:21:16:34]: Info: Requested frame rate [60fps]
[2024:05:13:21:16:34]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.686523,0.307617]
Green Primary      : [0.224609,0.720703]
Blue Primary       : [0.150391,0.0664062]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.0825 nits
Max Luminance      : 1015.27 nits
Max Full Luminance : 603.698 nits
[2024:05:13:21:16:34]: Info: Adjusted capture rate to 59.997fps to better match display
[2024:05:13:21:16:34]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:05:13:21:16:34]: Info: SDR color coding [Rec. 709]
[2024:05:13:21:16:34]: Info: Color depth: 10-bit
[2024:05:13:21:16:34]: Info: Color range: [MPEG]
[2024:05:13:21:16:34]: Info: NvEnc: created encoder P4 10-bit two-pass vbv+10 rfi
[2024:05:13:21:16:58]: Info: CLIENT DISCONNECTED
[2024:05:13:21:17:34]: Info: nvprefs: No need to modify application profile settings
[2024:05:13:21:17:34]: Info: nvprefs: No need to modify global profile settings
[2024:05:13:21:17:34]: Info: CLIENT CONNECTED
[2024:05:13:21:17:34]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24142 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16335 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2024:05:13:21:17:34]: Info: Active GPU has HAGS disabled
[2024:05:13:21:17:34]: Info: Using realtime GPU priority
[2024:05:13:21:17:34]: Info: Desktop resolution [3840x2160]
[2024:05:13:21:17:34]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:05:13:21:17:34]: Info: Display refresh rate [59.997Hz]
[2024:05:13:21:17:34]: Info: Requested frame rate [120fps]
[2024:05:13:21:17:34]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.686523,0.307617]
Green Primary      : [0.224609,0.720703]
Blue Primary       : [0.150391,0.0664062]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.0825 nits
Max Luminance      : 1015.27 nits
Max Full Luminance : 603.698 nits
[2024:05:13:21:17:34]: Info: Adjusted capture rate to 119.994fps to better match display
[2024:05:13:21:17:34]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:05:13:21:17:34]: Info: SDR color coding [Rec. 709]
[2024:05:13:21:17:34]: Info: Color depth: 10-bit
[2024:05:13:21:17:34]: Info: Color range: [MPEG]
[2024:05:13:21:17:34]: Info: NvEnc: created encoder P4 10-bit two-pass vbv+10 rfi
[2024:05:13:21:18:34]: Info: App exited with code [0]
[2024:05:13:21:18:34]: Info: Process terminated
[2024:05:13:21:18:36]: Info: Executing: ["Y:\A2123\A2123 Up2\Darksiders2.exe"] in ["Y:\A2123\A2123 Up2"]
[2024:05:13:21:18:36]: Info: "Y:\A2123\A2123 Up2\Darksiders2.exe" running with PID 18136
[2024:05:13:21:18:36]: Info: nvprefs: No need to modify application profile settings
[2024:05:13:21:18:36]: Info: nvprefs: No need to modify global profile settings
[2024:05:13:21:18:36]: Info: CLIENT CONNECTED
[2024:05:13:21:18:37]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24142 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16335 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2024:05:13:21:18:37]: Info: Active GPU has HAGS disabled
[2024:05:13:21:18:37]: Info: Using realtime GPU priority
[2024:05:13:21:18:37]: Info: Desktop resolution [3840x2160]
[2024:05:13:21:18:37]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:05:13:21:18:37]: Info: Display refresh rate [59.997Hz]
[2024:05:13:21:18:37]: Info: Requested frame rate [120fps]
[2024:05:13:21:18:37]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.686523,0.307617]
Green Primary      : [0.224609,0.720703]
Blue Primary       : [0.150391,0.0664062]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.0825 nits
Max Luminance      : 1015.27 nits
Max Full Luminance : 603.698 nits
[2024:05:13:21:18:37]: Info: Adjusted capture rate to 119.994fps to better match display
[2024:05:13:21:18:37]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:05:13:21:18:37]: Info: SDR color coding [Rec. 709]
[2024:05:13:21:18:37]: Info: Color depth: 10-bit
[2024:05:13:21:18:37]: Info: Color range: [MPEG]
[2024:05:13:21:18:37]: Info: NvEnc: created encoder P4 10-bit two-pass vbv+10 rfi
[2024:05:13:21:19:09]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24142 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16335 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2024:05:13:21:19:09]: Info: Active GPU has HAGS disabled
[2024:05:13:21:19:09]: Info: Using realtime GPU priority
[2024:05:13:21:19:09]: Info: Desktop resolution [3840x2160]
[2024:05:13:21:19:09]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:05:13:21:19:09]: Info: Display refresh rate [59.997Hz]
[2024:05:13:21:19:09]: Info: Requested frame rate [120fps]
[2024:05:13:21:19:09]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.686523,0.307617]
Green Primary      : [0.224609,0.720703]
Blue Primary       : [0.150391,0.0664062]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.0825 nits
Max Luminance      : 1015.27 nits
Max Full Luminance : 603.698 nits
[2024:05:13:21:19:09]: Info: Adjusted capture rate to 119.994fps to better match display
[2024:05:13:21:19:09]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:05:13:21:19:09]: Info: SDR color coding [Rec. 709]
[2024:05:13:21:19:09]: Info: Color depth: 10-bit
[2024:05:13:21:19:09]: Info: Color range: [MPEG]
[2024:05:13:21:19:09]: Info: NvEnc: created encoder P4 10-bit two-pass vbv+10 rfi
[2024:05:13:21:19:23]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24142 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16335 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2024:05:13:21:19:23]: Info: Active GPU has HAGS disabled
[2024:05:13:21:19:23]: Info: Using realtime GPU priority
[2024:05:13:21:19:23]: Info: Desktop resolution [3840x2160]
[2024:05:13:21:19:23]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:05:13:21:19:23]: Info: Display refresh rate [59.997Hz]
[2024:05:13:21:19:23]: Info: Requested frame rate [120fps]
[2024:05:13:21:19:23]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.686523,0.307617]
Green Primary      : [0.224609,0.720703]
Blue Primary       : [0.150391,0.0664062]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.0825 nits
Max Luminance      : 1015.27 nits
Max Full Luminance : 603.698 nits
[2024:05:13:21:19:23]: Info: Adjusted capture rate to 119.994fps to better match display
[2024:05:13:21:19:23]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:05:13:21:19:23]: Info: SDR color coding [Rec. 709]
[2024:05:13:21:19:23]: Info: Color depth: 10-bit
[2024:05:13:21:19:23]: Info: Color range: [MPEG]
[2024:05:13:21:19:23]: Info: NvEnc: created encoder P4 10-bit two-pass vbv+10 rfi
[2024:05:13:21:19:41]: Info: App exited with code [0]
[2024:05:13:21:19:41]: Info: Process terminated
[2024:05:13:21:19:41]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24142 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16335 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2024:05:13:21:19:41]: Info: Active GPU has HAGS disabled
[2024:05:13:21:19:41]: Info: Using realtime GPU priority
[2024:05:13:21:19:41]: Info: Desktop resolution [3840x2160]
[2024:05:13:21:19:41]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:05:13:21:19:41]: Info: Display refresh rate [59.997Hz]
[2024:05:13:21:19:41]: Info: Requested frame rate [120fps]
[2024:05:13:21:19:41]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.686523,0.307617]
Green Primary      : [0.224609,0.720703]
Blue Primary       : [0.150391,0.0664062]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.0825 nits
Max Luminance      : 1015.27 nits
Max Full Luminance : 603.698 nits
[2024:05:13:21:19:42]: Info: Encoder reenumeration is required
[2024:05:13:21:19:42]: Info: Trying encoder [nvenc]
[2024:05:13:21:19:42]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24142 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16335 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2024:05:13:21:19:42]: Info: Active GPU has HAGS disabled
[2024:05:13:21:19:42]: Info: Using realtime GPU priority
[2024:05:13:21:19:42]: Info: Desktop resolution [3840x2160]
[2024:05:13:21:19:42]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2024:05:13:21:19:42]: Info: Display refresh rate [59.997Hz]
[2024:05:13:21:19:42]: Info: Requested frame rate [60fps]
[2024:05:13:21:19:42]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.686523,0.307617]
Green Primary      : [0.224609,0.720703]
Blue Primary       : [0.150391,0.0664062]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.0825 nits
Max Luminance      : 1015.27 nits
Max Full Luminance : 603.698 nits
[2024:05:13:21:19:43]: Info: SDR color coding [Rec. 601]
[2024:05:13:21:19:43]: Info: Color depth: 8-bit
[2024:05:13:21:19:43]: Info: Color range: [JPEG]
[2024:05:13:21:19:43]: Info: NvEnc: created encoder P4 two-pass vbv+10 rfi
[2024:05:13:21:19:43]: Info: SDR color coding [Rec. 601]
[2024:05:13:21:19:43]: Info: Color depth: 8-bit
[2024:05:13:21:19:43]: Info: Color range: [JPEG]
[2024:05:13:21:19:43]: Info: NvEnc: created encoder P4 two-pass vbv+10 rfi
[2024:05:13:21:19:43]: Info: SDR color coding [Rec. 601]
[2024:05:13:21:19:43]: Info: Color depth: 8-bit
[2024:05:13:21:19:43]: Info: Color range: [JPEG]
[2024:05:13:21:19:43]: Info: NvEnc: created encoder P4 two-pass vbv+10 rfi
[2024:05:13:21:19:43]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24142 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16335 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
```

**Comment by tvoracek** [comment] 2024-05-14 18:15
How is that related to Sunshine though? Easy workaround is to create new profile in NVCP just for Sunshine that works for you.

**Comment by Kane-Kuroneko** [comment] 2024-05-15 05:24
> How is that related to Sunshine though? Easy workaround is to create new profile in NVCP just for Sunshine that works for you.

It is does related to Sunshine because gaming on PC is perfect, but there is stuttering on the both of Moonlight(Android &Windows) client. All I need is to change a configuration of global V-Sync.

**Comment by maciekish** [comment] 2024-07-23 10:08
Having the same issue, Vsync: Fast is stuttering on both iPhone and Vision Pro, normal with Let 3d application decide. On PC monitor its smooth with either setting.

**Comment by Kane-Kuroneko** [comment] 2024-08-08 09:45
Is there any solution or explanation for that? It’s been shelved for too long.

**Comment by Nonary** [comment] 2024-08-13 04:06
Unfortunately this is either a Microsoft or NVIDIA bug, confirmed the issue happens on other software products that used both WGC, DXGI and all of them had the exact same problem. This issue is also present when using software encoding, so there really isn't any solution to this.

Fast sync is not recommended for recording in either case.

Since this bug is unresolvable on our side, confirmed with OBS and Discord recordings... closing out this issue.

**Comment by ThibaultNocchi** [comment] 2024-10-29 11:18
Hello,
Thanks a lot for your issue, I've been skimming through the issues here to find why NVENC was badly ghosting in games. I disabled fast VSYNC globally and it works as before!

**Comment by ReenigneArcher** [comment] 2024-10-29 12:53
I'll re-open this as some notes should be added to our docs, at a minimum.

**Comment by Kane-Kuroneko** [comment] 2024-10-29 13:57
> I'll re-open this as some notes should be added to our docs, at a minimum.

Thanks. It should be known by all users to avoid this issue. Additionally, we might need a utility for switching the vsync configuration while Sunshine is running.

**Closed** 2024-12-11 18:11 UTC
Labels: documentation
