### ISSUE TITLE
Sunshine incorrectly encodes using the BT.601 colourspace instead of BT.709, resulting in very incorrect colour reproduction on any connected client.

### ISSUE THREAD

**Issue by akemin-dayo** [LizardByte/Sunshine#300] opened 2022-08-05 19:53 UTC
## Describe the Bug

Sunshine incorrectly encodes using the BT.601 colourspace instead of BT.709, resulting in very incorrect colour reproduction on any connected client.

This behaviour does not occur with either Parsec (which I most often use) or NVIDIA GeForce Experience.

Sunshine log output also confirms the issue.
```
[2022:08:06:04:34:50]: Info:
Device Description : NVIDIA GeForce RTX 2060
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00001F08
Device Video Mem   : 5980 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8111 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 0x0
Virtual Desktop    : 1920x1080
[2022:08:06:04:34:50]: Info: Color coding [Rec. 601]
[2022:08:06:04:34:50]: Info: Color range: [MPEG]
```

## Screenshots
Open the Parsec/NVIDIA GFE/Sunshine screenshots in separate tabs and switch between them to see the difference.

### Parsec (correct, BT.709)
<img alt="testpattern-parsec" src="https://user-images.githubusercontent.com/1980487/183150386-ad05d07e-ee09-4bc0-ae4e-1a1e2424b674.png">
<img alt="nami-parsec" src="https://user-images.githubusercontent.com/1980487/183152107-fab8583f-1b78-40a8-a9e7-bad9feb69a78.png">
<img alt="win10wallpaper-parsec" src="https://user-images.githubusercontent.com/1980487/183152082-a271d845-08c2-485e-bb61-a77183bffd54.png">
<img alt="sunshinewebui-parsec" src="https://user-images.githubusercontent.com/1980487/183155667-c2e4f43e-5682-4fce-b3c5-557388f819d3.png">

### Moonlight + NVIDIA GeForce Experience (correct, BT.709)
<img alt="testpattern-nvidia" src="https://user-images.githubusercontent.com/1980487/183150515-f93e1113-848f-480d-ab4b-c518f2701edc.png">
<img alt="nami-nvidia" src="https://user-images.githubusercontent.com/1980487/183152272-b210424a-afdd-4c92-a6f0-d97716accfdb.png">
<img alt="win10wallpaper-nvidia" src="https://user-images.githubusercontent.com/1980487/183152300-ce3c3ee5-6da3-4298-b1f8-271a3a68d1d3.png">
<img alt="sunshinewebui-nvidia" src="https://user-images.githubusercontent.com/1980487/183155765-1881f4cd-b369-4876-a38a-14bc25b0523e.png">

### Moonlight + Sunshine (incorrect, BT.601)
<img alt="testpattern-sunshine" src="https://user-images.githubusercontent.com/1980487/183150569-26f19549-bd84-4ac6-8561-fd403ce2a6df.png">
<img alt="nami-sunshine" src="https://user-images.githubusercontent.com/1980487/183152334-1c431ef4-7dc9-4800-8f3d-3c366b5c888f.png">
<img alt="win10wallpaper-sunshine" src="https://user-images.githubusercontent.com/1980487/183152356-570355f2-eac0-44c8-9a84-82982b2a2c10.png">
<img alt="sunshinewebui-sunshine" src="https://user-images.githubusercontent.com/1980487/183155782-457d19e5-3e56-4d3c-8f8a-2c4055cbef45.png">

## Sunshine Host Operating System and Version
Windows 10 19044.1865 21H2

## Architecture
x86_64

## Sunshine Version
0.14.0

## GPU
NVIDIA RTX 2060

## GPU Driver Version
516.59

**Comment by KuleRucket** [comment] 2022-08-06 20:39
Out of interest, could you give some pointers on what's different about the incorrect BT.601 colours? Maybe I'm just old but I can't tell the difference even when putting them side by side.

**Comment by akemin-dayo** [comment] 2022-08-06 23:04
I… am going to be honest and say that I'm honestly not sure how to answer that question.

One is incorrect (BT.601), the other is correct (BT.709).

Let's take the `winver` screenshot as an example.

Open either the Parsec or the NVGFE screenshot above in any image editor, then take a colour picker and get the RGB values of the grey part of the window — it should be `#f0f0f0`.

Next, take a local screenshot of your own `winver` window and do the same thing. You should also get the same value of `#f0f0f0`.

Finally, open the Sunshine screenshot above, and use the colour picker on the same part. You'll get a value of `#eef0ed`, which is completely wrong.

Maybe I might just be more sensitive to colour differences than some people, but to me the issue is _immediately_ noticeable even without having to compare, to the point where Sunshine is pretty much unusable to me because the colour inaccuracy really bothers me ;P

**Comment by ReenigneArcher** [comment] 2022-08-28 19:58
I found some reference to this in the code. 601 is default.

https://github.com/LizardByte/Sunshine/blob/6000b85b1a4ec574d93fbc7545f5bf48f3d5aaa7/src/video.cpp#L883-L913

I am not sure if this is an undocumented config option or not, since I can't find a reference to it in the `config.cpp`.

Could you try adding `encoderCscMode=1` to your config file to see if it uses the 709?

**Comment by akemin-dayo** [comment] 2022-08-28 20:47
> I am not sure if this is an undocumented config option or not, since I can't find a reference to it in the config.cpp.

It isn't, as far as I'm aware. The `config` that is being referred to in `video.cpp` is actually a `config_t` struct defined here: https://github.com/LizardByte/Sunshine/blob/6000b85b1a4ec574d93fbc7545f5bf48f3d5aaa7/src/video.h#L53 and has no relation to the config file (as you correctly observed).

And just to be sure, I tried what your suggested anyway but there was no change ;P

**Comment by psyke83** [comment] 2022-09-02 15:32
The colorspace seems to be specified by the client. Testing on my laptop running Linux connecting to a Windows host using software renderering on an AMD GPU, moonlight-qt's logs shows:
```
00:00:08 - SDL Info (0): FFmpeg-based video decoder chosen
```

Looking [here](https://github.com/moonlight-stream/moonlight-qt/blob/be2f4433dbe8dc63a6cb434edf8d98adda5c1495/app/streaming/video/ffmpeg-renderers/renderer.h#L156-L159), it seems that Rec 601 would always be selected if using this renderer.

**Comment by cgutman** [comment] 2022-09-03 17:13
Sunshine should be doing the Rec 709 -> Rec 601 in the case that the Moonlight client requests it. Maybe that's what's going wrong here.

Whether Rec 709 or Rec 601 is picked shouldn't make a difference in color reproduction for renderers that support both. When streaming from GFE, Rec 709 and Rec 601 generate identical RGB values in Moonlight. All it does is change the coefficients used for the RGB->YUV and YUV->RGB conversions and you end up with the same color in the end.

**Comment by w0utert** [comment] 2022-10-07 09:40
I can confirm something is not right with colorspace conversion between sunshine/moonlight and the display. Color reproduction is definitely not great.

I put 2 identical screens next to each other, one running a Linux desktop connected natively through displayport, the other connected to a laptop that remotes into it using Moonlight on windows. Comparing side-by-side colors are washed out, which is particularly visible in bright colored text (orange, yellow, green, etc). The problem is not in the Windows laptop because a VNC remote desktop to the same machine has good color reproduction (but terrible performance).

Is there anything anywhere in the chain (host desktop settings - Sunshine - Moonlight - client desktop settings) that could improve this, or does this need to be fixed in either sunshine and/or moonlight?

**Comment by w0utert** [comment] 2022-10-10 09:56
Scrap my last comment about colorspace conversion, the bad color reproduction I was observing was not actually related to color space handling but to bugs in the RGB to NV12 conversion when using NvFBC with CUDA enabled (see #154)

**Comment by cgutman** [comment] 2023-01-07 22:11
Please try this build from #723 and see if it addresses the issue.

https://github.com/LizardByte/Sunshine/suites/10239661632/artifacts/502111042

**Comment by akemin-dayo** [comment] 2023-01-08 00:52
It improves the issue, but there is still a slightly noticeable difference.

In particular, it still doesn't match the output of NVGFE (or Parsec, though that's less direct of a comparison), although it is _much_ closer now.

---

# Moonlight + Sunshine #723 (improved, BT.601)
![image](https://user-images.githubusercontent.com/1980487/211175671-d8a261fc-836e-428b-8070-03f0bbe0acba.png)
![image](https://user-images.githubusercontent.com/1980487/211175673-d7764eca-7107-4484-81ab-79d7c6ab8e4d.png)
![image](https://user-images.githubusercontent.com/1980487/211175676-8e54a5af-c629-426a-b30f-685e5eeb50cf.png)
![image](https://user-images.githubusercontent.com/1980487/211175677-29d183f5-8ad6-4700-b5ba-da966d0f32ce.png)

**Comment by Isalight** [comment] 2023-01-08 03:44
The green tone is present with hardware encoding. Not available with x264.

host
![monitor test-nvhost](https://user-images.githubusercontent.com/46701344/211179375-21903a3e-4de8-4cbd-9449-38da7e199517.png)

fix
![monitor test-nvfix](https://user-images.githubusercontent.com/46701344/211179379-55cd2414-954e-4be1-ab63-da49767ec5be.png)

x264
![monitor test-nvfix-x264](https://user-images.githubusercontent.com/46701344/211179383-7c4ae672-217a-4792-8ba3-98fd2323cbde.png)

**Closed** 2023-01-09 02:03 UTC
Labels: fixed, os:Windows:10, os:Windows:11
