### ISSUE TITLE
Error: Unknown Monitor connector type [None]: Please report this to the GitHub issue tracker

### ISSUE THREAD

**Issue by benasanders** [LizardByte/Sunshine#526] opened 2022-12-05 20:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Describe the Bug

While using Wayland, moonlight connects, then immediately disconnects. The following appears in sunshine logs : 
`Error: Unknown Monitor connector type [None]: Please report this to the GitHub issue tracker`

### Expected Behavior

Remote session launches using moonlight client.

### Additional Context

Streaming works under X11. Monitor is connected via USB-C to HDMI cable.

### Host Operating System

Linux

### Operating System Version

ArchLinux updated as of 12/5/2022 (Kernel is v 6.0.10-arch2-1)

### Architecture

64 bit

### Sunshine commit or version

0.15.0-1

### Package

other (not listed)

### GPU Type

Nvidia

### GPU Model

GeForce RTX 2080

### GPU Driver/Mesa Version

525.60.11-2

### Capture Method (Linux Only)

KMS

### Relevant log output

```Shell
Dec 05 12:20:04 HomeServer sunshine[49167]: [2022:12:05:12:20:04]: Info: CLIENT CONNECTED
Dec 05 12:20:04 HomeServer sunshine[49167]: [2022:12:05:12:20:04]: Info: Found display [wayland-0]
Dec 05 12:20:04 HomeServer sunshine[49167]: [2022:12:05:12:20:04]: Info: Found interface: wl_output(5) version 2
Dec 05 12:20:04 HomeServer sunshine[49167]: [2022:12:05:12:20:04]: Info: Found interface: zxdg_output_manager_v1(6) version 3
Dec 05 12:20:04 HomeServer sunshine[49167]: [2022:12:05:12:20:04]: Info: Offset: 0x0
Dec 05 12:20:04 HomeServer sunshine[49167]: [2022:12:05:12:20:04]: Info: Resolution: 1920x1080
Dec 05 12:20:04 HomeServer sunshine[49167]: [2022:12:05:12:20:04]: Info: Name: None-1
Dec 05 12:20:04 HomeServer sunshine[49167]: [2022:12:05:12:20:04]: Info: Found monitor: Toshiba America Info Systems Inc
Dec 05 12:20:04 HomeServer sunshine[49167]: [2022:12:05:12:20:04]: Info: None-1: Toshiba America Info Systems Inc
Dec 05 12:20:04 HomeServer sunshine[49167]: [2022:12:05:12:20:04]: Error: Unknown Monitor connector type [None]: Please report this to the GitHub issue tracker
Dec 05 12:20:04 HomeServer sunshine[49167]: [2022:12:05:12:20:04]: Info: Screencasting with KMS
Dec 05 12:20:04 HomeServer sunshine[49167]: [2022:12:05:12:20:04]: Info: Found monitor for DRM screencasting
Dec 05 12:20:04 HomeServer sunshine[49167]: [2022:12:05:12:20:04]: Info: Color coding [Rec. 601]
Dec 05 12:20:04 HomeServer sunshine[49167]: [2022:12:05:12:20:04]: Info: Color range: [MPEG]
Dec 05 12:20:04 HomeServer sunshine[49167]: [2022:12:05:12:20:04]: Error: Couldn't import RGB Image: 00003004
```

**Comment by ReenigneArcher** [comment] 2022-12-05 21:24
Duplicate of #453

**Closed** 2022-12-05 21:24 UTC
Labels: invalid:duplicate
