### ISSUE TITLE
Starting Sunshine on Ubuntu 23 enables screen reader

### ISSUE THREAD

**Issue by joeldevelops** [LizardByte/Sunshine#1982] opened 2024-01-05 09:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

There are actually two issues happening right now in Ubuntu 23.10:
- Starting sunshine (`systemctl -u start sunshine`) causes the screenreader to turn on, and opens the Ubuntu "Getting Started" application and [Hidemari](https://github.com/jeffshee/hidamari)
- When I restart my PC, sunshine does not start (`sudo systemctl --user enable sunshine`)

## Opening Sunshine after a fresh boot

When starting my PC and looking to stream, the service has died. Running `systemctl --user status sunshine` shows the following:
![image](https://github.com/LizardByte/Sunshine/assets/19559133/73c5f660-152d-4c10-b657-0bfbdf0eb8cb)

As you can see, the service is enabled, and so should be starting up when I boot the PC. I'm hoping to stream from the PC remotely while I'm away in the future. But for now, starting the service manually is fine.

When I start up the service, several things open at once and the screen reader turns on:
![image](https://github.com/LizardByte/Sunshine/assets/19559133/5f4c9122-dbc0-497d-80ed-31d970216e56)

The screen reader usually turns off with a couple times of pressing: Alt + Super (Windows Key) + S, and the two applications can be closed easily.

Expecting that something has gone wrong with the service, I check the logs:
- `journalctl -u sunshine(.service)`: No entries
- `systemctl --user status -l sunshine`: 
```
● sunshine.service - Sunshine is a self-hosted game stream host for Moonlight.
     Loaded: loaded (/usr/lib/systemd/user/sunshine.service; enabled; preset: enabled)
     Active: active (running) since Fri 2024-01-05 10:00:45 CET; 4min 43s ago
   Main PID: 6600 (sunshine)
      Tasks: 17 (limit: 38333)
     Memory: 152.8M
        CPU: 1.419s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/sunshine.service
             └─6600 /usr/bin/sunshine

Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info: // Testing for available encoders, this may generate errors. You can safe>
Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info:
Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info: // Ignore any errors mentioned above, they are not relevant. //
Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info:
Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info: Found H.264 encoder: h264_nvenc [nvenc]
Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info: Found HEVC encoder: hevc_nvenc [nvenc]
Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info: Found AV1 encoder: av1_nvenc [nvenc]
Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info: Adding avahi service Sunshine
Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info: Configuration UI available at [https://localhost:47990]
Jan 05 10:00:48 Ghosty sunshine[6600]: [2024:01:05:10:00:48]: Info: Avahi service Sunshine successfully established.
```

The odd thing is that everything else seems to work just fine when streaming, outside of some lag that I'm sure has to do with my settings. The important thing here is that I'm able to have sunshine start on system boot so I can do Wake on Lan in the future.

### Expected Behavior

- App starts without starting other applications/managing screen reader
- App starts on system boot

### Additional Context

Here is my system info:
```
# System Details Report
---

## Report details
- **Date generated:**                              2024-01-05 10:07:44

## Hardware Information:
- **Hardware Model:**                              ASRock B450M Pro4
- **Memory:**                                      32.0 GiB
- **Processor:**                                   AMD Ryzen™ 7 2700X × 16
- **Graphics:**                                    NVIDIA GeForce RTX™ 4060 Ti
- **Disk Capacity:**                               1.0 TB

## Software Information:
- **Firmware Version:**                            P5.70
- **OS Name:**                                     Ubuntu 23.10
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.1
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.5.0-14-generic
```
Additional info about the CPU:
```
*-cpu
          product: AMD Ryzen 7 2700X Eight-Core Processor
          vendor: Advanced Micro Devices [AMD]
          physical id: 1
          bus info: cpu@0
          version: 23.8.2
          size: 2124MHz
          capacity: 3700MHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp x86-64 constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca sev sev_es cpufreq
          configuration: microcode=134251021
```

And the graphics card:
```
  *-display
       description: VGA compatible controller
       product: AD106 [GeForce RTX 4060 Ti 16GB]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:06:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:96 memory:fb000000-fbffffff memory:d0000000-dfffffff memory:e0000000-e1ffffff ioport:e000(size=128) memory:c0000-dffff
  *-graphics
       product: EFI VGA
       physical id: 1
       logical name: /dev/fb0
       capabilities: fb
       configuration: depth=32 resolution=1024,768
```

### Host Operating System

Linux

### Operating System Version

Ubuntu 23.10

### Architecture

64 bit

### Sunshine commit or version

v0.21.0

### Package

Linux - AppImage

### GPU Type

Nvidia

### GPU Model

NVIDIA GeForce RTX™ 4060 Ti

### GPU Driver/Mesa Version

535.129.03

### Capture Method (Linux Only)

Autodetect

### Config

```Shell
qp = 40
min_threads = 5
nvenc_preset = 5
encoder = nvenc
output_name = 5
fec_percentage = 40
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    1920x1200
]
sw_preset = veryfast
```

### Relevant log output

```shell
● sunshine.service - Sunshine is a self-hosted game stream host for Moonlight.
     Loaded: loaded (/usr/lib/systemd/user/sunshine.service; enabled; preset: enabled)
     Active: active (running) since Fri 2024-01-05 10:00:45 CET; 21min ago
   Main PID: 6600 (sunshine)
      Tasks: 17 (limit: 38333)
     Memory: 155.5M
        CPU: 2.109s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/sunshine.service
             └─6600 /usr/bin/sunshine

Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info:
Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info: // Ignore any errors mentioned above, they are not relevant. //
Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info:
Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info: Found H.264 encoder: h264_nvenc [nvenc]
Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info: Found HEVC encoder: hevc_nvenc [nvenc]
Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info: Found AV1 encoder: av1_nvenc [nvenc]
Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info: Adding avahi service Sunshine
Jan 05 10:00:47 Ghosty sunshine[6600]: [2024:01:05:10:00:47]: Info: Configuration UI available at [https://localhost:47990]
Jan 05 10:00:48 Ghosty sunshine[6600]: [2024:01:05:10:00:48]: Info: Avahi service Sunshine successfully established.
```

**Comment by ReenigneArcher** [comment] 2024-01-05 14:18
Duplicate of #1303

**Closed** 2024-01-05 14:18 UTC
