### ISSUE TITLE
Moonlight Server 20.0 says there's update available, even when running the latest (very! small issue)

### ISSUE THREAD

**Issue by accessiblepixel** [LizardByte/Sunshine#1461] opened 2023-07-20 21:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [ ] This issue is present in the nightly release

### Describe the Bug

In the main interface of sunshine, it will say "A new stable version is available" and shows version 0.20.0 despite that I'm already running 0.20.0.

It's an incredibly small issue, but perhaps there's an issue with how it detects versions and sends that information online to check for updates?

I checked through other issues to see if it had been mentioned, although have not tried the nightly release since I would imagine that would check a different list for it's updates anyway.

I absolutely love the work you've done on Sunshine and I'm reporting this in the off-chance it's something that was missed.

Thank you!

Kind regards.

### Expected Behavior

If you're running the latest version it should say that there's not an update available.

### Additional Context

In the (highly unlikely?) you need something I haven't provided, please let me know and I'll provide it. :)

### Host Operating System

Windows

### Operating System Version

10

### Architecture

64 bit

### Sunshine commit or version

20.0.0

### Package

Windows - installer

### GPU Type

n/a

### GPU Model

Not relevant?

### GPU Driver/Mesa Version

Not Relevent?

### Config

```Shell
Not relevant?
```

### Relevant log output

```shell
Not relevant?
```
N.B: I did not test in the nighly version since that probably has a different update check, but I could not submit a report unless I ticked that option (since there was no option to say no and provide context) although now I have gone back and edited it since I put the wrong architecture, I have unticked that box

**Comment by Hawxxer** [comment] 2023-07-20 22:46
Commit #1358 I guess

**Comment by ReenigneArcher** [comment] 2023-07-20 23:58
Duplicate of #1387

**Closed** 2023-07-20 23:59 UTC

**Comment by accessiblepixel** [comment] 2023-07-21 00:42
Thank you! I apologise I'm not very good at using github's features (since it didn't turn up in an issue search). Glad it's already known about and fixed for next release too :) 

Be well :)
