### ISSUE TITLE
Audio distorted when using 5.1/7.1 streaming

### ISSUE THREAD

**Issue by KarlVogel** [LizardByte/Sunshine#220] opened 2022-06-21 08:19 UTC
### Describe the Bug

When audio configuration in Moonlight is set to 5.1 or 7.1 surround, audio is distorted. Using the stereo settings, audio is fine.

### Expected Behavior

Audio shouldn't distort.

### Additional Context

Sunshine is running on a Fedora 35 host, which uses pipewire for audio. Tested with 2 streaming clients, one laptop running fedora 35 using the moonlight-qt client and one nVidia Shield using the android moonlight client. Issue is present with both clients.

Pipewire version: pipewire-0.3.51-2.fc35.x86_64

### Sunshine Host Operating System and Version

Fedora 35

### Architecture

x86_64

### Sunshine Version

nightly

### GPU Type

AMD

### GPU Model

6900XT

### GPU Driver/Mesa Version

 Mesa Gallium driver 21.3.8 for AMD Radeon RX 6900 XT (SIENNA_CICHLID, DRM 3.44.0,, 5.17.13-200.fc35.x86_64, LLVM 13.0.0)

### Capture Method (Linux Only)

Pipewire/KMS

**Comment by KuleRucket** [comment] 2022-06-21 09:05
Sounds like a duplicate of #168, which will be fixed in the next pipewire release.

**Comment by KarlVogel** [comment] 2022-06-21 10:07
Saw that issue but thought the problem was in 0.3.52, while this is 0.3.51. Audio also works fine in stereo mode, but will see if I can check with the fixed pipewire release.

**Comment by istori1** [comment] 2022-06-21 10:52
Did you build from source or installed the RPM package?

**Comment by KarlVogel** [comment] 2022-06-21 10:59
Sunshine I build from source, pipewire just the RPM.

**Closed** 2022-06-21 13:16 UTC
Labels: invalid:duplicate, os:Linux:Fedora
