### ISSUE TITLE
Dualsense touchpad is read as 5 different inputs at the same time

### ISSUE THREAD

**Issue by FlebsyGit** [LizardByte/Sunshine#1064] opened 2023-03-24 05:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

When pressing the Dualsense touchpad (when DS4 is being emulated) the Dualsense touchpad also presses 5 other inputs at the same time. Steam Input is disabled. The same issue occurs when emulating a 360 controller. Using a DS4/DS5 controller is basically unusable with Sunshine, as most new games require touchpad input for maps, etc.

Image showing holding down the touchpad results in 5 inputs: [https://i.imgur.com/UV0AVuW.png](https://i.imgur.com/UV0AVuW.png)

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

32 bit

### Sunshine commit or version

0.18.4

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

3080

### GPU Driver/Mesa Version

531.29

### Config

```Shell
origin_pin_allowed = lan
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3860x2160,
    3840x1600
]
nv_coder = auto
gamepad = x360
vt_coder = auto
amd_rc = vbr_latency
hevc_mode = 0
nv_rc = cbr
nv_tune = ull
sunshine_name = Sunshine
amd_coder = auto
upnp = disabled
nv_preset = p4
min_log_level = 1
vt_realtime = enabled
key_rightalt_to_key_win = disabled
fps = [10,30,60,90,120]
vt_software = auto
origin_web_ui_allowed = lan
amd_quality = balanced
dwmflush = enabled
```

### Relevant log output

```shell
n/a
```

**Comment by cgutman** [comment] 2023-05-28 04:20
I think this is not a Sunshine issue. The spurious inputs are most likely coming from the client. Due to changes in DualSense firmware and different gamepad implementations, some Moonlight clients may misinterpret DualSense touch input as button input and cause this issue.

**Comment by cgutman** [comment] 2023-07-10 00:03
Closing since this is confirmed to be a Moonlight bug which is already fixed in the latest dev builds.

**Closed by cgutman** 2023-07-10 00:03 UTC
