### ISSUE TITLE
Temporary fix if someone is having problems in Arch Linux new miniupnpc update

### ISSUE THREAD

**Issue by lvgvspe** [LizardByte/Sunshine#2789] opened 2024-07-01 16:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

I'm too lazy to test

### Describe the Bug

After Arch Linux updated miniupnpc to 2.2.8-1, the service returned an error:
`jul 01 13:38:38 sunshine[2342]: /usr/bin/sunshine: error while loading shared libraries: libminiupnpc.so.17: cannot open shared object file: No such file or directory`

But I found a temporary solution from an issue on zerotier-one, just create a symlink from the updated version as so:
`sudo ln -s /usr/lib/libminiupnpc.so.18 /usr/lib/libminiupnpc.so.17`

Just trying to help if someone end up with this error and don't know what to do.

### Expected Behavior

The service should appear as "running" on systemd status, but appear as "crashed".

### Additional Context

Bug happened after Arch Linux updated miniupnpc to 2.2.8-1

### Host Operating System

Linux

### Operating System Version

EndeavourOS

### Architecture

64 bit

### Sunshine commit or version

0.23.1

### Package

Linux - AUR (Third Party)

### GPU Type

AMD

### GPU Model

Radeon VEGA 7

### GPU Driver/Mesa Version

24.1.2-1

### Capture Method

X11 (Linux)

### Config

```Shell
channels = 4
```

### Relevant log output

```shell
jul 01 13:38:38 sunshine[2342]: /usr/bin/sunshine: error while loading shared libraries: libminiupnpc.so.17: cannot open shared object file: No such file or directory
```

**Comment by ReenigneArcher** [comment] 2024-07-01 17:08
That fix likely won't help at all when the code actually tries to call the functions.

Anyway, this has already been fixed.

Duplicate of #2775 
Duplicate of #2782 
Duplicate of #2746

**Closed by ReenigneArcher** 2024-07-01 17:08 UTC
