### ISSUE TITLE
Rendering issues when small changes to image occur

### ISSUE THREAD

**Issue by jmyoung** [LizardByte/Sunshine#615] opened 2022-12-23 10:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Bit of an odd issue, sorry if I can't describe it completely clearly, but it's 100% repeatable.  I'm putting it here because this problem happens with Sunshine, and does not happen with Gamestream, with all other components being the same.

The Playnite game launcher (full-screen), when run through Sunshine exhibits some unusual behaviour.  If you use keys (not moving the mouse) to move across the categories on the top of the screen, they move as expected (with each category highlighting in orange) on the actual computer monitor, but the output stream does not show the change to display.  If you wait approximately 10 seconds, the output stream snaps to consistency with what's on the computer monitor.

Interestingly, if Playnite is in the process of updating a library, so there's a spinning wheel on the bottom right of the screen, the above behaviour doesn't happen.  It only happens when the only display change happening is the highlighted category, or navigating the menus.  Scrolling through game thumbnails doesn't cause this (likely because of the large amount of pixels being changed?).

I suspected this might have been a DwmFlush issue, so I've tried toggling that.  No effect.  I've tried various other encoder tweaks, also to no effect.

To be clear, this problem does not happen when using either Gamestream or when using Steam Link.  This only happens when using Sunshine.  And in addition, the actual computer monitor displays state correctly, it's the stream that does not.

I'm not able to replicate this with any other application, only Playnite, but I can replicate this with Playnite 100% of the time.  I suspect that Playnite may not be sending some window update or something similar, and so Sunshine doesn't "know" the window has been updated until it hits a key frame in the stream and then sends a full frame, causing the output stream to update.  But that's pure conjecture.

### Expected Behavior

Expect that stream output corresponds 100% to output on the associated computer monitor.

### Additional Context

Using latest version of Playnite (happens both with hardware acceleration on and off), and latest version of Sunshine.  Operating system is Windows 11 22H2, nVidia driver version is 526.47, client is nVidia Shield 2017 running current release of Moonlight.

nVidia Control Panel settings have vSync set to default, monitor is set to fixed refresh, 4k60hz.

### Host Operating System

Windows

### Operating System Version

Windows 11 22H2

### Architecture

64 bit

### Sunshine commit or version

v0.16.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

EVGA Geforce RTX 3080

### GPU Driver/Mesa Version

526.47

**Comment by ReenigneArcher** [comment] 2022-12-23 11:47
You checked that you confirmed the issue is present in the nightly release, but I'm 99% certain the issue you describe has already been fixed. Please test the nightly version and report back.

**Comment by jwkim930** [comment] 2022-12-23 12:53
Glad to find someone having a similar issue as mine! And no, it’s still not fixed as of 0.16.0 in my system (Windows 11 Host, iPad client, NVENC encoding).

In my case, I tested using touchscreen input, and noted that exactly 2 frames get “queued up” before getting sent to my device. That is, when I instantly move the mouse cursor in the screen by using the touchscreen, the cursor is always at where I tapped 2 taps before (while it is correct on the host display). And this happens regardless of the input method (I can notice it in typing too, for example).

**Comment by ReenigneArcher** [comment] 2022-12-23 14:05
v0.16.0 is not the nightly release -> https://github.com/LizardByte/Sunshine/releases/tag/nightly-dev

Check it and let me know if it resolves the issue.

**Comment by jwkim930** [comment] 2022-12-23 14:36
> v0.16.0 is not the nightly release -> https://github.com/LizardByte/Sunshine/releases/tag/nightly-dev
> 
> Check it and let me know if it resolves the issue.

It seems like the issue is gone on that version. Thanks for your help!

**Comment by ReenigneArcher** [comment] 2022-12-23 14:46
Duplicate of #122

**Closed by ReenigneArcher** 2022-12-23 14:46 UTC
Labels: fixed, invalid:duplicate
