### ISSUE TITLE
Occasional poor quality when streamed video is static

### ISSUE THREAD

**Issue by b5mith** [LizardByte/Sunshine#717] opened 2023-01-06 11:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I'm not entirely sure how to describe this, apologies in advance.

To reproduce the issue, open Moonlight and connect to Desktop. 
Scroll through a text document in a PDF viewer quickly enough to see frames with very poor quality, then stop completely, hand off the mouse so that there are no more changes.
If you time it right, you should end up with a very poor quality, persistent frame that does not correct itself until you move the mouse again.

I had to lower the bitrate from 20Mb/s to 18Mb/s when I switched from Gamestream to Sunshine, in spite of having 1Gb wired LAN between laptop and desktop. At 20Mb/s I get bitrate warnings and stutter.

![Capture](https://user-images.githubusercontent.com/8345889/211003504-d49ea508-85e4-468d-a1e7-f73c9507f8f0.JPG)
![Capture2](https://user-images.githubusercontent.com/8345889/211005375-58e84e61-aaf5-485b-a6ea-a1e4fb7030f6.JPG)

### Expected Behavior

If a received frame is poor quality, expect a new frame to be sent even if the video being streamed is static.

### Host Operating System

Windows

### Operating System Version

Windows 11 Pro Version 10.0.22621 Build 22621

### Architecture

64 bit

### Sunshine commit or version

2023-01-06T01:00:08Z - effa98f

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

GeForce RTX 2070

### GPU Driver/Mesa Version

527.57

**Comment by cgutman** [comment] 2023-01-07 00:37
This is caused by our variable rate encoding. Because we aren't continuing to encode frames when the desktop is static, the encoder doesn't have the opportunity to fill in additional detail in the following frames.

We plan to move to fixed rate encoding for v0.18 which will fix this issue.

**Comment by apoklyps3** [comment] 2023-01-07 07:58
I noticed this in too in steam big picture mode.
very blurry, glad to hear it's getting fixed.
keep it going guys. nvidia's gamestream won't be missed.

**Comment by b5mith** [comment] 2023-01-12 06:56
> This is caused by our variable rate encoding. Because we aren't continuing to encode frames when the desktop is static, the encoder doesn't have the opportunity to fill in additional detail in the following frames.
> 
> We plan to move to fixed rate encoding for v0.18 which will fix this issue.

Thank you for the fix in #754, cgutman. Much appreciated.

**Comment by ReenigneArcher** [comment] 2023-01-12 13:31
Please don't close issues until the issue is fixed in a stable release.

**Closed** 2023-01-30 03:26 UTC
Labels: fixed

**Comment by crappy624** [comment] 2023-02-12 14:58
Hello,
the issue persists when there is a dynamic Image with Static parts. For example a Game with a Static Text for a Mission objective on the Screen.
Should i Open a different issue ?

**Comment by ReenigneArcher** [comment] 2023-02-12 15:27
> Hello, the issue persists when there is a dynamic Image with Static parts. For example a Game with a Static Text for a Mission objective on the Screen. Should i Open a different issue ?

No... discuss with us on Discord.
