### ISSUE TITLE
Segmentation fault on Apple M1/M2

### ISSUE THREAD

**Issue by jcrowthe** [LizardByte/Sunshine#1528] opened 2023-08-13 04:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

A segmentation fault occurs on a vanilla install of 0.20.0. I have tried this on both a M2 Mac Mini and a M1 Macbook Pro.
```
~% sunshine
[2023:08:12:21:39:15]: Info: Sunshine version: 0.20.0
[2023:08:12:21:39:15]: Info: system_tray() is not yet implemented for this platform.
[2023:08:12:21:39:15]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:08:12:21:39:15]: Info: Trying encoder [videotoolbox]
[2023:08:12:21:39:15]: Info: SDR color coding [Rec. 601]
[2023:08:12:21:39:15]: Info: Color range: [JPEG]
zsh: segmentation fault  sunshine
```

### Expected Behavior

I expected Sunshine to start normally.

### Host Operating System

macOS

### Operating System Version

macOS Ventura 13.5

### Architecture

arm

### Sunshine commit or version

0.20.0

### Package

macOS - Portfile

### GPU Type

n/a

### GPU Model

confirmed on both M2 and M1 Pro

### GPU Driver/Mesa Version

included in Ventura

### Config

```Shell
Default config used
```

### Relevant log output

```shell
Current executable set to 'sunshine' (arm64).
(lldb) run
Process 15983 launched: '/opt/local/bin/sunshine' (arm64)
[2023:08:12:22:33:44]: Info: Sunshine version: 0.20.0
[2023:08:12:22:33:44]: Info: system_tray() is not yet implemented for this platform.
[2023:08:12:22:33:44]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:08:12:22:33:44]: Info: Trying encoder [videotoolbox]
[2023:08:12:22:33:44]: Info: SDR color coding [Rec. 601]
[2023:08:12:22:33:44]: Info: Color range: [JPEG]
2023-08-12 22:33:44.599478-0600 sunshine[15983:3355592] [default] 0 is not a valid connection ID.
2023-08-12 22:33:45.421994-0600 sunshine[15983:3355592] [] CMIO_DAL_PlugInManagement.cpp:880:CreatePlugIn Could not find plugin with kCMIOHardwarePlugInTypeID
Process 15983 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x12b004044)
    frame #0: 0x000000019cfd2730 libsystem_platform.dylib`_platform_memmove + 144
libsystem_platform.dylib`:
->  0x19cfd2730 <+144>: ldnp   q2, q3, [x1]
    0x19cfd2734 <+148>: sub    x5, x3, x0
    0x19cfd2738 <+152>: add    x1, x1, x5
    0x19cfd273c <+156>: ldnp   q0, q1, [x1]
Target 0: (sunshine) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x12b004044)
  * frame #0: 0x000000019cfd2730 libsystem_platform.dylib`_platform_memmove + 144
    frame #1: 0x000000010011c398 sunshine`image_copy_plane + 104
    frame #2: 0x000000010011c654 sunshine`image_copy + 376
    frame #3: 0x000000010011c4b4 sunshine`av_image_copy + 84
    frame #4: 0x0000000100117ea4 sunshine`av_frame_copy + 596
    frame #5: 0x00000001001178ac sunshine`av_frame_ref + 516
    frame #6: 0x00000001000ff48c sunshine`avcodec_send_frame + 488
    frame #7: 0x00000001000be07c sunshine`video::encode(long long, video::session_t&, AVFrame*, std::__1::shared_ptr<safe::post_t<safe::queue_t<std::__1::unique_ptr<video::packet_raw_t, std::__1::default_delete<video::packet_raw_t> > > > >&, void*, std::__1::optional<std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > > const&) + 84
    frame #8: 0x00000001000c2564 sunshine`video::validate_config(std::__1::shared_ptr<platf::display_t>&, video::encoder_t const&, video::config_t const&) + 564
    frame #9: 0x00000001000c282c sunshine`video::validate_encoder(video::encoder_t&, bool) + 356
    frame #10: 0x00000001000c3858 sunshine`video::probe_encoders() + 2716
    frame #11: 0x00000001000205f0 sunshine`main + 2416
    frame #12: 0x000000019cc4bf28 dyld`start + 2236
```

**Comment by ReenigneArcher** [comment] 2023-08-13 20:00
Duplicate of #1348

**Closed** 2023-08-13 20:01 UTC
Labels: invalid:duplicate
