### ISSUE TITLE
Reboot without ugh!!

### ISSUE THREAD

**Issue by jriker1** [LizardByte/Sunshine#1810] opened 2023-11-02 20:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I just updated from a nightly to 0.21.0.  After it was installed it just rebooted my system.  Never asked, never had an option, was doing some rendering and poof.  Maybe I missed it somewhere in the installer but really need an option to reboot now or later.

### Host Operating System

Windows

### Operating System Version

Win 11

### Architecture

64 bit

### Sunshine commit or version

0.21.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

4090

### GPU Driver/Mesa Version

latest

### Config

```Shell
not relevant
```

### Relevant log output

```shell
not relevant
```

**Comment by ReenigneArcher** [comment] 2023-11-02 22:54
Duplicate of #1805

**Closed by ReenigneArcher** 2023-11-02 22:54 UTC
