### ISSUE TITLE
Sunshine error at launch 

### ISSUE THREAD

**Issue by Jerophoto** [LizardByte/Sunshine#1446] opened 2023-07-13 10:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I just installed Sunshine on my Windows 10 desktop but when i open it i get this message: Terminate called after throwing an instance of 'std::range_error'
  what():  wstring_convert::from_bytes

And suddenly stops.

### Host Operating System

Docker

### Operating System Version

Windows 10

### Architecture

64 bit

### Sunshine commit or version

0.20.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

Quaddro M 4000

### GPU Driver/Mesa Version

536.25

### Config

```Shell
OS Name	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	JEDAIL
System Manufacturer	System manufacturer
System Model	System Product Name
System Type	x64-based PC
System SKU	SKU
Processor	Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz, 4200 Mhz, 4 Core(s), 4 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 3801, 14.03.2018
SMBIOS Version	3.0
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	ASUSTeK COMPUTER INC.
BaseBoard Product	MAXIMUS VIII GENE
BaseBoard Version	Rev 1.xx
Platform Role	Desktop
Secure Boot State	Unsupported
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume7
Locale	Switzerland
Hardware Abstraction Layer	Version = "10.0.19041.2728"
Username	JEDAIL\Jérôme
Time Zone	W. Europe Summer Time
Installed Physical Memory (RAM)	32,0 GB
Total Physical Memory	31,9 GB
Available Physical Memory	18,2 GB
Total Virtual Memory	63,9 GB
Available Virtual Memory	46,1 GB
Page File Space	32,0 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualisation-based security	Not enabled
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and the device is not Modern Standby, Un-allowed DMA-capable bus/device(s) detected, TPM is not usable
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualisation Enabled in Firmware	No
Hyper-V - Data Execution Protection	Yes
```

### Relevant log output

```shell
Terminate called after throwing an instance of 'std::range_error'
  what():  wstring_convert::from_bytes
```

**Comment by Nonary** [comment] 2023-07-25 14:01
You have invalid configuration in your sunshine.conf file, please upload it.

**Comment by cgutman** [comment] 2023-08-10 00:19
I think this is a duplicate of #475. Please try this build: https://github.com/LizardByte/Sunshine/suites/14939820346/artifacts/851805098 (must be signed in with GitHub account)

**Comment by jmiguec** [comment] 2023-10-09 18:23
> I think this is a duplicate of #475. Please try this build: https://github.com/LizardByte/Sunshine/suites/14939820346/artifacts/851805098 (must be signed in with GitHub account)

First time I'm installing Sunshine and I'm having the same problem. In my case, my local installation path also contains spaces ' ' and characters like 'ã'. In any version I try to install I've the same sympthons, therefore I'm not able to install any Sunshine version.

**Comment by 3856887** [comment] 2023-12-21 10:42
I encountered the same problem, my version of sunshine is 0.21.0, Windows11, the system language is Chinese (simplified), but my problem is very strange: My sunshine started normally and displayed an icon in the lower right corner of the desktop, but after clicking the icon and then clicking the open sunshine button, the program would crash, then I manually ran the exe and exported the log. The result is "terminate called after throwing an instance of 'std::range_error'
what(): wstring_convert::from_bytes ". In addition, there is a weird thing: if I open a browser and manually type in the webUI, the web site will open and I can use the default Desktop stream, but the application involving other startup applications (such as steam big pic) will still crash in the same way.

**Comment by ByronLeeeee** [comment] 2024-01-16 12:50
> I encountered the same problem, my version of sunshine is 0.21.0, Windows11, the system language is Chinese (simplified), but my problem is very strange: My sunshine started normally and displayed an icon in the lower right corner of the desktop, but after clicking the icon and then clicking the open sunshine button, the program would crash, then I manually ran the exe and exported the log. The result is "terminate called after throwing an instance of 'std::range_error' what(): wstring_convert::from_bytes ". In addition, there is a weird thing: if I open a browser and manually type in the webUI, the web site will open and I can use the default Desktop stream, but the application involving other startup applications (such as steam big pic) will still crash in the same way.

@3856887 

可以依次通过Win+S输入【区域】并进入区域设置，点击【管理】标签页，然后点击【更改系统区域设置】，勾选【Beta版：使用Unicode UTF-8 提供全球语言支持】，重启电脑即可成功打开。

（The following is the English version）
You can sequentially enter "Region" through Win+S and access the region settings. Click on the "Manage" tab, then click on "Change system locale." Check the option for "Beta: Use Unicode UTF-8 for worldwide language support," and restart your computer to successfully open it.

**Comment by Konstantin749** [comment] 2024-01-24 13:29
> > I encountered the same problem, my version of sunshine is 0.21.0, Windows11, the system language is Chinese (simplified), but my problem is very strange: My sunshine started normally and displayed an icon in the lower right corner of the desktop, but after clicking the icon and then clicking the open sunshine button, the program would crash, then I manually ran the exe and exported the log. The result is "terminate called after throwing an instance of 'std::range_error' what(): wstring_convert::from_bytes ". In addition, there is a weird thing: if I open a browser and manually type in the webUI, the web site will open and I can use the default Desktop stream, but the application involving other startup applications (such as steam big pic) will still crash in the same way.
> 
> @3856887
> 
> 可以依次通过Win+S输入【区域】并进入区域设置，点击【管理】标签页，然后点击【更改系统区域设置】，勾选【Beta版：使用Unicode UTF-8 提供全球语言支持】，重启电脑即可成功打开。
> 
> （The following is the English version） You can sequentially enter "Region" through Win+S and access the region settings. Click on the "Manage" tab, then click on "Change system locale." Check the option for "Beta: Use Unicode UTF-8 for worldwide language support," and restart your computer to successfully open it.

Thank you!

**Comment by ZReplicant** [comment] 2024-02-09 06:58
> > I encountered the same problem, my version of sunshine is 0.21.0, Windows11, the system language is Chinese (simplified), but my problem is very strange: My sunshine started normally and displayed an icon in the lower right corner of the desktop, but after clicking the icon and then clicking the open sunshine button, the program would crash, then I manually ran the exe and exported the log. The result is "terminate called after throwing an instance of 'std::range_error' what(): wstring_convert::from_bytes ". In addition, there is a weird thing: if I open a browser and manually type in the webUI, the web site will open and I can use the default Desktop stream, but the application involving other startup applications (such as steam big pic) will still crash in the same way.
> 
> @3856887
> 
> 可以依次通过Win+S输入【区域】并进入区域设置，点击【管理】标签页，然后点击【更改系统区域设置】，勾选【Beta版：使用Unicode UTF-8 提供全球语言支持】，重启电脑即可成功打开。
> 
> （The following is the English version） You can sequentially enter "Region" through Win+S and access the region settings. Click on the "Manage" tab, then click on "Change system locale." Check the option for "Beta: Use Unicode UTF-8 for worldwide language support," and restart your computer to successfully open it.

As expected, this also works if the system language is cyrillic (Russian). Thanks, that problem has bugged me for a month!

**Comment by Konstantin749** [comment] 2024-02-09 16:06
But devs should not close this issue because that option in Windows breaks other apps. For example all text in MSI Afterburner looked like this: "???????????????????"

**Comment by ByronLeeeee** [comment] 2024-02-11 14:25
> But devs should not close this issue because that option in Windows breaks other apps. For example all text in MSI Afterburner looked like this: "???????????????????"

Yes, this feature, as indicated by its prompt, is a Beta feature. It converts characters without specified encoding to UTF-8 encoding, which may result in many old files becoming garbled and may also cause many legacy applications to display garbled text. Generally, it should not be opened casually... Therefore, the simplest solution is to submit a PR to make Sunshine default to UTF-8 encoding, which will resolve the Bug of software failure caused by non-English system languages.

**Comment by cgutman** [comment] 2024-02-11 20:00
We are [defaulting to UTF-8](https://github.com/LizardByte/Sunshine/pull/1517) and generally do take care to use Unicode-compatible APIs in Sunshine. I'm not completely sure what's going on, but I will try to install a Russian or Chinese version of Windows in a VM and see if I can debug it.

**Comment by cgutman** [comment] 2024-02-11 22:46
Please test this build: https://github.com/LizardByte/Sunshine/actions/runs/7864940019/artifacts/1236941310

**Closed** 2024-02-13 00:43 UTC
