### ISSUE TITLE
unabel to start from macos

### ISSUE THREAD

**Issue by iMonZ** [LizardByte/Sunshine#1658] opened 2023-09-20 01:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Starting from macOS Sonoma gives this error

### Host Operating System

macOS

### Operating System Version

14.0 (23A339)

### Architecture

arm

### Sunshine commit or version

latest

### Package

macOS - dmg

### GPU Type

n/a

### GPU Model

-

### GPU Driver/Mesa Version

-

### Config

```Shell
-
```

### Relevant log output

```shell
dyld[81341]: Library not loaded: /usr/local/opt/boost/lib/libboost_locale-mt.dylib
  Referenced from: <FC3A383B-8AB9-3F20-9889-8C46F15D02DB> /Volumes/Sunshine/usr/bin/sunshine-0.20.0
  Reason: tried: '/usr/local/opt/boost/lib/libboost_locale-mt.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/boost/lib/libboost_locale-mt.dylib' (no such file), '/usr/local/opt/boost/lib/libboost_locale-mt.dylib' (no such file), '/usr/local/lib/libboost_locale-mt.dylib' (no such file), '/usr/lib/libboost_locale-mt.dylib' (no such file, not in dyld cache)
fish: Job 1, '/Volumes/Sunshine/usr/bin/sunsh…' terminated by signal SIGABRT (Abort)
```

**Comment by ReenigneArcher** [comment] 2023-09-20 01:30
Why do you check these boxes?

![image](https://github.com/LizardByte/Sunshine/assets/42013603/18a1be4c-b180-46ba-8a8e-4e8be582ebcf)

Duplicate of #1348

**Closed by ReenigneArcher** 2023-09-20 01:30 UTC

**Comment by iMonZ** [comment] 2023-09-20 01:37
> Why do you check these boxes?
> 
> ![image](https://user-images.githubusercontent.com/42013603/269132409-18a1be4c-b180-46ba-8a8e-4e8be582ebcf.png)
> 
> Duplicate of #1348

That’s a whole different issue with different log.
Also I’m not using macports I’m using the official dmg way. Could you please reopen the issue?

**Comment by ReenigneArcher** [comment] 2023-09-20 02:01
dmg is a Duplicate of #186
