### ISSUE TITLE
Unknown Monitor connector type [Virtual]

### ISSUE THREAD

**Issue by Anti-Iridium** [LizardByte/Sunshine#1713] opened 2023-10-07 06:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

While trying to connect to sunshine, It seems to be having a problem with the fact that the GPU I have is headless. Log contains all relevant information. Please let me know what other information would be useful.

### Additional Context

`xrandr --listmonitors`
> Monitors: 1
 0: +*XWAYLAND0 1920/508x1080/286+0+0  XWAYLAND0

`glxinfo -B`

> name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Radeon Instinct MI25 (vega10, LLVM 15.0.7, DRM 3.49, 6.2.0-34-generic) (0x6860)
    Version: 23.0.4
    Accelerated: yes
    Video memory: 16384MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 15997 MB, largest block: 15997 MB
    VBO free aux. memory - total: 15987 MB, largest block: 15987 MB
    Texture free memory - total: 15997 MB, largest block: 15997 MB
    Texture free aux. memory - total: 15987 MB, largest block: 15987 MB
    Renderbuffer free memory - total: 15997 MB, largest block: 15997 MB
    Renderbuffer free aux. memory - total: 15987 MB, largest block: 15987 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 16384 MB
    Total available memory: 32426 MB
    Currently available dedicated video memory: 15997 MB
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon Instinct MI25 (vega10, LLVM 15.0.7, DRM 3.49, 6.2.0-34-generic)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.0.4-0ubuntu1~22.04.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

### Host Operating System

Linux

### Operating System Version

22.04

### Architecture

64 bit

### Sunshine commit or version

0.20

### Package

Linux - deb

### GPU Type

AMD

### GPU Model

AMD Radeon Instinct MI25

### GPU Driver/Mesa Version

Mesa 23.0.4-0ubuntu1~22.04.1

### Config

```Shell
Config file is blank
```

### Relevant log output

```shell
[2023:10:07:01:47:43]: Info: Sunshine version: 0.20.0.9c401f52aa067094c81658ce187cad6838037e69
[2023:10:07:01:47:43]: Error: Couldn't load cuda: -1
[2023:10:07:01:47:43]: Info: Found display [wayland-0]
[2023:10:07:01:47:43]: Info: Found interface: wl_output(4) version 3
[2023:10:07:01:47:43]: Info: Found interface: zxdg_output_manager_v1(5) version 3
[2023:10:07:01:47:43]: Warning: Missing Wayland wire for wlr-export-dmabuf
[2023:10:07:01:47:43]: Error: Couldn't get drm fb for plane [97]: No such device
[2023:10:07:01:47:43]: Info: Found display [wayland-0]
[2023:10:07:01:47:43]: Info: Found display [wayland-0]
[2023:10:07:01:47:43]: Info: Found interface: wl_output(4) version 3
[2023:10:07:01:47:43]: Info: Found interface: zxdg_output_manager_v1(5) version 3
[2023:10:07:01:47:43]: Info: Offset: 0x0
[2023:10:07:01:47:43]: Info: Resolution: 1920x1080
[2023:10:07:01:47:43]: Info: Name: Virtual-1
[2023:10:07:01:47:43]: Info: Found monitor: Unknown Display
[2023:10:07:01:47:43]: Info: Virtual-1: Unknown Display
[2023:10:07:01:47:43]: Error: Unknown Monitor connector type [Virtual]: Please report this to the GitHub issue tracker
[2023:10:07:01:47:43]: Error: Unable to initialize capture method
[2023:10:07:01:47:43]: Error: Platform failed to initialize
```

**Comment by ReenigneArcher** [comment] 2023-10-07 14:18
Duplicate of #347

**Closed** 2023-10-07 14:20 UTC
Labels: invalid:duplicate
