### ISSUE TITLE
Install sunshine on macOS failure 

### ISSUE THREAD

**Issue by mwcodefun** [LizardByte/Sunshine#3139] opened 2024-09-05 08:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

Hello,

I am experiencing an issue with installing Sunshine via Homebrew on macOS. Unfortunately, the installation fails, and I am attaching some of the error logs below for your reference.

### Host Operating System

macOS

### Operating System Version

14.6

### Architecture

64 bit

### Sunshine commit or version

not sure 

### Package

macOS - Homebrew

### GPU Type

Intel

### GPU Model

Amd rx 570

### GPU Driver/Mesa Version

not sure

### Capture Method

None

### Config

```Shell
not need
```

### Relevant log output

```shell
==> Fetching lizardbyte/homebrew/sunshine
==> Cloning https://github.com/LizardByte/Sunshine.git
Updating /Users/ss/Library/Caches/Homebrew/sunshine--git
==> Checking out tag v0.23.1
HEAD is now at 8b21db64 Merge pull request #2388 from LizardByte/nightly
HEAD is now at 8b21db64 Merge pull request #2388 from LizardByte/nightly
Entering 'packaging/linux/flatpak/deps/org.flatpak.Builder.BaseApp'
Entering 'packaging/linux/flatpak/deps/shared-modules'
Entering 'third-party/Simple-Web-Server'
Entering 'third-party/TPCircularBuffer'
Entering 'third-party/ViGEmClient'
Entering 'third-party/build-deps'
Entering 'third-party/googletest'
Entering 'third-party/moonlight-common-c'
Synchronizing submodule url for 'enet'
Entering 'third-party/moonlight-common-c/enet'
Entering 'third-party/nanors'
Entering 'third-party/nv-codec-headers'
Entering 'third-party/nvapi-open-source-sdk'
Entering 'third-party/tray'
Entering 'third-party/wayland-protocols'
Entering 'third-party/wlr-protocols'
/Users/ss/Library/Caches/Homebrew/sunshine--git/packaging/linux/flatpak/deps/org.flatpak.Builder.BaseApp
/Users/ss/Library/Caches/Homebrew/sunshine--git/packaging/linux/flatpak/deps/shared-modules
/Users/ss/Library/Caches/Homebrew/sunshine--git/third-party/Simple-Web-Server
/Users/ss/Library/Caches/Homebrew/sunshine--git/third-party/TPCircularBuffer
/Users/ss/Library/Caches/Homebrew/sunshine--git/third-party/ViGEmClient
/Users/ss/Library/Caches/Homebrew/sunshine--git/third-party/build-deps
/Users/ss/Library/Caches/Homebrew/sunshine--git/third-party/googletest
/Users/ss/Library/Caches/Homebrew/sunshine--git/third-party/moonlight-common-c
/Users/ss/Library/Caches/Homebrew/sunshine--git/third-party/moonlight-common-c/enet
/Users/ss/Library/Caches/Homebrew/sunshine--git/third-party/nanors
/Users/ss/Library/Caches/Homebrew/sunshine--git/third-party/nv-codec-headers
/Users/ss/Library/Caches/Homebrew/sunshine--git/third-party/nvapi-open-source-sdk
/Users/ss/Library/Caches/Homebrew/sunshine--git/third-party/tray
/Users/ss/Library/Caches/Homebrew/sunshine--git/third-party/wayland-protocols
/Users/ss/Library/Caches/Homebrew/sunshine--git/third-party/wlr-protocols
==> Installing sunshine from lizardbyte/homebrew
==> cmake -S . -B build -DBUILD_WERROR=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@3 -DSUNSHINE_ASSETS_DIR=sunshine/assets -DSUNSHI
==> make -j
Last 15 lines from /Users/ss/Library/Logs/Homebrew/sunshine/02.make:
../../../../build/assets/web/assets/Navbar-48ec9d0d.css                       0.07 kB │ gzip:   0.09 kB
../../../../build/assets/web/assets/_plugin-vue_export-helper-cff45802.css  327.59 kB │ gzip:  54.06 kB
../../../../build/assets/web/assets/password-41ebda5b.js                      0.63 kB │ gzip:   0.41 kB
../../../../build/assets/web/assets/welcome-6454da3a.js                       0.66 kB │ gzip:   0.42 kB
../../../../build/assets/web/assets/pin-677ef343.js                           0.81 kB │ gzip:   0.43 kB
../../../../build/assets/web/assets/troubleshooting-76080e6f.js               1.36 kB │ gzip:   0.59 kB
../../../../build/assets/web/assets/ResourceCard-ea4a7cba.js                  1.67 kB │ gzip:   0.64 kB
../../../../build/assets/web/assets/index-1d511c0f.js                         2.06 kB │ gzip:   0.90 kB
../../../../build/assets/web/assets/Navbar-dbaf0800.js                        2.16 kB │ gzip:   0.94 kB
../../../../build/assets/web/assets/config-f4fb6dcb.js                        4.97 kB │ gzip:   2.10 kB
../../../../build/assets/web/assets/apps-966a1e70.js                         85.57 kB │ gzip:  25.93 kB
../../../../build/assets/web/assets/_plugin-vue_export-helper-fe085d29.js   327.84 kB │ gzip: 111.98 kB
✓ built in 1.06s
[ 54%] Built target web-ui
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/lizardbyte/homebrew-homebrew/issues

```

**Comment by ReenigneArcher** [comment] 2024-09-05 12:35
Duplicate of #3098, #3052, #3025, #2780, #2655, #2629, #2369

**Closed by ReenigneArcher** 2024-09-05 12:35 UTC
Labels: os:macOS
