### ISSUE TITLE
Sound is "craking" when streaming to Moonlight.

### ISSUE THREAD

**Issue by Gaeus** [LizardByte/Sunshine#1541] opened 2023-08-15 12:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

The audio is "crakling" as if it was amplified while streaming, the issue happens regardless of the audio output, and regardless of the audio settings (settings the sound quality @44.1mhz doesn't solve the "craking" sound.

### Expected Behavior

Audio should be clear.

### Additional Context

Have been using Sunshine/Moonlight for a year with no issue, the bug persists after a clean reinstallation and several reboots.

The issue persist on multiple clients : Android, Google TV, Ios, Windows (client).

The bug does not seem to be related to Moonlight, since it appears on older client whom I've not updated.

### Host Operating System

Windows

### Operating System Version

11 22H2 22621.2134

### Architecture

64 bit

### Sunshine commit or version

20

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

4070

### GPU Driver/Mesa Version

599

### Config

```Shell
encoder = nvenc
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    2560x1080,
    3440x1440,
    1920x1200,
    3840x2160,
    3840x1600,
    2176x1812,
    2560x1440
]
nv_preset = p1
```

### Relevant log output

```shell
[2023:08:15:14:07:13]: Info: Sunshine version: 0.20.0
[2023:08:15:14:07:13]: Info: Compiling shaders...
[2023:08:15:14:07:13]: Info: System tray created
[2023:08:15:14:07:13]: Info: Compiled shaders
[2023:08:15:14:07:13]: Info: Trying encoder [nvenc]
[2023:08:15:14:07:13]: Info: ddprobe.exe [1] [] returned: 0x00000000
[2023:08:15:14:07:13]: Info: Set GPU preference: 1
[2023:08:15:14:07:14]: Info: 
Device Description : NVIDIA GeForce RTX 4070
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002786
Device Video Mem   : 12026 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16344 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 2560x190
Virtual Desktop    : 4480x1440
[2023:08:15:14:07:14]: Info: Desktop resolution [1920x1080]
[2023:08:15:14:07:14]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:15:14:07:14]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:15:14:07:14]: Info: SDR color coding [Rec. 601]
[2023:08:15:14:07:14]: Info: Color range: [JPEG]
[2023:08:15:14:07:14]: Info: 
Device Description : NVIDIA GeForce RTX 4070
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002786
Device Video Mem   : 12026 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16344 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 2560x190
Virtual Desktop    : 4480x1440
[2023:08:15:14:07:14]: Info: Desktop resolution [1920x1080]
[2023:08:15:14:07:14]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:15:14:07:14]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:15:14:07:14]: Info: SDR color coding [Rec. 601]
[2023:08:15:14:07:14]: Info: Color range: [JPEG]
[2023:08:15:14:07:15]: Info: 
Device Description : NVIDIA GeForce RTX 4070
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002786
Device Video Mem   : 12026 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16344 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 2560x190
Virtual Desktop    : 4480x1440
[2023:08:15:14:07:15]: Info: Desktop resolution [1920x1080]
[2023:08:15:14:07:15]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:15:14:07:15]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:15:14:07:15]: Info: SDR color coding [Rec. 709]
[2023:08:15:14:07:15]: Info: Color range: [JPEG]
[2023:08:15:14:07:15]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:08:15:14:07:15]: Info: 
[2023:08:15:14:07:15]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2023:08:15:14:07:15]: Info: 
[2023:08:15:14:07:15]: Info: Found encoder nvenc: [h264_nvenc, hevc_nvenc]
[2023:08:15:14:07:15]: Info: Configuration UI available at [https://localhost:47990]
[2023:08:15:14:07:15]: Info: Registered Sunshine mDNS service
[2023:08:15:14:07:29]: Info: Trying encoder [nvenc]
[2023:08:15:14:07:29]: Info: 
Device Description : NVIDIA GeForce RTX 4070
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002786
Device Video Mem   : 12026 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16344 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 2560x190
Virtual Desktop    : 4480x1440
[2023:08:15:14:07:29]: Info: Desktop resolution [1920x1080]
[2023:08:15:14:07:29]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:15:14:07:29]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:15:14:07:30]: Info: SDR color coding [Rec. 601]
[2023:08:15:14:07:30]: Info: Color range: [JPEG]
[2023:08:15:14:07:30]: Info: 
Device Description : NVIDIA GeForce RTX 4070
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002786
Device Video Mem   : 12026 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16344 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 2560x190
Virtual Desktop    : 4480x1440
[2023:08:15:14:07:30]: Info: Desktop resolution [1920x1080]
[2023:08:15:14:07:30]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:15:14:07:30]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:15:14:07:30]: Info: SDR color coding [Rec. 601]
[2023:08:15:14:07:30]: Info: Color range: [JPEG]
[2023:08:15:14:07:30]: Info: 
Device Description : NVIDIA GeForce RTX 4070
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002786
Device Video Mem   : 12026 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16344 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 2560x190
Virtual Desktop    : 4480x1440
[2023:08:15:14:07:30]: Info: Desktop resolution [1920x1080]
[2023:08:15:14:07:30]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:15:14:07:30]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:15:14:07:30]: Info: SDR color coding [Rec. 709]
[2023:08:15:14:07:30]: Info: Color range: [JPEG]
[2023:08:15:14:07:31]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:08:15:14:07:31]: Info: 
[2023:08:15:14:07:31]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2023:08:15:14:07:31]: Info: 
[2023:08:15:14:07:31]: Info: Found encoder nvenc: [h264_nvenc, hevc_nvenc]
[2023:08:15:14:07:31]: Info: Executing [Desktop]
[2023:08:15:14:07:31]: Info: CLIENT CONNECTED
[2023:08:15:14:07:31]: Info: 
Device Description : NVIDIA GeForce RTX 4070
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002786
Device Video Mem   : 12026 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16344 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1440
Offset             : 0x0
Virtual Desktop    : 4480x1440
[2023:08:15:14:07:31]: Info: Desktop resolution [2560x1440]
[2023:08:15:14:07:31]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:15:14:07:31]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.675781,0.313477]
Green Primary      : [0.279297,0.647461]
Blue Primary       : [0.151367,0.0722656]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5132 nits
Max Luminance      : 248.379 nits
Max Full Luminance : 248.379 nits
[2023:08:15:14:07:31]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:15:14:07:31]: Info: SDR color coding [Rec. 709]
[2023:08:15:14:07:31]: Info: Color range: [MPEG]
[2023:08:15:14:07:44]: Info: CLIENT DISCONNECTED
[2023:08:15:14:09:06]: Info: Trying encoder [nvenc]
[2023:08:15:14:09:06]: Info: 
Device Description : NVIDIA GeForce RTX 4070
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002786
Device Video Mem   : 12026 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16344 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 2560x190
Virtual Desktop    : 4480x1440
[2023:08:15:14:09:06]: Info: Desktop resolution [1920x1080]
[2023:08:15:14:09:06]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:15:14:09:06]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:15:14:09:06]: Info: SDR color coding [Rec. 601]
[2023:08:15:14:09:06]: Info: Color range: [JPEG]
[2023:08:15:14:09:07]: Info: 
Device Description : NVIDIA GeForce RTX 4070
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002786
Device Video Mem   : 12026 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16344 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 2560x190
Virtual Desktop    : 4480x1440
[2023:08:15:14:09:07]: Info: Desktop resolution [1920x1080]
[2023:08:15:14:09:07]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:15:14:09:07]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:15:14:09:07]: Info: SDR color coding [Rec. 601]
[2023:08:15:14:09:07]: Info: Color range: [JPEG]
[2023:08:15:14:09:08]: Info: 
Device Description : NVIDIA GeForce RTX 4070
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002786
Device Video Mem   : 12026 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16344 MiB
Feature Level      : 0x0000B100
Capture size       : 1920x1080
Offset             : 2560x190
Virtual Desktop    : 4480x1440
[2023:08:15:14:09:08]: Info: Desktop resolution [1920x1080]
[2023:08:15:14:09:08]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:15:14:09:08]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.149414,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.5 nits
Max Luminance      : 270 nits
Max Full Luminance : 270 nits
[2023:08:15:14:09:08]: Info: SDR color coding [Rec. 709]
[2023:08:15:14:09:08]: Info: Color range: [JPEG]
[2023:08:15:14:09:08]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:08:15:14:09:08]: Info: 
[2023:08:15:14:09:08]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2023:08:15:14:09:08]: Info: 
[2023:08:15:14:09:08]: Info: Found encoder nvenc: [h264_nvenc, hevc_nvenc]
[2023:08:15:14:09:08]: Info: CLIENT CONNECTED
[2023:08:15:14:09:08]: Info: 
Device Description : NVIDIA GeForce RTX 4070
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002786
Device Video Mem   : 12026 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16344 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1440
Offset             : 0x0
Virtual Desktop    : 4480x1440
[2023:08:15:14:09:08]: Info: Desktop resolution [2560x1440]
[2023:08:15:14:09:08]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:15:14:09:08]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.675781,0.313477]
Green Primary      : [0.279297,0.647461]
Blue Primary       : [0.151367,0.0722656]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5132 nits
Max Luminance      : 248.379 nits
Max Full Luminance : 248.379 nits
[2023:08:15:14:09:08]: Info: Capture format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:08:15:14:09:08]: Info: SDR color coding [Rec. 709]
[2023:08:15:14:09:08]: Info: Color range: [MPEG]
[2023:08:15:14:09:19]: Info: CLIENT DISCONNECTED
```

**Comment by Gaeus** [comment] 2023-08-15 18:49
FIX : The issue came from my internet solution, i'm using a wifi mesh network, and the satellite my Host was plugged into (An Orbi from Netgear) had been slightly moved while cleaning the house, after rebooting the satellite the "crakling" is gone...

It's still weird that it would only happen with sunshine and not Steam Link. But at least it's fixed.

**Comment by ZigZagT** [comment] 2023-08-16 17:34
I think this happens when low latency streaming combined with unstable network connection.

at default settings Steam Link has a higher latency than sunshine therefore is less prone to this issue.

**Comment by ReenigneArcher** [comment] 2023-09-02 01:56
Duplicate of #1389

**Closed** 2023-09-02 01:56 UTC
Labels: invalid:duplicate, audio:windows
