### ISSUE TITLE
build failed used macports

### ISSUE THREAD

**Issue by statmasterY** [LizardByte/Sunshine#3176] opened 2024-09-12 12:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

I used Portfile in the latest release and  installed sunshine, error occurs.

--->  Building Sunshine                                  
Error: Failed to build Sunshine: command execution failed
Error: See /opt/local/var/macports/logs/_Users_jinmingshu_ports_multimedia_sunshine/Sunshine/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there
is a bug.
Error: Processing of port Sunshine failed
--->  Some of the ports you installed have notes:
  libheif has the following notes:
    Support for rav1e now disabled by default; enable via +rav1e
jinmingshu@jinmingshudeAir ports % open  /opt/local/var/macports/logs/_Users_jinmingshu_ports_multimedia_sunshine/Sunshine/main.log

### Host Operating System

Docker

### Operating System Version

13.0 (22A380)

### Architecture

32 bit

### Sunshine commit or version

v2024.910.123325

### Package

Linux - AppImage

### GPU Type

AMD

### GPU Model

Apple M1

### GPU Driver/Mesa Version

unknown

### Capture Method

None

### Config

```Shell
# MacPorts system-wide configuration file for ports tree sources.
#
# To change how MacPorts fetches base, see rsync_server and rsync_dir in
# macports.conf.

# To add a local source, add a "file://" entry.
#
#   Example: file:///Users/landonf/misc/MacPorts/ports
#
# To prevent a source from synchronizing when `port sync` is used,
# append "[nosync]" at the end.
#
#   Example: file:///Users/landonf/misc/MacPorts/ports [nosync]
#
# Note that MacPorts parses source URLs in order; when a port appears in
# multiple sources, it installs the first occurrence. For local sources
# to shadow remote ones, "file://" URLs must come before other URLs.

# A list of rsync mirrors is available at
# https://trac.macports.org/wiki/Mirrors#Portfiles.
#
# If an "rsync://" URL points to a .tar file, a signed .rmd160 file must
# exist in the same directory on the server and will be used to verify
# its integrity.
#
# For proper functionality of various resources (port groups, mirror
# sites, etc.), the primary MacPorts source must always be tagged
# "[default]", even if switched from the default "rsync://" URL.

rsync://rsync.macports.org/macports/release/tarballs/ports.tar.gz [default]
# rsync://pek.cn.rsync.macports.org/macports/release/tarballs/ports.tar

file:///Users/jinmingshu/ports
```

### Relevant log output

```shell
:info:build /usr/bin/ar qc libboost_chrono.a CMakeFiles/boost_chrono.dir/src/chrono.cpp.o CMakeFiles/boost_chrono.dir/src/process_cpu_clocks.cpp.o CMakeFiles/boost_chrono.dir/src/thread_clock.cpp.o
:info:build /usr/bin/ranlib libboost_chrono.a
:info:build make[2]: Leaving directory `/opt/local/var/macports/build/_Users_jinmingshu_ports_multimedia_sunshine/Sunshine/work/build'
:info:build [ 11%] Built target boost_chrono
:info:build make[1]: Leaving directory `/opt/local/var/macports/build/_Users_jinmingshu_ports_multimedia_sunshine/Sunshine/work/build'
:info:build make: *** [all] Error 2
:info:build make: Leaving directory `/opt/local/var/macports/build/_Users_jinmingshu_ports_multimedia_sunshine/Sunshine/work/build'
:info:build Command failed:  cd "/opt/local/var/macports/build/_Users_jinmingshu_ports_multimedia_sunshine/Sunshine/work/build" && /usr/bin/make -j8 -w all VERBOSE=ON 
:info:build Exit code: 2
:error:build Failed to build Sunshine: command execution failed
:debug:build Error code: CHILDSTATUS 89980 2
:debug:build Backtrace: command execution failed
:debug:build     while executing
:debug:build "system {*}$notty {*}$callback {*}$nice $fullcmdstring"
:debug:build     invoked from within
:debug:build "command_exec -callback portprogress::target_progress_callback build"
:debug:build     (procedure "portbuild::build_main" line 10)
:debug:build     invoked from within
:debug:build "$procedure $targetname"
:error:build See /opt/local/var/macports/logs/_Users_jinmingshu_ports_multimedia_sunshine/Sunshine/main.log for details.
```

**Comment by ReenigneArcher** [comment] 2024-09-12 12:39
Duplicate of #3169

**Closed by ReenigneArcher** 2024-09-12 12:39 UTC
