### ISSUE TITLE
Trouble With Installing:  App Cycles On and Off in System Tray

### ISSUE THREAD

**Issue by Mopete118** [LizardByte/Sunshine#2194] opened 2024-02-29 17:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Trying to install Sunshine on my new pc (Ryzen 7 and 4090).  It worked with no  issue on my previous rig (Intel i5 and 2080).  What will happen is, the installer will finish and everything appears to go smoothly.  When I try to access the localhost site, i get the "this site cannot be reached"  page.  When I look at the system tray, i see the Sunshine app constantly appearing and disappearing.  I've tried the installer, and portable both, disabled virus and firewall protection temporarily, and nothing has worked.

### Expected Behavior

Normally you install, access the webpage, setup your username and pin, and then go into the settings.

### Additional Context

Have looked up and down over the internet for solutions and don't see many issues related to mine that have been solved.

### Host Operating System

Windows

### Operating System Version

Windows 11 Home

### Architecture

64 bit

### Sunshine commit or version

v0.21.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

4090FE

### GPU Driver/Mesa Version

551.61

### Config

```Shell
config file won't copy, and when opened in notepad, is completely blank.
```

### Apps

```json
{
  "env": {
    "PATH": "$(PATH);$(ProgramFiles(x86))\\Steam"
  },
  "apps": [
    {
      "name": "Desktop",
      "image-path": "desktop.png"
    },
    {
      "name": "Steam Big Picture",
      "detached": [
        "steam steam://open/bigpicture"
      ],
      "image-path": "steam.png"
    }
  ]
}
```

### Relevant log output

```shell
[2024:02:29:12:33:20]: Info: nvprefs: Opened undo file from previous improper termination
[2024:02:29:12:33:20]: Info: nvprefs: Restored OGL_CPL_PREFER_DXPRESENT for base profile
[2024:02:29:12:33:20]: Info: nvprefs: Restored global profile settings from undo file - deleting the file
[2024:02:29:12:33:20]: Info: nvprefs: No need to modify application profile settings
[2024:02:29:12:33:20]: Info: nvprefs: Changed OGL_CPL_PREFER_DXPRESENT to OGL_CPL_PREFER_DXPRESENT_PREFER_ENABLED for base profile
[2024:02:29:12:33:20]: Info: Sunshine version: 0.21.0
[2024:02:29:12:33:20]: Info: Compiling shaders...
[2024:02:29:12:33:20]: Info: System tray created
[2024:02:29:12:33:20]: Info: Compiled shaders
[2024:02:29:12:33:21]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2024:02:29:12:33:21]: Info: Trying encoder [nvenc]
[2024:02:29:12:33:21]: Info: ddprobe.exe [1] [] returned: 0x887A0004
[2024:02:29:12:33:21]: Info: ddprobe.exe [2] [] returned: 0x00000000
[2024:02:29:12:33:21]: Info: Set GPU preference: 2
[2024:02:29:12:33:21]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24142 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 15946 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2024:02:29:12:33:21]: Info: Active GPU has HAGS enabled
[2024:02:29:12:33:21]: Info: Using realtime GPU priority
[2024:02:29:12:33:21]: Info: Desktop resolution [3840x2160]
[2024:02:29:12:33:21]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2024:02:29:12:33:21]: Info: Display refresh rate [119.88Hz]
[2024:02:29:12:33:21]: Info: Requested frame rate [60fps]
[2024:02:29:12:33:21]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 10
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.150391,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.01 nits
Max Luminance      : 1499 nits
Max Full Luminance : 799 nits
[2024:02:29:12:33:21]: Info: 
Device Description : NVIDIA GeForce RTX 4090
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002684
Device Video Mem   : 24142 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 15946 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 3840x2160
[2024:02:29:12:33:21]: Info: Active GPU has HAGS enabled
[2024:02:29:12:33:21]: Info: Using realtime GPU priority
[2024:02:29:12:33:21]: Info: Desktop resolution [3840x2160]
[2024:02:29:12:33:21]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2024:02:29:12:33:21]: Info: Display refresh rate [119.88Hz]
[2024:02:29:12:33:21]: Info: Requested frame rate [60fps]
[2024:02:29:12:33:21]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 10
Red Primary        : [0.639648,0.330078]
Green Primary      : [0.299805,0.599609]
Blue Primary       : [0.150391,0.0595703]
White Point        : [0.3125,0.329102]
Min Luminance      : 0.01 nits
Max Luminance      : 1499 nits
Max Full Luminance : 799 nits
[2024:02:29:12:33:21]: Info: SDR color coding [Rec. 601]
[2024:02:29:12:33:21]: Info: Color depth: 8-bit
[2024:02:29:12:33:21]: Info: Color range: [JPEG]
[2024:02:29:12:33:21]: Info: NvEnc: created encoder P1 two-pass rfi
```

**Comment by leeson865** [comment] 2024-03-01 04:15
I have the same issue, but I think it only started popping up after installing the new Nvidia app (which uninstalled geforce experience). Does this issue happen when HDR is switched off on your PC? I reckon it might be related to the Nvidia app and its RTX HDR functionalities.

**Comment by leeson865** [comment] 2024-03-01 04:17
Confirmed: Disable RTX HDR on the individual Sunshine app profile in the Nvidia app and it fixes the issue straight away: https://github.com/LizardByte/Sunshine/issues/2163

**Comment by cgutman** [comment] 2024-03-01 07:09
Duplicate of #2163

**Closed by cgutman** 2024-03-01 07:09 UTC
