### ISSUE TITLE
Mouse cursor appears frozen at upper left corner if no mouse/keyboard device connected

### ISSUE THREAD

**Issue by laggykiller** [LizardByte/Sunshine#3492] opened 2024-12-26 20:25 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [x] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

When connect with Moonlight (Tested on Android, Windows), Mouse cursor appears frozen at upper left corner if no mouse/keyboard device connected.

The cursor actually moves but the icon appears not moving.

This is resolved immediately when I insert mouse/keyboard USB device to the computer.

Computer is running Windows.

### Host Operating System

Windows

### Operating System Version

Windows 11

### Architecture

amd64/x86_64

### Sunshine commit or version

v0.23.1

### Package

Windows - installer (recommended)

### GPU Type

Intel

### GPU Model

Intel

### GPU Driver/Mesa Version

Intel Iris Plus Graphics 655

### Capture Method

None

### Config

```Shell

```

### Apps

```json

```

### Relevant log output

```shell
-
```

**Comment by ReenigneArcher** [comment] 2024-12-28 22:01
Is this a duplicate of #2801?

**Comment by ReenigneArcher** [comment] 2024-12-28 22:03
Also, this is mentioned in the docs. https://github.com/LizardByte/Sunshine/pull/3366

**Closed by ReenigneArcher** 2024-12-28 22:03 UTC
Labels: input:mouse
