### ISSUE TITLE
HDR support in windows

### ISSUE THREAD

**Issue by svenlange2** [LizardByte/Sunshine#499] opened 2022-11-15 20:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Describe the Bug

When starting in hevc_mode=3, the server detects no HDR support and refuses to start with "Fatal: Couldn't find any encoder". Is it supported in Windows 10 or not ? Am I missing some settings ? Documentation offers no clue. RTX 3070 sure works in HDR mode over GameStream.

### Additional Context

When activating HDR Desktop mode the server does not even test the codecs but crashes immediately. 

### Host Operating System

Windows

### Operating System Version

10

### Sunshine commit or version

0.15

### GPU Type

Nvidia

### GPU Model

RTX 3070

### GPU Driver/Mesa Version

526.86

### Relevant log output

```Shell
[2022:11:15:22:49:11]: Debug: ------  hevc ------
[2022:11:15:22:49:11]: Debug: PASSED: supported
[2022:11:15:22:49:11]: Debug: REF_FRAMES_RESTRICT: supported
[2022:11:15:22:49:11]: Debug: REF_FRAMES_AUTOSELECT: supported
[2022:11:15:22:49:11]: Debug: SLICE: supported
[2022:11:15:22:49:11]: Debug: CBR: supported
[2022:11:15:22:49:11]: Debug: DYNAMIC_RANGE: unsupported
[2022:11:15:22:49:11]: Debug: VUI_PARAMETERS: supported
[2022:11:15:22:49:11]: Debug: NALU_PREFIX_5b: unsupported
```

**Comment by zerkz** [comment] 2022-12-18 18:47
I had to disable HDR to get sunshine to work at all for me on 6900 XT.

**Comment by Gammler** [comment] 2022-12-19 09:00
Please fix this...

**Comment by davidfletchercc** [comment] 2022-12-19 13:02
Same here.  Can't run Sunshine with HDR enable, also prevents running the Main 10 codec as a result.  Screen shot with debug below - not much to see other than applications halts before next expected line which is something like the second screenshot
![Screenshot 2022-12-19 125825](https://user-images.githubusercontent.com/64904299/208431642-6f9acc5f-9ad5-4c9e-b949-2d4aebd25a2c.png)

![Screenshot 2022-12-19 130204](https://user-images.githubusercontent.com/64904299/208432153-f9c5af64-0b7e-430d-9271-c81e23b08d6d.png)

Other than HDR - Sunshine appears to be awesome!

**Comment by KuleRucket** [comment] 2022-12-19 13:05
Existing feature request: https://github.com/LizardByte/Sunshine/discussions/376

**Comment by iopean** [comment] 2022-12-19 13:05
Same here. Can't run Sunshine with HDR enable, also prevents running the Main 10 codec as a result. Screen shot with debug below - not much to see other than applications halts before next expected line which is something like the second screenshot

![Screenshot 2022-12-19 125825](https://user-images.githubusercontent.com/64904299/208432701-1db0192c-3209-4f61-ab5b-16655ba6fd78.png)

![Screenshot 2022-12-19 130204](https://user-images.githubusercontent.com/64904299/208432743-95933d83-5724-4627-b7b7-740930aa3f08.png)

Other than HDR - Sunshine appears to be awesome!

**Comment by ReenigneArcher** [comment] 2022-12-19 13:21
Closing as a duplicate of the previously mentioned feature request.

**Closed by ReenigneArcher** 2022-12-19 13:21 UTC
