### ISSUE TITLE
MacOS - Compilation fails when using MacPorts for v0.22

### ISSUE THREAD

**Issue by thejudge22** [LizardByte/Sunshine#2228] opened 2024-03-06 17:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Trying to compile using the MacPorts version fails when running sudo port install sunshine.  Please see main.log attached.

### Additional Context

[main.log](https://github.com/LizardByte/Sunshine/files/14513485/main.log)

### Host Operating System

macOS

### Operating System Version

Sonoma 14.3.1

### Architecture

64 bit

### Sunshine commit or version

0.22.0

### Package

macOS - Portfile

### GPU Type

n/a

### GPU Model

Apple M2

### GPU Driver/Mesa Version

Apple M2

### Config

```Shell
n/a - Sunshine never compiles
```

### Relevant log output

```shell
:info:build make[2]: Leaving directory `/opt/local/var/macports/build/_Users_mark_ports_multimedia_sunshine/Sunshine/work/build'
:info:build [ 24%] Built target web-ui
:info:build /opt/local/var/macports/build/_Users_mark_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.22.0/src/main.cpp:110:59: error: 'codecvt_utf8<wchar_t>' is deprecated [-Werror,-Wdeprecated-declarations]
:info:build   std::locale::global(std::locale(std::locale(), new std::codecvt_utf8<wchar_t>));
:info:build                                                           ^
:info:build /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/c++/v1/codecvt:187:28: note: 'codecvt_utf8<wchar_t>' has been explicitly marked deprecated here
:info:build class _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 codecvt_utf8
:info:build                            ^
:info:build /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/c++/v1/__config:1037:41: note: expanded from macro '_LIBCPP_DEPRECATED_IN_CXX17'
:info:build #    define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
:info:build                                         ^
:info:build /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/c++/v1/__config:1010:49: note: expanded from macro '_LIBCPP_DEPRECATED'
:info:build #      define _LIBCPP_DEPRECATED __attribute__((__deprecated__))
:info:build                                                 ^
:info:build 1 error generated.
:info:build make[2]: *** [CMakeFiles/sunshine.dir/src/main.cpp.o] Error 1
:info:build make[2]: Leaving directory `/opt/local/var/macports/build/_Users_mark_ports_multimedia_sunshine/Sunshine/work/build'
:info:build make[1]: *** [CMakeFiles/sunshine.dir/all] Error 2
:info:build make[1]: Leaving directory `/opt/local/var/macports/build/_Users_mark_ports_multimedia_sunshine/Sunshine/work/build'
:info:build make: *** [all] Error 2
:info:build make: Leaving directory `/opt/local/var/macports/build/_Users_mark_ports_multimedia_sunshine/Sunshine/work/build'
:info:build Command failed:  cd "/opt/local/var/macports/build/_Users_mark_ports_multimedia_sunshine/Sunshine/work/build" && /usr/bin/make -j10 -w all VERBOSE=ON 
:info:build Exit code: 2
:error:build Failed to build Sunshine: command execution failed
:debug:build Error code: CHILDSTATUS 20225 2
:debug:build Backtrace: command execution failed
:debug:build     while executing
:debug:build "system {*}$notty {*}$callback {*}$nice $fullcmdstring"
:debug:build     invoked from within
:debug:build "command_exec -callback portprogress::target_progress_callback build"
:debug:build     (procedure "portbuild::build_main" line 10)
:debug:build     invoked from within
:debug:build "$procedure $targetname"
:error:build See /opt/local/var/macports/logs/_Users_mark_ports_multimedia_sunshine/Sunshine/main.log for details.
```

**Comment by ReenigneArcher** [comment] 2024-03-06 18:17
Duplicate of #2210

**Closed by ReenigneArcher** 2024-03-06 18:17 UTC
Labels: os:macOS
