### ISSUE TITLE
Ubuntu 22.04 deb download, Activates voice assist?

### ISSUE THREAD

**Issue by i1Cps** [LizardByte/Sunshine#2785] opened 2024-07-01 11:27 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [x] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

I noticed there's two Ubuntu 22.04 deb downloads. The one I downloaded when executed launches the Ubuntu setup turns of 'night light', and then turns on some automated voice whenever I hover over anything. (Almost like malware but I refuse to believe that)

Is that normal?

If so how do I turn that off?

### Expected Behavior

A clean install and run of Sunshine

### Host Operating System

Linux

### Operating System Version

Ubuntu 22.04

### Architecture

64 bit

### Sunshine commit or version

v0.23.1

### Package

Linux - deb

### GPU Type

Nvidia

### GPU Model

RTX 3060

### GPU Driver/Mesa Version

535.183.01

### Capture Method

None

### Config

```Shell
Didnt even get that far
```

### Relevant log output

```shell
NA
```

**Comment by ReenigneArcher** [comment] 2024-07-01 14:26
Duplicate of #1303

**Closed by ReenigneArcher** 2024-07-01 14:26 UTC
