### ISSUE TITLE
Instant "Connection terminated" on client and vague error in logs (Unable to stream via internet)

### ISSUE THREAD

**Issue by Ravnger** [LizardByte/Sunshine#1852] opened 2023-11-18 19:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

When I try connecting to my host PC via Moonlight on an external network, the whole loading process completes, going through "Starting desktop," "Starting RTSP handshake," etc. When it completes, the client (phone) immediately shows "connection terminated" with no error code or other information.
There is an error in the host's Sunshine log that is obviously related. 
Warning: Rejected connection from [::XXX:XXX.XXX.XXX.XXX]: it's not properly set up
I'll share more of the log in the "Relevent log output" section.

### Expected Behavior

While connected to a network outside of home, I should be able to connect my client to my PC, clean and simple.

### Additional Context

Very rarely, this will resolve itself, and stop working again when I disconnect and reconnect my phone's internet. Might be related to identifying my phone.
CPU: Ryzen 9 3900x
32gb RAM
Tested with host connected to both ethernet and Wifi
Linksys TP-Link Archer C7 router
Updated from Win10 to 11 yesterday, also migrated from GeForce Experience to Sunshine on host (due to resolution bugs with Nvidia GamesStream)

### Host Operating System

Windows

### Operating System Version

Windows 11 Pro, 23H2, OS Build 22631.2715

### Architecture

64 bit

### Sunshine commit or version

0.21.0, also tested on the nightly release of 11/18/23

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

GeForce RTX 4060 Ti 16GB

### GPU Driver/Mesa Version

546.17

### Config

```Shell
address_family = both
upnp = enabled
origin_web_ui_allowed = pc
```

### Relevant log output

```shell
Device Description : NVIDIA GeForce RTX 4060 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002805
Device Video Mem   : 16123 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 16338 MiB
Feature Level      : 0x0000B100
Capture size       : 2560x1440
Offset             : 0x0
Virtual Desktop    : 2560x1440
[2023:11:18:13:36:59]: Info: Active GPU has HAGS disabled
[2023:11:18:13:36:59]: Info: Using realtime GPU priority
[2023:11:18:13:36:59]: Info: Desktop resolution [2560x1440]
[2023:11:18:13:36:59]: Info: Desktop format [DXGI_FORMAT_B8G8R8A8_UNORM]
[2023:11:18:13:36:59]: Info: Display refresh rate [164.847Hz]
[2023:11:18:13:36:59]: Info: Requested frame rate [60fps]
[2023:11:18:13:36:59]: Info:
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709
Bits Per Color     : 8
Red Primary        : [0.673828,0.31543]
Green Primary      : [0.28125,0.643555]
Blue Primary       : [0.151367,0.0683594]
White Point        : [0.313477,0.329102]
Min Luminance      : 0.5132 nits
Max Luminance      : 248.379 nits
Max Full Luminance : 248.379 nits
[2023:11:18:13:36:59]: Info: SDR color coding [Rec. 709]
[2023:11:18:13:36:59]: Info: Color depth: 10-bit
[2023:11:18:13:36:59]: Info: Color range: [JPEG]
[2023:11:18:13:36:59]: Info: NvEnc: created encoder P1 10-bit two-pass rfi
[2023:11:18:13:36:59]: Info:
[2023:11:18:13:36:59]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2023:11:18:13:36:59]: Info:
[2023:11:18:13:36:59]: Info: Found H.264 encoder: h264_nvenc [nvenc]
[2023:11:18:13:36:59]: Info: Found HEVC encoder: hevc_nvenc [nvenc]
[2023:11:18:13:36:59]: Info: Found AV1 encoder: av1_nvenc [nvenc]
[2023:11:18:13:36:59]: Info: Executing [Desktop]
[2023:11:18:13:37:00]: Info: nvprefs: No need to modify application profile settings
[2023:11:18:13:37:00]: Info: nvprefs: No need to modify global profile settings
[2023:11:18:13:37:00]: Info: WLAN interface 0 is now in low latency mode
[2023:11:18:13:37:01]: Warning: Rejected connection from [::xxx:xxx.xxx.xxx.xxx]: it's not properly set up
[2023:11:18:13:37:10]: Error: Initial Ping Timeout
[2023:11:18:13:37:10]: Error: Initial Ping Timeout
[2023:11:18:13:37:10]: Info: ::xxx:xxx.xxx.xxx.xxx: Ping Timeout
```

**Comment by ReenigneArcher** [comment] 2023-11-18 19:56
Duplicate of #1804

**Closed by ReenigneArcher** 2023-11-18 19:56 UTC

**Comment by Ravnger** [comment] 2023-11-18 20:00
This happens when connecting by IPV4, and log output is totally different. They might be related though.

**Comment by Ravnger** [comment] 2023-11-18 20:18
@ReenigneArcher How do you know it's a duplicate of #1804?

**Comment by yhw2003** [comment] 2024-06-15 20:12
Could you please let me know if this issue has been resolved? I have been following the updates and would like to confirm the current status.
