### ISSUE TITLE
MacPort cannot install 0.20.0 release

### ISSUE THREAD

**Issue by BlackdeerY** [LizardByte/Sunshine#1338] opened 2023-05-31 02:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

I was using the 0.19.1 release with MacPort on my Mac.
I tried to install the 0.20.0 release, but it doesn't install.
I also did a selfupdate on MacPort, and also reinstalled the Xcode Command Line Tools.
(So the warning when starting from sudo port install sunshine does not appear.)

I attach `main.log`.
[main.log](https://github.com/LizardByte/Sunshine/files/11608034/main.log)

### Host Operating System

macOS

### Operating System Version

Ventura 13.4(22F66)

### Architecture

64 bit

### Sunshine commit or version

0.20.0

### Package

macOS - Portfile

### GPU Type

Intel

### GPU Model

Intel UHD Graphics 630 1536 MB

### GPU Driver/Mesa Version

Don't_Know

### Config

```Shell
Not Using Bug. It's Install Bug.
```

### Relevant log output

```shell
Please see main.log attached in Describe the Bug. Too Long (65536 over).
```

**Comment by ReenigneArcher** [comment] 2023-08-30 22:38
Duplicate of #1348

**Closed by ReenigneArcher** 2023-08-30 22:38 UTC
Labels: invalid:duplicate, os:macOS
