### ISSUE TITLE
Unable to cleanup NvFBC

### ISSUE THREAD

**Issue by Seb85** [LizardByte/Sunshine#363] opened 2022-09-11 16:27 UTC
### Describe the Bug

Connecting to sunshine causes the error:
Error: Couldn't destroy session handle: Unable to cleanup NvFBC

The latest NVIDIA driver is installed and patched.

I opt on moonlight a black screen, with sound and mouse but crashes after a few seconds.

### Host Operating System

Linux

### Operating System Version

Linux Mint 21

### Architecture

64 bit

### Sunshine Version

0.14.1

### GPU Type

Nvidia

### GPU Model

1660 TI

### GPU Driver/Mesa Version

515.65.01

### Relevant log output

```Shell
[2022:09:11:18:17:41]: Error: Couldn't destroy session handle: Unable to cleanup NvFBC
[2022:09:11:18:17:41]: Error: Couldn't release NvFBC context from current thread: Unable to cleanup NvFBC
```

**Comment by KuleRucket** [comment] 2022-09-11 17:55
Look like duplicate of #47 

I couldn't find out the cause.

**Comment by Seb85** [comment] 2022-09-11 18:13
Resolving this ticket did not work for me.

Sunshine worked fine for several weeks, the linux snapshot from the day before where everything was working didn't even solve my problem.

These are the only error messages I see.

**Comment by ReenigneArcher** [comment] 2022-09-11 23:31
Is this the same as https://github.com/LizardByte/Sunshine/issues/364 ?

**Comment by KuleRucket** [comment] 2022-09-12 07:06
Was this with moonlight v4.2.0? There was a problem with that release and there is a new version:
"v4.2.1 is a hotfix release to address a bug in v4.2.0 that prevented streaming from hosts running [Sunshine](https://github.com/LizardByte/Sunshine). The original release notes for v4.2.0 are below."

**Comment by Seb85** [comment] 2022-09-12 12:36
Updating the moonlight client fixed the problem.

Thanks for your help

**Closed** 2022-09-12 12:40 UTC
