### ISSUE TITLE
MacPorts build fails on M2 Mac Mini (2023) when ffmpeg is installed

### ISSUE THREAD

**Issue by jmou** [LizardByte/Sunshine#3169] opened 2024-09-10 18:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [x] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

`sudo port install sunshine`

Using https://github.com/LizardByte/Sunshine/releases/download/v2024.910.123325/Portfile

### Expected Behavior

build succeeds

### Additional Context

[main.log](https://github.com/user-attachments/files/16949191/main.log)

I have looked for similar issues and seen #2482 and #3052 but they seem to describe different failures.

### Host Operating System

macOS

### Operating System Version

14.6.1

### Architecture

arm

### Sunshine commit or version

8098df6c381fcb8d9e847144069796114b2dd62c

### Package

macOS - Portfile

### GPU Type

Apple Silicon

### GPU Model

Apple M2

### GPU Driver/Mesa Version

n/a

### Capture Method

None

### Config

```Shell
n/a
```

### Relevant log output

```shell
full main.log attached above

--- snip ---
:info:build In file included from /opt/local/var/macports/build/_Users_joe_.dotfiles_macmini_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.23.1/src/cbs.cpp:6:
:info:build In file included from /opt/local/var/macports/build/_Users_joe_.dotfiles_macmini_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.23.1/third-party/build-deps/ffmpeg/macos-aarch64/include/cbs/cbs_h264.h:25:
:info:build In file included from /opt/local/var/macports/build/_Users_joe_.dotfiles_macmini_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.23.1/third-party/build-deps/ffmpeg/macos-aarch64/include/cbs/cbs.h:28:
:info:build /opt/local/var/macports/build/_Users_joe_.dotfiles_macmini_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.23.1/third-party/build-deps/ffmpeg/macos-aarch64/include/cbs/codec_par.h:206:5: error: unknown type name 'AVChannelLayout'
:info:build     AVChannelLayout ch_layout;
:info:build     ^
:info:build In file included from /opt/local/var/macports/build/_Users_joe_.dotfiles_macmini_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.23.1/src/cbs.cpp:9:
:info:build /opt/local/include/libavcodec/avcodec.h:227:6: error: redefinition of 'AVDiscard'
:info:build enum AVDiscard{
:info:build      ^
:info:build /opt/local/var/macports/build/_Users_joe_.dotfiles_macmini_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.23.1/third-party/build-deps/ffmpeg/macos-aarch64/include/cbs/defs.h:210:6: note: previous definition is here
:info:build enum AVDiscard{
:info:build      ^
:info:build In file included from /opt/local/var/macports/build/_Users_joe_.dotfiles_macmini_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.23.1/src/cbs.cpp:9:
:info:build /opt/local/include/libavcodec/avcodec.h:239:6: error: redefinition of 'AVAudioServiceType'
:info:build enum AVAudioServiceType {
:info:build      ^
:info:build /opt/local/var/macports/build/_Users_joe_.dotfiles_macmini_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.23.1/third-party/build-deps/ffmpeg/macos-aarch64/include/cbs/defs.h:222:6: note: previous definition is here
:info:build enum AVAudioServiceType {
:info:build      ^
:info:build In file included from /opt/local/var/macports/build/_Users_joe_.dotfiles_macmini_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.23.1/src/cbs.cpp:9:
:info:build /opt/local/include/libavcodec/avcodec.h:424:16: error: redefinition of 'AVPanScan'
:info:build typedef struct AVPanScan {
:info:build                ^
:info:build /opt/local/var/macports/build/_Users_joe_.dotfiles_macmini_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.23.1/third-party/build-deps/ffmpeg/macos-aarch64/include/cbs/defs.h:240:16: note: previous definition is here
:info:build typedef struct AVPanScan {
:info:build                ^
:info:build In file included from /opt/local/var/macports/build/_Users_joe_.dotfiles_macmini_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.23.1/src/cbs.cpp:9:
:info:build /opt/local/include/libavcodec/avcodec.h:453:16: error: redefinition of 'AVCPBProperties'
:info:build typedef struct AVCPBProperties {
:info:build                ^
:info:build /opt/local/var/macports/build/_Users_joe_.dotfiles_macmini_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.23.1/third-party/build-deps/ffmpeg/macos-aarch64/include/cbs/defs.h:269:16: note: previous definition is here
:info:build typedef struct AVCPBProperties {
:info:build                ^
:info:build In file included from /opt/local/var/macports/build/_Users_joe_.dotfiles_macmini_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.23.1/src/cbs.cpp:9:
:info:build /opt/local/include/libavcodec/avcodec.h:503:16: error: redefinition of 'AVProducerReferenceTime'
:info:build typedef struct AVProducerReferenceTime {
:info:build                ^
:info:build /opt/local/var/macports/build/_Users_joe_.dotfiles_macmini_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.23.1/third-party/build-deps/ffmpeg/macos-aarch64/include/cbs/defs.h:318:16: note: previous definition is here
:info:build typedef struct AVProducerReferenceTime {
:info:build                ^
--- snip ---
:info:build /opt/local/var/macports/build/_Users_joe_.dotfiles_macmini_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.23.1/src/upnp.cpp:112:21: error: no matching function for call to 'UPNP_GetValidIGD'
:info:build       auto status = UPNP_GetValidIGD(device.get(), &urls.el, &data, lan_addr.data(), lan_addr.size());
:info:build                     ^~~~~~~~~~~~~~~~
:info:build /opt/local/include/miniupnpc/miniupnpc.h:122:1: note: candidate function not viable: requires 7 arguments, but 5 were provided
:info:build UPNP_GetValidIGD(struct UPNPDev * devlist,
:info:build ^
:info:build /opt/local/var/macports/build/_Users_joe_.dotfiles_macmini_ports_multimedia_sunshine/Sunshine/work/Sunshine-0.23.1/src/upnp.cpp:334:23: error: no matching function for call to 'UPNP_GetValidIGD'
:info:build         auto status = UPNP_GetValidIGD(device.get(), &urls.el, &data, lan_addr.data(), lan_addr.size());
:info:build                       ^~~~~~~~~~~~~~~~
:info:build /opt/local/include/miniupnpc/miniupnpc.h:122:1: note: candidate function not viable: requires 7 arguments, but 5 were provided
:info:build UPNP_GetValidIGD(struct UPNPDev * devlist,
:info:build ^
:info:build 2 errors generated.
--- snip ---
```

**Comment by ReenigneArcher** [comment] 2024-09-10 18:36
https://github.com/LizardByte/Sunshine/issues/3139#issuecomment-2331468245

**Comment by TheKidThatCodes** [comment] 2024-09-11 11:09
brew sunshine-beta also fails with cmake saying theres no cmake list or smth

**Comment by Pheggas** [comment] 2024-09-13 12:37
Also fails on homebrew on Mac M3 Air. Mention me here so I will provide logs.

**Comment by ReenigneArcher** [comment] 2024-09-13 13:10
Here's the brew issue. https://github.com/LizardByte/Sunshine/issues/2482

Both of these issues are due to the user's environment, as we are having successful builds across macOS-12,13,14 with both homebrew and macports in our CI.

**Comment by ReenigneArcher** [comment] 2024-09-13 13:27
Sorry, I had the wrong issue. Updated now.

Also, no idea what's wrong with your environment. I'm just pointing on that a clean system doesn't have these issues.

**Comment by ReenigneArcher** [comment] 2024-09-13 13:35
Closing in favor of a consolidated issue: #3180

Please add any pertinent information to that issue.

**Closed by ReenigneArcher** 2024-09-13 13:35 UTC
Labels: os:macOS

**Comment by ReenigneArcher** [comment] 2024-09-13 16:30
It's okay if they have different root causes. It's just too overwhelming to have new macOS build issues opened daily. So this one aims to reduce the influx.

Can you post that info about system ffmpeg header on the open issue? Or a PR would also be welcome.

**Comment by jmou** [comment] 2024-09-13 18:40
Looks like you beat me to posting a comment. I'm not sure how to fix it but I'll make a PR if I figure it out.
