### ISSUE TITLE
sound distorted using Pipewire

### ISSUE THREAD

**Issue by adolfotregosa** [LizardByte/Sunshine#168] opened 2022-05-27 15:18 UTC
### Describe the Bug

Any audio comes distorted no matter what stream setting is used in moonlight. I have no idea here to start to fix this.
Any help is appreciated.

Both Host and guest are running manjaro with pipewire + wireplumber.

### Sunshine Host Operating System and Version

Manjaro

### Architecture

64

### Sunshine Version

0.13

### GPU Type

nvidia 

### GPU Model

3060

### GPU Driver/Mesa Version

515.43.04

### Capture Method (Linux Only)

X11

**Comment by adolfotregosa** [comment] 2022-06-08 20:27
First clue. The problem only exists while using pipewire. 
Pulseaudio works fine

**Comment by KuleRucket** [comment] 2022-06-11 22:06
This started happening to me and I remembered getting a pipewire update this week. So I rolled back to a snapshot from a week ago and the sound was fine again. I then held back the update of pipewire + pipewire-pulse, updated the rest and it's still working.

**Comment by KuleRucket** [comment] 2022-06-12 06:27
https://github.com/PipeWire/pipewire/blob/master/NEWS

Highlights:
  - Add 44.1KHz to allowed samplerates. The server can now switch by
    default between 48KHz and 44.1KHz.

So maybe now Sunshine is trying to use a different sampling rate than Moonlight and we need to do something to set it explicitly?

**Comment by KuleRucket** [comment] 2022-06-12 09:56
Thinking about it, if it works with pulseaudio then this a probably a problem with the pipeline-pulse translation. I guess the best solution would be to implement the option to use pipeline natively.

**Comment by adolfotregosa** [comment] 2022-06-12 15:05
> Thinking about it, if it works with pulseaudio then this a probably a problem with the pipeline-pulse translation. I guess the best solution would be to implement the option to use pipeline natively.

pipewire 0.3.52 same issue. If I can actually help on fixing this, please do ask

**Comment by thegamingrestoration** [comment] 2022-06-13 10:40
> This started happening to me and I remembered getting a pipewire update this week. So I rolled back to a snapshot from a week ago and the sound was fine again. I then held back the update of pipewire + pipewire-pulse, updated the rest and it's still working.

Do you still have the snapshot from a week ago? Could you attach it here?

**Comment by KuleRucket** [comment] 2022-06-13 11:13
It's a btrfs snapshot of my root filesystem and wouldn't be much use to you. You can just downgrade the packages though if you want to revert an update (https://wiki.archlinux.org/title/downgrading_packages).

**Comment by schlegp** [comment] 2022-06-13 18:41
I was able to pinpoint the last working pipewire version to 0.3.50-1. I suspect pipewire-pulse to be the culprit, but have for now just downgraded all pipewire packages to this version.

**Comment by falk4243** [comment] 2022-06-14 11:01
The duplicate above was me - my bad, but yeah, same result here and I have taken a closer look at the config files. The additional 44.1 KHz sampling rate is the only difference between v0.3.51 and 0.3.52 I could find. Unfortunately changing  "default.clock.allowed-rates" in /usr/share/pipewire/pipewire.conf back to the previous default (only 48 KHz) doesn't fix the distortions, only downgrading to v51.

**Comment by adolfotregosa** [comment] 2022-06-14 11:20
guys I downgraded pipewire and pipewire-pulse from 52 -> 51 -> 49 and my sound always comes out distorted

**Comment by istori1** [comment] 2022-06-19 00:02
This is also an issue on Fedora 36.

**Comment by thegamingrestoration** [comment] 2022-06-20 18:17
> It's a btrfs snapshot of my root filesystem and wouldn't be much use to you. You can just downgrade the packages though if you want to revert an update (https://wiki.archlinux.org/title/downgrading_packages).

Sorry for the late reply and thank you for the link, I was not aware of the existence of the Arch Linux Archive.

It seems that one of the workers at Red Hat [fixed this issue a few hous ago](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/ff05ebada63c1c91473e1034bfa92da7f938b1b0) , and an user has already confirmed that it works: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2447#note_1435298 .

**Comment by thegamingrestoration** [comment] 2022-06-20 19:04
Ok I can confirm that installing pipewire-git and pipewire-pulse-git in Arch Linux fixed the issue, I just did a local test and the audio capture sounds perfect.

**Comment by KuleRucket** [comment] 2022-06-20 20:23
Good news.

I'll probably wait until they tag it as their release cycle looks pretty fast anyway.

**Comment by KarlVogel** [comment] 2022-06-21 13:58
Commenting here since #220 has been locked. I honestly doubt #220 is the same issue as this one. The pipewire rpm changelog shows the package is using a 0.3.51 version from April:

```
* Thu Apr 28 2022 Wim Taymans <wtaymans@redhat.com> - 0.3.51-1
- Update version to 0.3.51

```

while the pipewire ticket https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2447 shows the bisect commit that caused pipewire 0.3.52 to fail is from june, so after the RPM's version was cut:

```
0d51f3b74e1efc2787e29f00e0ccc4b28b5da8a6 is the first bad commit
commit 0d51f3b74e1efc2787e29f00e0ccc4b28b5da8a6
Author: Wim Taymans <wtaymans@redhat.com>
Date:   Wed Jun 1 15:12:48 2022 +0200

    pulse-server: always send at least fragsize data
    
    Make sure to never send less than the negotiated fragsize to a client.
    Also make sure we don't send too much data in one go. This is more in
    line with what pulseaudio does.
    
    Fixes capture from multiple tabs in chrome.
    
    Fixes #2418

 src/modules/module-protocol-pulse/pulse-server.c | 11 ++++++-----
 1 file changed, 6 insertions(+), 5 deletions(-)
```

Also double checked the SRPM to see if this breaking commit is present, and it's not.


The debian 0.3.51 package was also working fine according to the issue here.

All of this seems to indicate that the issue here is not the same as the issue reported in #220.

**Comment by ReenigneArcher** [comment] 2022-06-21 14:03
@KarlVogel the issue is the same "sound is very distorted" & "Audio distorted" mean the same thing... the cause might be different.

**Comment by KarlVogel** [comment] 2022-06-21 14:06
Ah you're tracking multiple bugs in a single issue. Fair enough.

**Comment by KarlVogel** [comment] 2022-06-22 08:29
Confirming it was a pipewire bug, fixed by https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/ff05ebada63c1c91473e1034bfa92da7f938b1b0

**Comment by JustPlainGarak** [comment] 2022-07-01 13:50
G'morning! Just sharing here as well, pipewire 0.3.53-1 in the test repo for Fedora 36 fixes this issue as well, should hit production in a few days.

**Closed as completed** 2022-07-01 13:52 UTC
Labels: os:Linux:Arch, os:Linux:Debian, os:Linux:Fedora, audio:pipewire

**Comment by KuleRucket** [comment] 2022-07-01 19:24
Also working on Arch again now

**Comment by adolfotregosa** [comment] 2022-07-02 13:15
I have one machine that started working correctly but another that still doesn't, it still distorts.
I have done a complete clean arch reinstall and it still is happening.
