### ISSUE TITLE
WINDOWS AMF: cursor not shown when streaming with AMF

### ISSUE THREAD

**Issue by Quackdoc** [LizardByte/Sunshine#513] opened 2022-11-26 14:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Describe the Bug

When streaming the desktop with AMF on windows the cursor fails to appear.

### Expected Behavior

Show the cursor on screen

### Additional Context

I have tested software encoding and cursor appears just fine.

### Host Operating System

Windows

### Operating System Version

Windows 11 (10.0 Build 22000)

### Architecture

64 bit

### Sunshine commit or version

0.15.0

### Package

Windows - installer

### GPU Type

AMD

### GPU Model

Rx 580

### GPU Driver/Mesa Version

Driver Version 22.20.29.07-221110a-385749C-AMD-Software-Adrenalin-Edition

**Comment by ryanteck** [comment] 2022-12-12 19:13
A +1 for this issue, I get no Cursor on a host using Windows.

Pretty much every detail is the same on my machine, except for having an RX 5700XT instead. The other bug report stuff applies.

**Comment by JamesM92** [comment] 2022-12-19 19:20
So, there is a bit of a work around, 

<html><body>


Ctrl + Alt + ↑   Shift + M | Toggle mouse mode (pointer capture or direct control)
-- | --



</body>
</html>

GameStream on nvidia seemed to know how to handle transitioning between pointer modes on its own. 

I run the issue that if im playing minecraft i need the direct control mode but when i exit out and need to navigate the menu i need pointer capture.

If i try and play in the wrong mode my character flails wildly till I set it right.

A bit of an announce to have to constantly use the hot key every time i need my cursor or not.

**Comment by blitterz** [comment] 2022-12-25 19:34
this is the case for nvenc and windows 10 for me too, sunshine sees it though:

--end relative mouse move packet--
[2022:12:25:20:25:08]: Verbose: Frame [198] :: send [64] shards...
[2022:12:25:20:25:08]: Verbose: type [IDX_ENCRYPTED]
[2022:12:25:20:25:08]: Debug: --begin relative mouse move packet--
deltaX [-16]
deltaY [0]
--end relative mouse move packet--
[2022:12:25:20:25:08]: Verbose: type [IDX_ENCRYPTED]
[2022:12:25:20:25:08]: Debug: --begin relative mouse move packet--
deltaX [-13]
deltaY [0]
--end relative mouse move packet--
[2022:12:25:20:25:08]: Verbose: type [IDX_ENCRYPTED]
[2022:12:25:20:25:08]: Debug: --begin relative mouse move packet--
deltaX [-10]
deltaY [0]
--end relative mouse move packet--
[2022:12:25:20:25:08]: Verbose: type [IDX_ENCRYPTED]
[2022:12:25:20:25:08]: Debug: --begin relative mouse move packet--
deltaX [-7]
deltaY [0]
--end relative mouse move packet--
[2022:12:25:20:25:08]: Verbose: Generating multiple FEC blocks
[2022:12:25:20:25:08]: Verbose: type [IDX_ENCRYPTED]
[2022:12:25:20:25:08]: Debug: --begin relative mouse move packet--
deltaX [-4]
deltaY [0]
--end relative mouse move packet--
[2022:12:25:20:25:08]: Verbose: Frame [199] :: send [101] shards...
[2022:12:25:20:25:08]: Verbose: Frame [199] :: send [101] shards...
[2022:12:25:20:25:08]: Verbose: type [IDX_ENCRYPTED]
[2022:12:25:20:25:08]: Debug: --begin relative mouse move packet--
deltaX [-2]
deltaY [0]
--end relative mouse move packet--
[2022:12:25:20:25:08]: Verbose: Frame [199] :: send [101] shards...
[2022:12:25:20:25:08]: Verbose: type [IDX_ENCRYPTED]
[2022:12:25:20:25:08]: Debug: --begin relative mouse move packet--
deltaX [-1]
deltaY [0]
--end relative mouse move packet--
[2022:12:25:20:25:08]: Verbose: type [IDX_ENCRYPTED]
[2022:12:25:20:25:08]: Debug: --begin relative mouse move packet--
deltaX [-1]
deltaY [0]
--end relative mouse move packet--

is this a Bug or not?

**Comment by Quackdoc** [comment] 2023-01-06 12:45
issue is not exhibited with #681

**Comment by cgutman** [comment] 2023-01-07 00:34
> issue is not exhibited with #681

Excellent find. That pointed me to the issue in the code and I have a fix for it in #720.

**Comment by cgutman** [comment] 2023-01-07 05:18
Please try this build from #720 and see if the issue is resolved: https://github.com/LizardByte/Sunshine/suites/10231526085/artifacts/501564044

If not, please mention what game or custom cursor settings you're using.

Note that this PR does not solve the issue of the mouse cursor not appearing if your host PC doesn't physically have a mouse connected and has no cursor visible locally. This reported issue specifically relates to the case where the mouse cursor appears locally on the host, but not remotely.

**Comment by Quackdoc** [comment] 2023-01-07 05:35
it's working on my end! thanks a bunch.

**Comment by ReenigneArcher** [comment] 2023-01-08 12:57
Please don't close this as it's still present in stable.

**Closed** 2023-01-09 02:03 UTC
Labels: fixed, os:Windows:11, input:mouse
