### ISSUE TITLE
Tracking issue for solving both Intel iGPU and nVidia dGPU on muxless Optimus laptop

### ISSUE THREAD

**Issue by Originalimoc** [LizardByte/Sunshine#1745] opened 2023-10-13 03:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Given I've been using Steam Link 1080P60 with both HW encoder(AVC on iGPU and HEVC on dGPU, can choose in setting) working very well, I'd say freeing up CPU resources for older laptop with only 4/6 "weak(in today's term)" cores is well worth it, memory copy are faster than you think. Frames are in RAM anyway if using SW x264/x265(?), why not sending it to GPU for encoding, HW encoder has much much lower encoding latency

QuickSync init issue which should work but not, init M?? failed , *log later*

NVENC "not implemented?"

Video output port is connected to iGPU not dGPU.

### Expected Behavior

Both encoder can work.

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

20231012 Nightly

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

HD 4600 x GTX 1070

### GPU Driver/Mesa Version

5xx

### Config

```Shell
NA
```

### Relevant log output

```shell
later
```

**Comment by ReenigneArcher** [comment] 2023-10-13 12:30
Duplicate of #945

**Closed by ReenigneArcher** 2023-10-13 12:30 UTC

**Comment by Originalimoc** [comment] 2023-10-13 13:14
@ReenigneArcher I know the issue #994, but Steam Link proved it's not the case.

**Comment by ReenigneArcher** [comment] 2023-10-13 13:21
There's no point in opening issues because another application does something that this doesn't.

Example: Remote Desktop allows sharing printers between the host and client... Not supported between Sunshine and Moonlight... Is it an issue though? No.

Anyway, currently Sunshine is working as intended. Open a PR if you have an improvement. The issue tracker is for actual bugs.

**Comment by ReenigneArcher** [comment] 2023-10-13 13:39
You can open a feature request instead of an issue.

**Comment by Originalimoc** [comment] 2023-10-13 13:40
Hmmmmm you consider this as a new feature... ok...

**Comment by cgutman** [comment] 2023-10-13 15:28
To be clear, hardware video encoding on muxless Optimus/hybrid systems has been supported since the v0.18 release of Sunshine. If you are experiencing issues forcing a fallback to software encoding on v0.20 and the latest nightly builds, please file a bug for that.

**Comment by Originalimoc** [comment] 2023-12-01 14:21
@cgutman No, still doesn't work on my HD4600 + 1070 muxless laptop. Won't load either GPU encoder while Steam Link can.
